"""Write real Python detector modules for discovered subtle ties.

Each discovery becomes `analytics/generated_patterns/pat_<hash>.py` with a
`detect(ctx)` function. Modules are archived and never deleted — only disabled
via registry if needed.

Safe subset: AST-validated, no network/io/exec in generated code.
"""

from __future__ import annotations

import ast
import os
import textwrap
import time
from pathlib import Path
from typing import Any

from analytics.subtle_tie_discover import SubtleTie, discover_subtle_ties, tie_hash

ROOT = Path(__file__).resolve().parents[1]
GEN_DIR = ROOT / "analytics" / "generated_patterns"
ARCHIVE = GEN_DIR / "archive"

_FORBIDDEN_NODES = (
    ast.Import,
    ast.ImportFrom,
    # Call names checked separately
)
_FORBIDDEN_NAMES = frozenset(
    {
        "exec",
        "eval",
        "compile",
        "open",
        "__import__",
        "subprocess",
        "os",
        "sys",
        "socket",
        "requests",
        "pathlib",
        "shutil",
    }
)


def _b(name: str, default: bool = True) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.lower() in ("1", "true", "yes", "on")


def _f(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


def _validate_source(src: str) -> None:
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, _FORBIDDEN_NODES):
            raise ValueError(f"forbidden node {type(node).__name__}")
        if isinstance(node, ast.Name) and node.id in _FORBIDDEN_NAMES:
            raise ValueError(f"forbidden name {node.id}")
        if isinstance(node, ast.Attribute) and node.attr in _FORBIDDEN_NAMES:
            raise ValueError(f"forbidden attr {node.attr}")
        if isinstance(node, ast.Call):
            fn = node.func
            if isinstance(fn, ast.Name) and fn.id in _FORBIDDEN_NAMES:
                raise ValueError(f"forbidden call {fn.id}")
    # Require DETECTOR_ID + detect
    names = {n.name for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}
    assigns = set()
    for n in tree.body:
        if isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    assigns.add(t.id)
    if "detect" not in names:
        raise ValueError("missing detect()")
    if "DETECTOR_ID" not in assigns:
        raise ValueError("missing DETECTOR_ID")


def _render_detector(tie: SubtleTie) -> str:
    """Emit a self-contained detector. Uses only numpy via ctx['np'] and ctx getters."""
    hid = tie_hash(tie)
    did = f"gen_{tie.kind}_{tie.a}_{tie.b}_l{tie.lag}_{hid}"
    a, b = tie.a.upper(), tie.b.upper()
    kind = tie.kind
    lag = int(tie.lag)
    # Direction when pattern fires for the *queried* symbol
    dir_a = int(tie.direction_a)
    dir_b = int(tie.direction_b)
    thr = float(max(0.2, min(0.8, abs(float(tie.stats.get("lead_corr") or tie.stats.get("resid_corr") or tie.stats.get("vol_lead_corr") or tie.stats.get("delayed_corr") or 0.3)) * 0.85)))
    rationale = (tie.rationale or "").replace('"""', "'")[:300]
    leader = a  # for leadlag, `a` is the leader in our SubtleTie convention for resid_leadlag

    body = f'''\
"""AUTO-GENERATED subtle pattern detector — do not hand-edit; never delete.
KIND={kind}  PAIR={a}/{b}  LAG={lag}
RATIONALE={rationale!r}
Generated by analytics.pattern_code_evolver
"""

DETECTOR_ID = {did!r}
FAMILY = "gen"
KIND = {kind!r}
SYMBOLS = ({a!r}, {b!r})
LAG = {lag}
LEADER = {leader!r}
DIR_A = {dir_a}
DIR_B = {dir_b}
THR = {thr}
SCORE_HINT = {float(tie.score):.4f}


def detect(ctx):
    """Return (strength 0..1, direction -1/0/+1, reason, features).

    ctx keys: symbol, get_rets(sym), get_vol(sym), market_rets, np
    """
    np = ctx["np"]
    sym = str(ctx.get("symbol") or "").upper()
    if sym not in SYMBOLS:
        return 0.0, 0, "", {{}}
    get_rets = ctx["get_rets"]
    get_vol = ctx.get("get_vol")
    mkt = ctx.get("market_rets")
    ra = get_rets({a!r})
    rb = get_rets({b!r})
    if ra is None or rb is None or mkt is None:
        return 0.0, 0, "", {{}}
    n = min(len(ra), len(rb), len(mkt))
    if n < 60:
        return 0.0, 0, "", {{}}
    ra, rb, mkt = ra[-n:], rb[-n:], mkt[-n:]

    def _resid(r, m):
        x = m - np.mean(m)
        y = r - np.mean(r)
        beta = float(np.dot(x, y) / (float(np.dot(x, x)) + 1e-12))
        return r - beta * m

    def _ll(x, y, lag):
        if lag <= 0 or len(x) <= lag + 15:
            return 0.0
        a, b = x[:-lag], y[lag:]
        nn = min(len(a), len(b))
        a, b = a[-nn:], b[-nn:]
        if float(np.std(a)) < 1e-12 or float(np.std(b)) < 1e-12:
            return 0.0
        return float(np.corrcoef(a, b)[0, 1])

    ida, idb = _resid(ra, mkt), _resid(rb, mkt)
    strength = 0.0
    reason = ""
    feats = {{}}

    if KIND == "shared_resid":
        raw = float(np.corrcoef(ra, rb)[0, 1]) if float(np.std(ra)) > 1e-12 else 0.0
        rc = float(np.corrcoef(ida, idb)[0, 1]) if float(np.std(ida)) > 1e-12 else 0.0
        feats["raw_corr"] = raw
        feats["resid_corr"] = rc
        if abs(raw) < 0.35 and abs(rc) >= THR:
            strength = min(1.0, (abs(rc) - abs(raw)) / 0.5)
            reason = f"gen:shared_resid {{SYMBOLS[0]}}/{{SYMBOLS[1]}} resid={{rc:+.2f}} raw={{raw:+.2f}}"
    elif KIND in ("resid_leadlag", "delayed_echo"):
        c = _ll(ida, idb, LAG)
        feats["lead_corr"] = c
        if abs(c) >= THR:
            strength = min(1.0, abs(c) / 0.55)
            reason = f"gen:{{KIND}} {{LEADER}}→{{SYMBOLS[1] if LEADER==SYMBOLS[0] else SYMBOLS[0]}} l{{LAG}}d c={{c:+.2f}}"
    elif KIND == "vol_echo":
        if get_vol is None:
            return 0.0, 0, "", {{}}
        va = get_vol(LEADER)
        if va is None:
            return 0.0, 0, "", {{}}
        follower = SYMBOLS[1] if LEADER == SYMBOLS[0] else SYMBOLS[0]
        id_f = idb if follower == SYMBOLS[1] else ida
        nn = min(len(va), len(id_f))
        c = _ll(va[-nn:], id_f[-nn:], LAG)
        feats["vol_lead_corr"] = c
        if abs(c) >= THR:
            strength = min(1.0, abs(c) / 0.55)
            reason = f"gen:vol_echo {{LEADER}} vol→{{follower}} l{{LAG}}d c={{c:+.2f}}"

    if strength < 0.28:
        return 0.0, 0, "", feats
    if sym == {a!r}:
        direction = DIR_A
    else:
        direction = DIR_B
    # Live confirmation: last residual move of leader agrees with stored sign
    last = float(ida[-1]) if LEADER == {a!r} else float(idb[-1])
    if direction != 0 and last != 0.0 and (last > 0) != (direction > 0):
        # opposing last move — soften rather than invert blindly
        strength *= 0.55
    return float(strength), int(direction), reason, feats
'''
    return textwrap.dedent(body)


def write_detector_module(tie: SubtleTie) -> Path | None:
    """Validate + write pat_<hash>.py; archive a copy; register. Never deletes old files."""
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    hid = tie_hash(tie)
    stem = f"pat_{hid}"
    path = GEN_DIR / f"{stem}.py"
    src = _render_detector(tie)
    try:
        _validate_source(src)
    except Exception as e:
        return None

    # If identical content already present, skip rewrite but keep registry fresh
    if path.is_file() and path.read_text(encoding="utf-8") == src:
        from analytics.generated_patterns import register_detector

        try:
            rel = str(path.relative_to(ROOT))
        except ValueError:
            rel = str(path)
        register_detector(
            file_stem=stem,
            detector_id=f"gen_{tie.kind}_{tie.a}_{tie.b}_l{tie.lag}_{hid}",
            kind=tie.kind,
            symbols=[tie.a, tie.b],
            score=tie.score,
            rationale=tie.rationale,
            path=rel,
        )
        return path

    path.write_text(src, encoding="utf-8")
    arch = ARCHIVE / f"{stem}_{int(time.time())}.py"
    arch.write_text(src, encoding="utf-8")

    from analytics.generated_patterns import register_detector

    try:
        rel = str(path.relative_to(ROOT))
    except ValueError:
        rel = str(path)
    register_detector(
        file_stem=stem,
        detector_id=f"gen_{tie.kind}_{tie.a}_{tie.b}_l{tie.lag}_{hid}",
        kind=tie.kind,
        symbols=[tie.a, tie.b],
        score=tie.score,
        rationale=tie.rationale,
        path=rel,
    )
    return path


def discover_and_emit(*, max_new: int | None = None) -> dict[str, Any]:
    """Discover subtle ties and write detector code for top survivors."""
    if not _b("USE_PATTERN_CODE_EVOLVER", True):
        return {"enabled": False, "written": 0}
    max_new = max_new if max_new is not None else int(_f("PATTERN_CODE_MAX_NEW", 12))
    ties = discover_subtle_ties()
    written: list[str] = []
    skipped = 0
    for tie in ties:
        if len(written) >= max_new:
            break
        # Min score gate for codegen
        if tie.score < _f("PATTERN_CODE_MIN_SCORE", 0.35):
            skipped += 1
            continue
        p = write_detector_module(tie)
        if p is not None:
            written.append(str(p.name))
        else:
            skipped += 1
    # Force loader cache bust
    try:
        from analytics.generated_patterns import load_generated_detectors

        load_generated_detectors(force=True)
    except Exception:
        pass
    return {
        "enabled": True,
        "candidates": len(ties),
        "written": len(written),
        "files": written,
        "skipped": skipped,
        "ts": time.time(),
    }


def main() -> int:
    import json

    rep = discover_and_emit()
    print(json.dumps(rep, indent=2))
    return 0 if rep.get("written", 0) >= 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
