"""
Investing formulas package — re-exports key pure functions.
"""

from __future__ import annotations

from investing.formulas.analysis import (
    comps_implied_price,
    conglomerate_discount,
    enterprise_value,
    ev_ebitda,
    margin_of_safety,
    monte_carlo_mean_paths,
    pe_ratio,
    scenario_expected_value,
    sotp_equity,
    wacc,
)
from investing.formulas.derivatives import (
    black_scholes_call,
    black_scholes_put,
    calendar_spread_theta_edge,
    covered_call_max_return,
    futures_basis,
    greeks,
    implied_vol,
    iron_condor_max_profit,
    moneyness,
    norm_cdf,
    norm_pdf,
    protective_put_floor,
    put_call_parity_check,
    straddle_payoff,
)
from investing.formulas.growth import (
    compounder_score,
    garp_score,
    hypergrowth_score,
    peg_ratio,
    quality_growth_score,
)
from investing.formulas.income import (
    dividend_coverage,
    dividend_yield,
    gordon_growth_value,
    high_yield_score,
)
from investing.formulas.macro import (
    cycle_score,
    fisher_equation,
    inflation_hedge_tilt,
    real_rate,
)
from investing.formulas.quant import (
    capm_expected_return,
    fama_french_expected,
    factor_tilt_score,
    inverse_vol_weights,
    kelly_fraction,
    sharpe_ratio,
    sortino_ratio,
)
from investing.formulas.technical import (
    bollinger,
    breakout_score,
    macd,
    mean_reversion_score,
    rsi,
    technical_composite,
    trend_score,
    zscore,
)

__all__ = [
    "peg_ratio",
    "garp_score",
    "hypergrowth_score",
    "quality_growth_score",
    "compounder_score",
    "gordon_growth_value",
    "dividend_yield",
    "dividend_coverage",
    "high_yield_score",
    "capm_expected_return",
    "sharpe_ratio",
    "sortino_ratio",
    "kelly_fraction",
    "inverse_vol_weights",
    "fama_french_expected",
    "factor_tilt_score",
    "rsi",
    "macd",
    "bollinger",
    "zscore",
    "breakout_score",
    "trend_score",
    "mean_reversion_score",
    "technical_composite",
    "norm_cdf",
    "norm_pdf",
    "black_scholes_call",
    "black_scholes_put",
    "greeks",
    "implied_vol",
    "moneyness",
    "calendar_spread_theta_edge",
    "futures_basis",
    "covered_call_max_return",
    "protective_put_floor",
    "put_call_parity_check",
    "iron_condor_max_profit",
    "straddle_payoff",
    "wacc",
    "enterprise_value",
    "ev_ebitda",
    "pe_ratio",
    "comps_implied_price",
    "sotp_equity",
    "conglomerate_discount",
    "margin_of_safety",
    "scenario_expected_value",
    "monte_carlo_mean_paths",
    "real_rate",
    "fisher_equation",
    "cycle_score",
    "inflation_hedge_tilt",
]
