"""
Offline US equity symbol list when Nasdaq Trader is unreachable.
Liquid large/mid-cap + major ETFs — expand via data/universe_extra.txt
"""

SYMBOLS: list[str] = """
AAPL MSFT GOOGL GOOG AMZN NVDA META TSLA AVGO AMD INTC QCOM MU NFLX DIS CMCSA T
JPM BAC C WFC GS MS BLK SCHW AXP COF USB PNC TFC
XOM CVX COP SLB MPC VLO OXY EOG
JNJ UNH LLY MRK PFE ABBV TMO ABT DHR BMY AMGN GILD CVS CI ELV HUM
V MA PYPL XYZ FIS FISV AXP COF
WMT COST HD LOW TGT TJX NKE SBUX MCD CMG YUM
PG KO PEP GIS MDLZ CL KHC MO PM
CAT DE EMR ETN HON MMM GE BA LMT RTX NOC GD
UPS FDX CSX UNP NSC DE
NEE DUK SO D AEP EXC SRE
SPY QQQ IWM DIA VTI VOO IVV XLK XLF XLE XLV XLI XLY XLP XLU XLB XLRE
CRM ORCL IBM NOW INTU ADBE PANW CRWD SNOW NET ZS
CSCO AMAT LRCX KLAC SNPS CDNS MCHP ADI ON SWKS
PLTR COIN HOOD RBLX UBER LYFT DASH ABNB BKNG EXPE
BA LUV DAL UAL AAL JBLU
F GM STLA TSLA RIVN LCID
PFE BNTX MRNA GILD REGN VRTX BIIB
TMO DHR SYK BSX ISRG EW MDT ZBH
AMT PLD CCI EQIX PSA SPG WELL
CVS WBA CI CNC MOH HUM
OXY DVN FANG EOG PXD
""".split()

SYMBOLS = sorted(set(s.strip() for s in SYMBOLS if s.strip()))
