"""Auto-generated 50-category specification registry."""

from __future__ import annotations

from analytics.industries.categories._spec_types import CategorySpec

CATEGORY_SPECS: dict[str, CategorySpec] = {
    'biotechnology': CategorySpec(
        number=1,
        slug='biotechnology',
        display_name='Biotechnology',
        industry_id='biotech',
        sector_group='Healthcare & Biology',
        definition='Research-heavy firms developing molecular or cellular therapies, gene editing, and advanced cellular biology.',
        algo_key_metric='R&D Burn Rate vs. Cash Runway (Cash divided by annual cash burn must equal >24 months).',
        prediction_feature='Scrape ClinicalTrials.gov to feed an NLP model that parses Phase 2 and Phase 3 data release timelines.',
        correlation='Extremely low market correlation; moves almost entirely on binary scientific trial data and FDA approval announcements.',
        whole_group_movement='The entire group moves violently together during federal healthcare policy shifts or massive M&A (merger) waves.',
        metric_type='burn_runway',
        correlation_type='binary_event',
        group_keywords=(
            'biotechnology',
        'biotech',
        'genomic',
        'gene editing',
        'cell therapy',
        'immuno-oncology',
        'trial',
        'fda'
        ),
        bull_keywords=(
            'phase 3 success',
        'fda approval',
        'breakthrough therapy',
        'trial met primary',
        'orphan drug',
        'positive data'
        ),
        bear_keywords=(
            'clinical hold',
        'trial failure',
        'fda rejection',
        'safety concern',
        'offering',
        'dilution',
        'trial halted',
        'failed endpoint'
        ),
    ),
    'pharmaceuticals': CategorySpec(
        number=2,
        slug='pharmaceuticals',
        display_name='Pharmaceuticals',
        industry_id='big_pharma',
        sector_group='Healthcare & Biology',
        definition='Massive global corporations that manufacture, market, and distribute commercial medicines.',
        algo_key_metric='Patent Cliff Timeline (Years remaining on exclusive manufacturing rights for top 3 revenue-generating drugs).',
        prediction_feature='Tracker for total prescriptions filled (IQVIA data) crossed with regional government formulary updates.',
        correlation='Low-beta defensive play; steady consumer demand keeps earnings stable regardless of the broader economic cycle.',
        whole_group_movement='Moves tightly as a single unit when generic competition laws change or Medicare price negotiation news drops.',
        metric_type='patent_cliff',
        correlation_type='defensive_low_beta',
        group_keywords=(
            'drug manufacturers',
        'pharmaceutical',
        'big pharma',
        'prescription',
        'formulary',
        'patent',
        'beats estimates',
        'raises guidance'
        ),
        bull_keywords=(
            'beats estimates',
        'raises guidance',
        'patent win',
        'formulary inclusion',
        'blockbuster'
        ),
        bear_keywords=(
            'patent cliff',
        'generic entry',
        'medicare negotiation',
        'fda warning letter',
        'recall',
        'patent expiry',
        'price cap',
        'generic launch'
        ),
    ),
    'medical_devices_equipment': CategorySpec(
        number=3,
        slug='medical_devices_equipment',
        display_name='Medical Devices & Equipment',
        industry_id='medical_devices',
        sector_group='Healthcare & Biology',
        definition='Manufacturers of physical medical hardware ranging from surgical robots to pacemakers and artificial joints.',
        algo_key_metric='Gross Profit Margin (Must track >60% to support heavy hospital sales team commission structures).',
        prediction_feature='Hospital Capital Expenditure (CapEx) budgets, which are tracked via annual and quarterly hospital network earnings calls.',
        correlation='Moderate correlation to the market; behaves like high-tech manufacturing but with a healthcare safety net.',
        whole_group_movement='Co-moves strongly with the volume of elective surgeries happening globally (e.g., dropped together during pandemic lockdowns).',
        metric_type='gross_margin',
        correlation_type='moderate_cyclical',
        group_keywords=(
            'medical devices',
        'medical instruments',
        'surgical',
        'orthopedic',
        'pacemaker',
        'surgery',
        'hospital',
        'implant'
        ),
        bull_keywords=(
            'procedure volume',
        'hospital capex',
        'robotics adoption',
        'guidance raise'
        ),
        bear_keywords=(
            'hospital budget cut',
        'recall',
        'reimbursement cut',
        'elective delay',
        'class 1 recall',
        'warning letter'
        ),
    ),
    'life_sciences_tools_services': CategorySpec(
        number=4,
        slug='life_sciences_tools_services',
        display_name='Life Sciences Tools & Services',
        industry_id='life_sciences_tools',
        sector_group='Healthcare & Biology',
        definition='Providers of laboratory instruments, contract research services (CROs), and diagnostic reagents to scientists.',
        algo_key_metric='Backlog Growth Rate (The dollar value of contracted lab work signed but not yet executed).',
        prediction_feature='Global venture capital funding flows into biotech startups, as this funding directly dictates their instrument-buying power.',
        correlation="Growth-oriented asset; correlated with the broader technology sector's liquidity and risk appetite.",
        whole_group_movement='Moves as an absolute monolith based on global academic research grants and government science funding bills.',
        metric_type='backlog_growth',
        correlation_type='growth_high_beta',
        group_keywords=(
            'diagnostics',
        'life sciences',
        'research',
        'laboratory',
        'contract research',
        'cro',
        'instrument',
        'sequencing'
        ),
        bull_keywords=(
            'backlog growth',
        'biotech funding',
        'instrument demand',
        'academic grants'
        ),
        bear_keywords=(
            'biotech funding winter',
        'capex pause',
        'china weakness',
        'guidance cut',
        'funding drought'
        ),
    ),
    'healthcare_providers_services': CategorySpec(
        number=5,
        slug='healthcare_providers_services',
        display_name='Healthcare Providers & Services',
        industry_id='healthcare_providers',
        sector_group='Healthcare & Biology',
        definition='Owners of physical hospitals, dialysis centers, urgent care clinics, and outpatient medical facilities.',
        algo_key_metric='Bed Occupancy Rate & Payer Mix (The percentage of commercial insurance patients vs. lower-paying government Medicaid patients).',
        prediction_feature='Localized nursing wage data; rising labor costs are the number one killer of hospital profit margins.',
        correlation='Defensive; people require physical hospital beds and medical treatment regardless of stock market corrections.',
        whole_group_movement='Highly integrated group movement based on federal reimbursement rate updates from the Centers for Medicare & Medicaid Services.',
        metric_type='bed_occupancy',
        correlation_type='defensive_low_beta',
        group_keywords=(
            'health care plans',
        'hospitals',
        'healthcare providers',
        'managed care',
        'health services',
        'medicare',
        'medicaid',
        'mlr'
        ),
        bull_keywords=(
            'membership growth',
        'medical loss ratio beat',
        'rate increase',
        'utilization stable'
        ),
        bear_keywords=(
            'mlr miss',
        'medicare cut',
        'nurse wage inflation',
        'utilization spike',
        'reimbursement cut',
        'mlr pressure'
        ),
    ),
    'healthcare_technology': CategorySpec(
        number=6,
        slug='healthcare_technology',
        display_name='Healthcare Technology',
        industry_id='healthcare_technology',
        sector_group='Healthcare & Biology',
        definition='Providers of electronic health records (EHR), telehealth platforms, and AI-driven clinical workflow software.',
        algo_key_metric='LTV to CAC Ratio (Lifetime Value of a hospital contract divided by Customer Acquisition Cost).',
        prediction_feature='Federal enterprise software mandates and state-by-state legislative updates regarding out-of-state medical licensing for telehealth.',
        correlation='High-beta growth asset; moves hand-in-hand with mid-cap software-as-a-service (SaaS) technology stocks.',
        whole_group_movement='High internal group correlation; bad security breaches or privacy regulation hits one player and sinks them all.',
        metric_type='ltv_cac',
        correlation_type='growth_high_beta',
        group_keywords=(
            'health information',
        'healthcare technology',
        'health tech',
        'telehealth',
        'ehr',
        'hipaa',
        'contract win',
        'hospital go-live'
        ),
        bull_keywords=(
            'contract win',
        'hospital go-live',
        'saas growth',
        'ARR beat'
        ),
        bear_keywords=(
            'security breach',
        'privacy fine',
        'churn',
        'telehealth cut',
        'hipaa',
        'data breach',
        ' outage'
        ),
    ),
    'residential_reits': CategorySpec(
        number=7,
        slug='residential_reits',
        display_name='Residential REITs',
        industry_id='residential_reits',
        sector_group='Real Estate',
        definition='Real estate investment trusts that own, manage, and lease apartment buildings and single-family rental homes.',
        algo_key_metric='Net Effective Rent Growth (Face rent minus move-in concessions like "one month free").',
        prediction_feature='Regional employment rates mixed with local home affordability metrics (when homes get expensive, renting demand surges).',
        correlation='Highly sensitive to interest rates; moves inversely to rapid spikes in the US 10-Year Treasury yield.',
        whole_group_movement='Moves in near-perfect lockstep based on national multi-family housing starts and construction permit data releases.',
        metric_type='net_effective_rent',
        correlation_type='inverse_rates',
        group_keywords=(
            'residential reit',
        'reit—residential',
        'apartment reit',
        'multifamily',
        'rent',
        'apartment',
        'mortgage',
        'rent growth'
        ),
        bull_keywords=(
            'rent growth',
        'occupancy up',
        'concession down',
        'rate cut'
        ),
        bear_keywords=(
            'rent decline',
        'supply surge',
        'rate hike',
        'concession increase',
        'yield spike',
        'housing starts surge'
        ),
    ),
    'commercial_office_reits': CategorySpec(
        number=8,
        slug='commercial_office_reits',
        display_name='Commercial & Office REITs',
        industry_id='commercial_office_reits',
        sector_group='Real Estate',
        definition='Companies owning and managing skyscrapers, corporate business parks, and urban commercial office footprints.',
        algo_key_metric='Lease Weighted Average Unexpired Term (WAULT) (How many years are left on major corporate leases).',
        prediction_feature='Public transit ridership data mixed with commercial building keycard swipe data (e.g., Kastle Systems occupancy barometer).',
        correlation='Deeply cyclical; depends entirely on corporate financial health, white-collar employment levels, and return-to-office mandates.',
        whole_group_movement='Highly clustered downward or upward movements based on regional bank commercial real estate (CRE) lending standards.',
        metric_type='wault',
        correlation_type='cyclical_cre',
        group_keywords=(
            'office reit',
        'reit—office',
        'commercial office',
        'office',
        'wault',
        'occupancy',
        'return to office',
        'lease signed'
        ),
        bull_keywords=(
            'return to office',
        'lease signed',
        'occupancy stabil',
        'wault extended'
        ),
        bear_keywords=(
            'default',
        'vacancy rise',
        'cre stress',
        'remote work',
        'tenant bankruptcy',
        'cre loan'
        ),
    ),
    'retail_reits': CategorySpec(
        number=9,
        slug='retail_reits',
        display_name='Retail REITs',
        industry_id='retail_reits',
        sector_group='Real Estate',
        definition='Trusts owning regional shopping malls, open-air strip centers, and standalone single-tenant properties.',
        algo_key_metric="Tenant Occupancy Cost Ratio (The percentage of a retailer's sales that goes toward paying rent).",
        prediction_feature='Real-time foot traffic data derived from anonymized mobile phone geolocation data pings in shopping centers.',
        correlation='Consumer-dependent cyclical; correlated with broad retail sales data but buffered by fixed long-term lease structures.',
        whole_group_movement='Moves as a basket based on retail bankruptcy filings (e.g., if a major anchor tenant fails, all landlords suffer).',
        metric_type='tenant_occupancy_cost',
        correlation_type='consumer_cyclical',
        group_keywords=(
            'retail reit',
        'reit—retail',
        'shopping center',
        'mall reit',
        'mall',
        'foot traffic',
        'tenant',
        'tenant sales'
        ),
        bull_keywords=(
            'foot traffic',
        'tenant sales',
        're-leasing spread',
        'occupancy cost ratio ok'
        ),
        bear_keywords=(
            'anchor closure',
        'bankruptcy',
        'retail apocalypse',
        'rent cut',
        'chapter 11',
        'store closure wave'
        ),
    ),
    'industrial_logistics_reits': CategorySpec(
        number=10,
        slug='industrial_logistics_reits',
        display_name='Industrial & Logistics REITs',
        industry_id='industrial_logistics_reits',
        sector_group='Real Estate',
        definition='Owners of massive e-commerce fulfillment centers, distribution warehouses, and cold-storage logistics facilities.',
        algo_key_metric='Rent Reversion Rate (The percentage increase in rent achieved when old, cheaper leases expire).',
        prediction_feature='Global supply chain throughput metrics, container ship backlogs, and total e-commerce sales as a percentage of retail.',
        correlation='Growth-hybrid asset; strongly correlated with online shopping growth and physical manufacturing output volumes.',
        whole_group_movement='Extremely tight basket correlation; if Amazon scales back its warehouse footprint, the entire sector crashes together.',
        metric_type='rent_reversion',
        correlation_type='growth_hybrid',
        group_keywords=(
            'industrial reit',
        'reit—industrial',
        'warehouse',
        'logistics reit',
        'self storage',
        'fulfillment',
        'storage',
        'rent reversion'
        ),
        bull_keywords=(
            'rent reversion',
        'e-commerce demand',
        'supply chain',
        'development yield'
        ),
        bear_keywords=(
            'amazon slowdown',
        'oversupply',
        'cap rate expansion',
        'warehouse glut',
        'demand softening'
        ),
    ),
    'specialized_reits': CategorySpec(
        number=11,
        slug='specialized_reits',
        display_name='Specialized REITs',
        industry_id='specialized_reits',
        sector_group='Real Estate',
        definition='Infrastructure owners leasing out server rack space, cooling systems, and wireless telecom tower antennas.',
        algo_key_metric='Power Utilization Efficiency (PUE) & Churn (How efficiently they run power relative to server heat).',
        prediction_feature='Global cloud computing capital expenditure announcements from hyper-scalers like Microsoft, Amazon Web Services, and Google.',
        correlation='Highly correlated to the technology sector rather than traditional real estate cycles due to digital demand.',
        whole_group_movement='Moves uniformly based on global computing trends (e.g., the explosion of AI server demand boosted this entire group).',
        metric_type='pue_churn',
        correlation_type='tech_linked',
        group_keywords=(
            'data center',
        'cell tower',
        'reit—specialty',
        'reit—diversified',
        'healthcare reit',
        'tower reit',
        'tower',
        'ai server'
        ),
        bull_keywords=(
            'ai demand',
        'cloud capex',
        'tower lease',
        'power capacity'
        ),
        bear_keywords=(
            'rate spike',
        'hyperscaler pause',
        'interest expense',
        'capex cut',
        'yield jump'
        ),
    ),
    'semiconductors': CategorySpec(
        number=12,
        slug='semiconductors',
        display_name='Semiconductors',
        industry_id='semiconductors',
        sector_group='Technology',
        definition='Companies that design, fabricate, and market silicon computer chips, microprocessors, and memory units.',
        algo_key_metric='Book-to-Bill Ratio & Inventory Days (High inventory days mean chips are piling up unsold).',
        prediction_feature='Global foundry utilization rates (e.g., TSMC capacity) and global consumer electronics assembly schedules.',
        correlation='Hyper-cyclical, high-beta growth asset; the ultimate leading economic indicator for the entire global technology market.',
        whole_group_movement='Moves violently as an identical unit on trade war news, export restrictions, or hardware upgrades.',
        metric_type='book_to_bill',
        correlation_type='hyper_cyclical',
        group_keywords=(
            'semiconductor',
        'semiconductors',
        'chip',
        'gpu',
        'foundry',
        'wafer',
        'hbm',
        'ai demand'
        ),
        bull_keywords=(
            'ai demand',
        'book-to-bill',
        'supply tight',
        'export license',
        'data center'
        ),
        bear_keywords=(
            'inventory glut',
        'export ban',
        'cycle downturn',
        'book-to-bill below 1',
        'export restriction',
        'inventory days high'
        ),
    ),
    'semiconductor_equipment': CategorySpec(
        number=13,
        slug='semiconductor_equipment',
        display_name='Semiconductor Equipment',
        industry_id='semi_equipment',
        sector_group='Technology',
        definition='Manufacturers of the multi-million dollar lithography machines and tools used to print silicon wafers.',
        algo_key_metric='R&D Capital Investment Guidance from the major chip fabricators (Intel, TSMC, Samsung).',
        prediction_feature='Government subsidies and technology independence bills (like the CHIPS Act) that fund new physical factory builds.',
        correlation='Extreme volatility; long lead times mean their revenue cycles run in multi-year boom and bust waves.',
        whole_group_movement='The entire sub-sector trades on a single headline whenever global chipmakers pause or accelerate factory builds.',
        metric_type='fab_capex',
        correlation_type='extreme_cyclical',
        group_keywords=(
            'semiconductor equipment',
        'wafer fab',
        'lithography',
        'fab',
        'capex',
        'fab build',
        'capex raise',
        'chips act'
        ),
        bull_keywords=(
            'fab build',
        'capex raise',
        'chips act',
        'order backlog'
        ),
        bear_keywords=(
            'fab pause',
        'capex cut',
        'order cancel',
        'push out',
        'order push'
        ),
    ),
    'application_software': CategorySpec(
        number=14,
        slug='application_software',
        display_name='Application Software',
        industry_id='application_software',
        sector_group='Technology',
        definition='Developers of user-facing software programs for enterprise business operations, accounting, or design.',
        algo_key_metric='Net Revenue Retention (NRR) (Must be >110%, showing existing customers are spending more each year).',
        prediction_feature='Corporate IT budget surveys and white-collar employment growth data (more workers equals more software seats sold).',
        correlation='High-beta growth; relies heavily on low interest rates because its heavy cash flows occur far in the future.',
        whole_group_movement='Trades as an interconnected basket driven by broad valuation multiple expansions or contractions (P/S ratios).',
        metric_type='nrr',
        correlation_type='growth_high_beta',
        group_keywords=(
            'software—application',
        'software application',
        'saas',
        'enterprise software',
        'subscription',
        'seat',
        'nrr above 110',
        'billings beat'
        ),
        bull_keywords=(
            'nrr above 110',
        'billings beat',
        'seat expansion',
        'ai copilot'
        ),
        bear_keywords=(
            'nrr decline',
        'churn',
        'budget freeze',
        'multiple compression',
        'layoffs',
        'capex cut it'
        ),
    ),
    'systems_software': CategorySpec(
        number=15,
        slug='systems_software',
        display_name='Systems Software',
        industry_id='systems_software',
        sector_group='Technology',
        definition='Builders of core operating systems, cybersecurity architecture, database infrastructure, and cloud computing backends.',
        algo_key_metric='Annual Recurring Revenue (ARR) Growth and mission-critical retention metrics during economic downturns.',
        prediction_feature='Global cyberattack frequency indexes and corporate cloud migration speed tracked through cloud infrastructure data.',
        correlation='Resilient growth asset; less cyclical than application software because corporations cannot easily turn off their cybersecurity or databases.',
        whole_group_movement='Moves up dramatically as a unified block following major global ransomware attacks or cybersecurity failures.',
        metric_type='arr_growth',
        correlation_type='growth_high_beta',
        group_keywords=(
            'software—infra',
        'systems software',
        'cybersecurity',
        'security software',
        'database',
        'cyber',
        'cloud',
        'arr growth'
        ),
        bull_keywords=(
            'arr growth',
        'ransomware spike',
        'cloud migration',
        'platform stickiness'
        ),
        bear_keywords=(
            'breach at peer',
        'budget defer',
        'open source threat',
        'zero day',
        'outage'
        ),
    ),
    'technology_hardware_storage_peripherals': CategorySpec(
        number=16,
        slug='technology_hardware_storage_peripherals',
        display_name='Technology Hardware',
        industry_id='tech_hardware',
        sector_group='Technology',
        definition='Producers of consumer and enterprise electronics like smartphones, personal computers, laptops, and hard drives.',
        algo_key_metric='Gross Product Margin across hardware lines, balancing high assembly costs against retail consumer pricing.',
        prediction_feature='Foxconn assembly plant data, raw component pricing trends, and seasonal global consumer shipping volumes.',
        correlation='Deeply tied to the consumer discretionary spending cycle and global holiday retail performance timelines.',
        whole_group_movement='Strongly moves together based on consumer upgrade lifecycles (e.g., when the world replaces 4-year-old phones).Financial Industries',
        metric_type='hardware_margin',
        correlation_type='moderate_cyclical',
        group_keywords=(
            'computer hardware',
        'consumer electronics',
        'technology hardware',
        'storage device',
        'iphone',
        'pc',
        'smartphone',
        'foxconn'
        ),
        bull_keywords=(
            'upgrade cycle',
        'iphone demand',
        'pc recovery',
        'holiday strong'
        ),
        bear_keywords=(
            'inventory channel',
        'demand miss',
        'component cost',
        'china weak',
        'cut production',
        'demand warning'
        ),
    ),
    'diversified_banks': CategorySpec(
        number=17,
        slug='diversified_banks',
        display_name='Diversified Banks',
        industry_id='diversified_banks',
        sector_group='Financial',
        definition='Massive institutional banks combining consumer retail checking, corporate commercial lending, and Wall Street investment banking.',
        algo_key_metric='Net Interest Margin (NIM) (The difference between interest earned on loans and interest paid to depositors).',
        prediction_feature='Federal Reserve monetary policy direction and changes to the overnight Fed Funds interest rate.',
        correlation='Highly cyclical value play; thrives in environments with rising interest rates and stable, expanding GDP.',
        whole_group_movement='Moves in unified blocks based on central bank announcements or macro economic stress tests.',
        metric_type='nim',
        correlation_type='systemic_sensitive',
        group_keywords=(
            'banks—diversified',
        'diversified banks',
        'money center',
        'nim',
        'deposit',
        'loan',
        'nim expansion',
        'net interest income'
        ),
        bull_keywords=(
            'nim expansion',
        'net interest income',
        'stress test pass',
        'loan growth'
        ),
        bear_keywords=(
            'credit loss',
        'deposit flight',
        'regulatory fine',
        'inversion',
        'svb',
        'deposit outflow',
        'cecl spike'
        ),
    ),
    'regional_banks': CategorySpec(
        number=18,
        slug='regional_banks',
        display_name='Regional Banks',
        industry_id='regional_banks',
        sector_group='Financial',
        definition='Smaller commercial banks serving localized geographic footprints and focusing heavily on middle-market business loans.',
        algo_key_metric='Deposit Beta & Loan-to-Deposit Ratio (How fast they must raise deposit interest to stop customers from leaving).',
        prediction_feature='Local commercial real estate bankruptcy data and changes to Federal Deposit Insurance Corporation (FDIC) regulatory frameworks.',
        correlation='Highly sensitive to localized economic shocks and financial system liquidity pinches.',
        whole_group_movement='Prone to violent systemic cluster correlation; if one regional bank faces a deposit run, short-sellers attack the entire group.',
        metric_type='deposit_beta',
        correlation_type='systemic_sensitive',
        group_keywords=(
            'banks—regional',
        'regional banks',
        'cre',
        'deposit beta',
        'unrealized',
        'deposit stable',
        'cre manageable',
        'buyback'
        ),
        bull_keywords=(
            'deposit stable',
        'cre manageable',
        'buyback'
        ),
        bear_keywords=(
            'cre exposure',
        'unrealized losses',
        'deposit beta spike',
        'run risk',
        'regional bank',
        'deposit run',
        'cre default'
        ),
    ),
    'property_casualty_insurance': CategorySpec(
        number=19,
        slug='property_casualty_insurance',
        display_name='Property & Casualty Insurance',
        industry_id='property_casualty_insurance',
        sector_group='Financial',
        definition='Providers of insurance coverage for physical assets like homes, automobiles, commercial buildings, and shipping assets.',
        algo_key_metric='Combined Ratio (Losses plus expenses divided by earned premiums; must be under 100% to turn an underwriting profit).',
        prediction_feature='Extreme weather forecasting models, NOAA hurricane season data, and automotive repair inflation metrics.',
        correlation='Non-cyclical defensive asset; insurance is legally mandated, ensuring constant premium inflows during recessions.',
        whole_group_movement='Sinks uniformly during severe multi-state natural disasters; rallies together when state regulators approve broad insurance rate hikes.',
        metric_type='combined_ratio',
        correlation_type='defensive',
        group_keywords=(
            'insurance—property',
        'property & casualty',
        'pc insurance',
        'hurricane',
        'wildfire',
        'combined ratio',
        'combined ratio beat',
        'rate increase approved'
        ),
        bull_keywords=(
            'combined ratio beat',
        'rate increase approved',
        'pricing firm'
        ),
        bear_keywords=(
            'cat loss',
        'hurricane',
        'wildfire',
        'combined ratio miss',
        'cat event',
        'storm landfall'
        ),
    ),
    'life_health_insurance': CategorySpec(
        number=20,
        slug='life_health_insurance',
        display_name='Life & Health Insurance',
        industry_id='life_health_insurance',
        sector_group='Financial',
        definition='Underwriters of long-term life insurance policies, annuities, and comprehensive consumer healthcare coverage.',
        algo_key_metric='Actuarial Loss Ratio & Investment Income (The returns generated from investing client premiums in long-term bonds).',
        prediction_feature='Long-term actuarial mortality charts and macro shifts in structural long-term US bond yields.',
        correlation='Highly bond-correlated value play; performs best when long-term interest rates are high and predictable.',
        whole_group_movement='Moves in tandem based on national demographic aging steps and federal healthcare policy adjustments.',
        metric_type='actuarial_loss',
        correlation_type='bond_correlated',
        group_keywords=(
            'insurance—life',
        'life insurance',
        'insurance—diversified',
        'annuity',
        'mortality',
        'long bond',
        'investment income',
        'long bond yield'
        ),
        bull_keywords=(
            'investment income',
        'long bond yield',
        'mortality stable'
        ),
        bear_keywords=(
            'longevity',
        'rate cut',
        'alternative asset markdown',
        'rate cut cycle',
        'crediting rate'
        ),
    ),
    'financial_data_capital_markets': CategorySpec(
        number=21,
        slug='financial_data_capital_markets',
        display_name='Financial Data & Capital Markets',
        industry_id='financial_data_exchanges',
        sector_group='Financial',
        definition='Stock exchanges, investment management firms, index providers, and financial data terminal networks.',
        algo_key_metric='Assets Under Management (AUM) & Average Daily Trading Volume (ADV).',
        prediction_feature='Aggregate stock market performance and systemic volatility indexes like the VIX (higher volatility drives exchange fee revenues).',
        correlation='Directionally levered to the stock market; asset managers make more fees when stock prices are up.',
        whole_group_movement='Moves as a singular unit based on macro trading volumes and institutional wealth inflows into financial products.',
        metric_type='aum_adv',
        correlation_type='market_levered',
        group_keywords=(
            'financial data',
        'capital markets',
        'exchange',
        'asset management',
        'rating agency',
        'volume',
        'vix',
        'aum'
        ),
        bull_keywords=(
            'trading volume',
        'vix elevated',
        'aum growth',
        'data subscription'
        ),
        bear_keywords=(
            'volume drought',
        'fee pressure',
        'crypto winter',
        'trading slowdown',
        'fee cut'
        ),
    ),
    'consumer_finance': CategorySpec(
        number=22,
        slug='consumer_finance',
        display_name='Consumer Finance',
        industry_id='consumer_finance',
        sector_group='Financial',
        definition='Non-bank credit card issuers, personal loan originators, and point-of-sale buy-now-pay-later fintechs.',
        algo_key_metric='Net Charge-Off Rate (NCO) (The percentage of loaned money written off as uncollectible bad debt).',
        prediction_feature='Credit bureau delinquency tracking data and national consumer revolving credit extension metrics.',
        correlation='Cyclical and highly consumer-sensitive; performance suffers rapidly if employment rates tick downward.',
        whole_group_movement='Moves tightly with macro consumer spending indicators and changes to statutory credit card interest rate caps.Energy & Utility Industries',
        metric_type='net_charge_off',
        correlation_type='consumer_cyclical',
        group_keywords=(
            'credit services',
        'consumer finance',
        'credit card',
        'payment',
        'delinquency',
        'charge-off',
        'revolving',
        'spend growth'
        ),
        bull_keywords=(
            'spend growth',
        'delinquency stable',
        'loan growth'
        ),
        bear_keywords=(
            'charge-off rise',
        'delinquency spike',
        'rate cap',
        'recession fear',
        'delinquency',
        'charge-off',
        'bnpl stress'
        ),
    ),
    'integrated_oil_gas': CategorySpec(
        number=23,
        slug='integrated_oil_gas',
        display_name='Integrated Oil & Gas',
        industry_id='integrated_oil_gas',
        sector_group='Energy',
        definition='Global energy titans managing the entire lifecycle of oil from drilling (upstream) to refining and gas stations (downstream).',
        algo_key_metric='Free Cash Flow Breakeven Price (The exact price per barrel of oil required to cover dividends and operations).',
        prediction_feature='OPEC+ production quota agreements and global geopolitical tension risk premium tracking metrics.',
        correlation='Strong positive correlation to inflation; tracks global physical commodity markets rather than standard corporate metrics.',
        whole_group_movement='Moves in absolute lockstep with daily movements in West Texas Intermediate (WTI) and Brent crude futures.',
        metric_type='fcf_breakeven',
        correlation_type='commodity_inflation',
        group_keywords=(
            'oil & gas integrated',
        'integrated oil',
        'supermajor',
        'wti',
        'brent',
        'crude',
        'opec',
        'opec cut'
        ),
        bull_keywords=(
            'opec cut',
        'crude rally',
        'refining margin',
        'buyback'
        ),
        bear_keywords=(
            'demand destruction',
        'opec increase',
        'windfall tax',
        'demand concern',
        'inventory build'
        ),
    ),
    'oil_gas_exploration_production': CategorySpec(
        number=24,
        slug='oil_gas_exploration_production',
        display_name='Oil & Gas E&P',
        industry_id='oil_gas_ep',
        sector_group='Energy',
        definition='Pure-play companies focused solely on finding, drilling, and extracting raw crude oil and natural gas from the earth.',
        algo_key_metric='Drilling Rig Count & Production Decline Curve (How fast old wells dry up).',
        prediction_feature='Weekly EIA domestic oil inventory reports and regional drilling permit approvals.',
        correlation='Extremely high volatility asset; behaves like an amplified call option on the price of raw oil.',
        whole_group_movement='Highly correlated; a sudden collapse in energy demand crashes this entire industry segment immediately.',
        metric_type='rig_count',
        correlation_type='commodity_volatile',
        group_keywords=(
            'oil & gas e&p',
        'exploration',
        'upstream',
        'natural gas',
        'wti',
        'rig',
        'eia',
        'production beat'
        ),
        bull_keywords=(
            'production beat',
        'hedge gain',
        'rig count',
        'permit'
        ),
        bear_keywords=(
            'gas glut',
        'basis blowout',
        'decline curve',
        'eia build',
        'gas price collapse'
        ),
    ),
    'oil_gas_equipment_services': CategorySpec(
        number=25,
        slug='oil_gas_equipment_services',
        display_name='Oil & Gas Equipment & Services',
        industry_id='oil_gas_equipment',
        sector_group='Energy',
        definition='Providers of drilling rigs, seismic imaging technology, fracking fluid, and well-construction services to oil drillers.',
        algo_key_metric='Upstream Capital Expenditure Budgets set by E&P companies during annual planning phases.',
        prediction_feature='Long-term contractual utilization rates of offshore and onshore deep-well drilling equipment rigs.',
        correlation='Delayed cyclical play; their revenues lag behind crude oil price moves by about 3 to 6 months.',
        whole_group_movement='Moves as a tight sector group based on corporate drilling activity and global energy infrastructure demand.',
        metric_type='upstream_capex',
        correlation_type='delayed_cyclical',
        group_keywords=(
            'oil & gas equipment',
        'oilfield services',
        'drilling',
        'rig',
        'dayrate',
        'frac',
        'rig count',
        'international capex'
        ),
        bull_keywords=(
            'rig count',
        'international capex',
        'dayrate'
        ),
        bear_keywords=(
            'capex cut',
        'utilization fall',
        'frac spread narrow',
        'capex guide down',
        'stacked frac'
        ),
    ),
    'renewable_electricity_clean_energy': CategorySpec(
        number=26,
        slug='renewable_electricity_clean_energy',
        display_name='Renewable Electricity & Clean Energy',
        industry_id='renewable_energy',
        sector_group='Energy',
        definition='Operators and developers of utility-scale solar farms, wind infrastructure, and geothermal power generation assets.',
        algo_key_metric='Levelized Cost of Energy (LCOE) (The total lifetime cost of building and running a clean energy plant).',
        prediction_feature='Pricing of solar photovoltaic cells, wind turbine manufacturing input costs, and green energy tax credit legislation.',
        correlation='High interest rate sensitivity due to huge upfront construction costs; acts like a hybrid growth/utility asset.',
        whole_group_movement='Highly sensitive to federal environmental policy shifts; trades together based on clean energy subsidies.',
        metric_type='lcoe',
        correlation_type='rate_sensitive_growth',
        group_keywords=(
            'solar',
        'renewable',
        'clean energy',
        'wind energy',
        'wind',
        'lcoe',
        'ira',
        'ira credit'
        ),
        bull_keywords=(
            'ira credit',
        'solar demand',
        'lcoe decline',
        'policy support'
        ),
        bear_keywords=(
            'rate hike',
        'subsidy cut',
        'module glut',
        'interconnection delay',
        'subsidy rollback',
        'module oversupply'
        ),
    ),
    'electric_gas_utilities': CategorySpec(
        number=27,
        slug='electric_gas_utilities',
        display_name='Electric & Gas Utilities',
        industry_id='electric_gas_utilities',
        sector_group='Energy',
        definition='Regulated monopoly companies providing retail electricity, heating gas, and grid transmission infrastructure to cities.',
        algo_key_metric='Allowed Return on Equity (ROE) set by local state Public Utility Commissions.',
        prediction_feature='Short-term regional weather extremes (heatwaves/blizzards) and long-term trends in municipal electrical grid demand.',
        correlation='Classic negative-beta asset; stable, recession-proof business model that investors use strictly for safe dividend yield.',
        whole_group_movement='Trades uniformly like a corporate bond; drops when bond yields rise, jumps when bond yields crash.Consumer Goods & Retail Industries',
        metric_type='allowed_roe',
        correlation_type='defensive_utility',
        group_keywords=(
            'utilities—',
        'electric utilities',
        'gas utilities',
        'regulated utility',
        'utility',
        'grid',
        'allowed roe',
        'rate case win'
        ),
        bull_keywords=(
            'allowed roe',
        'rate case win',
        'load growth',
        'data center power'
        ),
        bear_keywords=(
            'rate case loss',
        'wildfire liability',
        'yield competition',
        'wildfire',
        'rate denial'
        ),
    ),
    'automobile_manufacturers': CategorySpec(
        number=28,
        slug='automobile_manufacturers',
        display_name='Automobile Manufacturers',
        industry_id='auto_manufacturers',
        sector_group='Consumer',
        definition='Designers and assembly line builders of mass-market consumer cars, trucks, and commercial electric vehicles.',
        algo_key_metric="Dealer Inventory Days' Supply (High inventory means cars are sitting unsold on dealer lots).",
        prediction_feature='Consumer auto loan interest rates and raw steel, aluminum, and battery component spot prices.',
        correlation='Highly cyclical discretionary play; consumers postpone buying new vehicles immediately if economic anxiety spikes.',
        whole_group_movement='Co-moves strongly based on global supply chain logistics and major union labor contract negotiations.',
        metric_type='dealer_inventory',
        correlation_type='consumer_cyclical',
        group_keywords=(
            'auto manufacturers',
        'automobile',
        'motor vehicles',
        'steel',
        'lithium',
        'battery',
        'auto loan',
        'delivery beat'
        ),
        bull_keywords=(
            'delivery beat',
        'ev demand',
        'inventory days low',
        'incentive cut'
        ),
        bear_keywords=(
            'strike',
        'inventory glut',
        'price war',
        'recall',
        'uaw strike',
        'price cut'
        ),
    ),
    'luxury_goods_apparel_accessories': CategorySpec(
        number=29,
        slug='luxury_goods_apparel_accessories',
        display_name='Luxury Goods',
        industry_id='luxury_goods',
        sector_group='Consumer',
        definition='High-end fashion houses, premium watchmakers, luxury jewelry manufacturers, and designer accessory brands.',
        algo_key_metric='Gross Pricing Power Margin (The ability to lift retail price tags without destroying unit demand volumes).',
        prediction_feature='Global high-net-worth individual wealth indexes, high-end art auction sales, and international tourist shopping flows.',
        correlation='Independent consumer asset; insulated from low-income recessions but highly vulnerable to global stock market wealth shocks.',
        whole_group_movement='Highly correlated group; moves on international currency exchange rates and travel retail spending numbers.',
        metric_type='pricing_power',
        correlation_type='wealth_correlated',
        group_keywords=(
            'luxury',
        'apparel—luxury',
        'designer',
        'premium fashion',
        'tourist',
        'yuan',
        'china reopen',
        'pricing power'
        ),
        bull_keywords=(
            'china reopen',
        'pricing power',
        'tourist spend',
        'hnw growth'
        ),
        bear_keywords=(
            'china slowdown',
        'asp reduction',
        'counterfeit',
        'wealth shock',
        'china weak',
        'discounting'
        ),
    ),
    'hotels_resorts_cruise_lines': CategorySpec(
        number=30,
        slug='hotels_resorts_cruise_lines',
        display_name='Hotels, Resorts & Cruise Lines',
        industry_id='hotels_resorts_cruise',
        sector_group='Consumer',
        definition='Operators of global hospitality properties, vacation destinations, entertainment booking systems, and cruise fleets.',
        algo_key_metric='Revenue Per Available Room (RevPAR) (Occupancy rate multiplied by Average Daily Room Rate).',
        prediction_feature='Commercial airline passenger volumes, corporate business travel travel budgets, and consumer leisure spending surveys.',
        correlation='High-beta discretionary cyclical; the first sector to experience spending cuts during economic contractions.',
        whole_group_movement='Moves completely in unison on global health, travel, safety, or fuel surcharge announcements.',
        metric_type='revpar',
        correlation_type='high_beta_discretionary',
        group_keywords=(
            'hotels',
        'resorts',
        'cruise',
        'lodging',
        'casino resort',
        'revpar',
        'occupancy',
        'jet fuel'
        ),
        bull_keywords=(
            'revpar up',
        'booking strong',
        'load factor',
        'business travel'
        ),
        bear_keywords=(
            'outbreak',
        'fuel surcharge',
        'geopolitical travel',
        'revpar miss',
        'travel warning',
        'port closure'
        ),
    ),
    'restaurants_food_services': CategorySpec(
        number=31,
        slug='restaurants_food_services',
        display_name='Restaurants & Food Services',
        industry_id='restaurants_food',
        sector_group='Consumer',
        definition='Fast-food chains, casual dining franchises, fine-dining operators, and institutional catering companies.',
        algo_key_metric='Same-Store Sales (SSS) Growth & Digital Order Mix (Tracks organic location growth vs. footprint expansion).',
        prediction_feature='Agricultural food commodity price indexes (beef, wheat, dairy) mixed with minimum wage adjustment schedules.',
        correlation='Moderate cyclical; fast-food stays resilient during downturns (trading down), while fine dining crashes.',
        whole_group_movement='Moves together based on broad consumer foot traffic trends and consumer food-away-from-home inflation data.',
        metric_type='same_store_sales',
        correlation_type='moderate_consumer',
        group_keywords=(
            'restaurants',
        'food service',
        'fast food',
        'casual dining',
        'beef',
        'wheat',
        'dairy',
        'coffee'
        ),
        bull_keywords=(
            'same store sales',
        'digital mix',
        'menu price',
        'traffic up'
        ),
        bear_keywords=(
            'food cost inflation',
        'wage inflation',
        'traffic down',
        'e.coli',
        'food safety',
        'minimum wage',
        'beef price'
        ),
    ),
    'hypermarkets_supercenters': CategorySpec(
        number=32,
        slug='hypermarkets_supercenters',
        display_name='Hypermarkets & Supercenters',
        industry_id='hypermarkets_discount',
        sector_group='Consumer',
        definition='Massive physical and e-commerce discount retail footprint operators selling groceries, apparel, and electronics.',
        algo_key_metric='Inventory Turnover Ratio (How many times a store sells out and replenishes its entire inventory per year).',
        prediction_feature='Consumer fuel pricing (lower gas prices leave shoppers with more cash to spend inside the supercenter).',
        correlation='Defensive consumer staple; counter-cyclical because middle-class consumers switch to discount stores during recessions.',
        whole_group_movement='Clustered performance movements based on quarterly corporate holiday spending data releases.',
        metric_type='inventory_turnover',
        correlation_type='defensive_consumer',
        group_keywords=(
            'discount stores',
        'department stores',
        'hypermarket',
        'supercenter',
        'gasoline',
        'consumer',
        'shrink',
        'traffic up'
        ),
        bull_keywords=(
            'traffic up',
        'market share gain',
        'inventory turn',
        'gas savings'
        ),
        bear_keywords=(
            'shrink',
        'theft',
        'margin pressure',
        'inventory glut',
        'guidance cut',
        'inventory markdown'
        ),
    ),
    'household_personal_products': CategorySpec(
        number=33,
        slug='household_personal_products',
        display_name='Household & Personal Products',
        industry_id='household_personal_products',
        sector_group='Consumer',
        definition='Manufacturers of everyday essentials like laundry detergent, diapers, soap, cosmetics, and paper towels.',
        algo_key_metric='Volume vs. Price Growth Mix (Are they growing revenues by selling more items or just raising prices?).',
        prediction_feature='Raw commodity chemical input prices and retail shelf space slotting fees.',
        correlation='Pure defensive staple; consumer consumption of toilet paper and soap remains completely flat across economic cycles.',
        whole_group_movement='Moves as a defensive safe-haven asset block during broad stock market corrections and panics.',
        metric_type='margin_stability',
        correlation_type='defensive_staple',
        group_keywords=(
            'household',
        'personal products',
        'soap',
        'cosmetics',
        'cleaning',
        'pulp',
        'chemical',
        'pricing power'
        ),
        bull_keywords=(
            'pricing power',
        'volume stable',
        'premium mix'
        ),
        bear_keywords=(
            'private label share',
        'input cost',
        'china weak',
        'volume decline',
        'promotional intensity'
        ),
    ),
    'food_products': CategorySpec(
        number=34,
        slug='food_products',
        display_name='Food Products',
        industry_id='packaged_foods',
        sector_group='Consumer',
        definition='Processors and packagers of brand-name consumer foods, snacks, cereals, and agricultural meat products.',
        algo_key_metric='Operating Profit Margin Stability against volatile raw agricultural crop pricing structures.',
        prediction_feature='Global grain, corn, and livestock futures markets crossed with major grocery store distribution agreements.',
        correlation='Defensive staple asset; insulated from economic downturns but highly sensitive to underlying food cost inflation.',
        whole_group_movement='Basket moves together based on consumer shifting habits between premium brand-name foods and cheaper private labels.Industrials, Materials & Transportation',
        metric_type='volume_price_mix',
        correlation_type='defensive_staple',
        group_keywords=(
            'packaged foods',
        'food products',
        'confectioners',
        'beverages—non-alcoholic',
        'corn',
        'wheat',
        'cocoa',
        'sugar'
        ),
        bull_keywords=(
            'pricing',
        'volume return',
        'snacking trend',
        'distribution gain'
        ),
        bear_keywords=(
            'glut',
        'grain cost',
        'trade down private label',
        'obesity drug',
        'corn spike',
        'glucagon',
        'weight loss headwind'
        ),
    ),
    'aerospace_defense': CategorySpec(
        number=35,
        slug='aerospace_defense',
        display_name='Aerospace & Defense',
        industry_id='aerospace_defense',
        sector_group='Industrials',
        definition='Manufacturers of commercial aircraft, military fighter jets, missile defense hardware, and space satellite technology.',
        algo_key_metric='Government Order Backlog (Multi-year contract pipelines funded by state defense budgets).',
        prediction_feature='National defense spending authorization bills, global geopolitical threat tracking, and commercial flight hour demands.',
        correlation='Non-cyclical sovereign asset; insulated from recessions due to guaranteed long-term government defense contracts.',
        whole_group_movement='Moves dynamically as a unit based on international defense spending policies and global escalations.',
        metric_type='defense_backlog',
        correlation_type='sovereign_defensive',
        group_keywords=(
            'aerospace',
        'defense',
        'aircraft',
        'military',
        'space',
        'backlog',
        'faa',
        'defense budget'
        ),
        bull_keywords=(
            'defense budget',
        'backlog record',
        'flight hours',
        'contract award'
        ),
        bear_keywords=(
            'program delay',
        'grounding',
        'budget cut',
        'strike',
        'quality issue'
        ),
    ),
    'air_freight_logistics': CategorySpec(
        number=36,
        slug='air_freight_logistics',
        display_name='Air Freight & Logistics',
        industry_id='air_freight_logistics',
        sector_group='Industrials',
        definition='Global overnight package delivery networks, cargo airlines, and commercial supply chain freight forwarders.',
        algo_key_metric='Yield Per Revenue Ton-Mile (The profitability of moving one ton of freight across one mile).',
        prediction_feature='E-commerce parcel volumes, manufacturing fulfillment orders, and jet fuel spot market futures.',
        correlation='Highly cyclical economic baseline; their internal parcel volumes serve as an early warning indicator for global GDP shifts.',
        whole_group_movement='High basket correlation; fuel costs and global customs trade tariffs impact all shipping networks simultaneously.',
        metric_type='yield_ton_mile',
        correlation_type='cyclical_indicator',
        group_keywords=(
            'integrated freight',
        'logistics',
        'courier',
        'air freight',
        'jet fuel',
        'diesel',
        'parcel',
        'freight'
        ),
        bull_keywords=(
            'parcel volume',
        'yield up',
        'e-commerce ship',
        'tender reject'
        ),
        bear_keywords=(
            'volume miss',
        'jet fuel',
        'trade tariff',
        'capacity add',
        'trade war',
        'fuel surcharge',
        'volume guide down'
        ),
    ),
    'railroads': CategorySpec(
        number=37,
        slug='railroads',
        display_name='Railroads',
        industry_id='railroads',
        sector_group='Industrials',
        definition='Operators of Class I freight rail infrastructure networks hauling bulk commodities and intermodal containers.',
        algo_key_metric='Operating Ratio (Operating expenses divided by revenue; a lower number proves higher structural efficiency).',
        prediction_feature='Weekly domestic rail carload data shipments covering grain, coal, automotive, and chemical commodities.',
        correlation='Core cyclical asset; deeply integrated into industrial production, agricultural crop harvests, and heavy manufacturing.',
        whole_group_movement='Moves seamlessly as a single block based on surface transportation laws and national fuel pricing setups.',
        metric_type='operating_ratio',
        correlation_type='industrial_cyclical',
        group_keywords=(
            'railroads',
        'rail freight',
        'class i rail',
        'coal',
        'grain',
        'intermodal',
        'carload',
        'carload up'
        ),
        bull_keywords=(
            'carload up',
        'operating ratio improve',
        'pricing',
        'intermodal'
        ),
        bear_keywords=(
            'coal decline',
        'strike',
        'weather',
        'regulatory',
        'derailment',
        'strike vote'
        ),
    ),
    'construction_machinery_heavy_trucks': CategorySpec(
        number=38,
        slug='construction_machinery_heavy_trucks',
        display_name='Construction Machinery',
        industry_id='construction_machinery',
        sector_group='Industrials',
        definition='Manufacturers of earthmovers, bulldozers, mining excavators, and class 8 highway freight semi-trucks.',
        algo_key_metric='Dealer De-stocking Velocity (How fast dealers clear physical machinery inventory lots).',
        prediction_feature='Federal infrastructure spending packages, global mining expansion plans, and national housing starts.',
        correlation='Highly cyclical industrial asset; relies heavily on corporate long-term capital expenditure commitment plans.',
        whole_group_movement='Moves cleanly as an absolute sector block based on global industrial manufacturing cycles.',
        metric_type='dealer_destocking',
        correlation_type='capex_cyclical',
        group_keywords=(
            'farm & construction',
        'construction machinery',
        'heavy machinery',
        'agricultural machinery',
        'steel',
        'copper',
        'infrastructure',
        'dealer inventory down'
        ),
        bull_keywords=(
            'dealer inventory down',
        'infrastructure bill',
        'mining capex',
        'backlog'
        ),
        bear_keywords=(
            'dealer destock',
        'china weak',
        'farm income down',
        'dealer inventory high',
        'china demand'
        ),
    ),
    'building_products_construction_materials': CategorySpec(
        number=39,
        slug='building_products_construction_materials',
        display_name='Building Products',
        industry_id='building_products',
        sector_group='Industrials',
        definition='Manufacturers of physical construction inputs like cement, drywall, lumber, insulation, and roofing materials.',
        algo_key_metric='Capacity Utilization Rate (The percentage of plant production potential actively running).',
        prediction_feature='National housing starts, building permits, and commercial construction architecture billings indexes.',
        correlation='Deeply cyclical asset; directly tied to fixed mortgage interest rates and real estate development cycles.',
        whole_group_movement='Moves in near-perfect internal correlation based on local construction commodity pricing data releases.',
        metric_type='capacity_utilization',
        correlation_type='housing_cyclical',
        group_keywords=(
            'building products',
        'building materials',
        'lumber',
        'cement',
        'roofing',
        'housing starts',
        'mortgage',
        'repair remodel'
        ),
        bull_keywords=(
            'housing starts',
        'repair remodel',
        'pricing',
        'capacity util'
        ),
        bear_keywords=(
            'mortgage rate spike',
        'housing slowdown',
        'input cost',
        'mortgage rate',
        'housing miss'
        ),
    ),
    'chemicals': CategorySpec(
        number=40,
        slug='chemicals',
        display_name='Chemicals',
        industry_id='chemicals',
        sector_group='Industrials',
        definition='Producers of plastic resins, agricultural fertilizers, industrial gases, and advanced specialty chemical coatings.',
        algo_key_metric='Spread over Natural Gas (Natural gas is both their primary manufacturing fuel and chemical feedstock).',
        prediction_feature='Global automotive manufacturing output data and international crop acreage planting projections.',
        correlation='Early-stage cyclical; chemical demand surges at the very beginning of an economic expansion cycle.',
        whole_group_movement='Moves as an integrated basket based on global energy input costs and basic industrial demand.',
        metric_type='gas_spread',
        correlation_type='cyclical_indicator',
        group_keywords=(
            'chemicals',
        'specialty chemicals',
        'agricultural inputs',
        'fertilizer',
        'natural gas',
        'ethylene',
        'potash',
        'spread widen'
        ),
        bull_keywords=(
            'spread widen',
        'volume up',
        'auto build',
        'crop acreage'
        ),
        bear_keywords=(
            'gas feedstock spike',
        'destock',
        'china demand',
        'destocking',
        'natural gas feed'
        ),
    ),
    'metals_mining': CategorySpec(
        number=41,
        slug='metals_mining',
        display_name='Metals & Mining',
        industry_id='metals_mining',
        sector_group='Industrials',
        definition='Corporations specializing in extraction, smelting, and distribution of industrial and precious metals.',
        algo_key_metric='Cash Cost Per Ounce/Ton Produced against current global spot market commodity prices.',
        prediction_feature='China Industrial Production data and London Metal Exchange (LME) physical inventory stockpile changes.',
        correlation='Highly volatile commodity play; tracks global infrastructural growth and serves as a major inflation hedge.',
        whole_group_movement='The entire sub-sector moves on daily metal price shifts, regardless of individual corporate performance.',
        metric_type='cash_cost',
        correlation_type='commodity_volatile',
        group_keywords=(
            'gold',
        'silver',
        'copper',
        'steel',
        'aluminum',
        'mining',
        'metals',
        'iron ore'
        ),
        bull_keywords=(
            'copper squeeze',
        'china stimulus',
        'gold safe haven',
        'lme draw'
        ),
        bear_keywords=(
            'china property',
        'dollar strong',
        'inventory build',
        'china weak',
        'inventory surge'
        ),
    ),
    'wireless_telecommunication_services': CategorySpec(
        number=42,
        slug='wireless_telecommunication_services',
        display_name='Wireless Telecom',
        industry_id='wireless_telecom',
        sector_group='Communication',
        definition='Operators of national mobile phone networks, fiber broadband pipelines, and data communication infrastructure.',
        algo_key_metric='Postpaid Churn Rate (The percentage of monthly contract customers who cancel their service).',
        prediction_feature='Consumer smartphone upgrade cycles and pricing wars across major network subscription plans.',
        correlation='Defensive utility-like asset; consumers prioritize keeping their mobile phone and internet connections over almost all other bills.',
        whole_group_movement='Moves as a high-dividend yielding basket; highly sensitive to aggregate bond market yield structures.',
        metric_type='postpaid_churn',
        correlation_type='defensive_yield',
        group_keywords=(
            'telecom services',
        'wireless',
        'communication services',
        'spectrum',
        'churn',
        'arpu',
        'churn low',
        'arpu up'
        ),
        bull_keywords=(
            'churn low',
        'arpu up',
        'fiber build',
        'dividend safe'
        ),
        bear_keywords=(
            'price war',
        'churn spike',
        'capex overhang',
        'yield competition',
        'price cut',
        'churn warning'
        ),
    ),
    'interactive_media_services': CategorySpec(
        number=43,
        slug='interactive_media_services',
        display_name='Interactive Media & Services',
        industry_id='interactive_media',
        sector_group='Communication',
        definition='Digital ad-monetized search engines, social networks, video platforms, and online communication software.',
        algo_key_metric='Average Revenue Per User (ARPU) & Daily Active Users (DAU).',
        prediction_feature='Corporate digital ad-spend budget trackers, pixel tracking efficacy, and data privacy regulatory changes.',
        correlation='High-beta secular growth asset; dependent on consumer attention market capture and corporate marketing budgets.',
        whole_group_movement='High cluster correlation; an ad-market downturn or antitrust regulation announcement hits the entire basket at once.',
        metric_type='arpu_dau',
        correlation_type='growth_high_beta',
        group_keywords=(
            'internet content',
        'interactive media',
        'search',
        'social media',
        'online advertising',
        'advertising',
        'pixel',
        'dau'
        ),
        bull_keywords=(
            'ad spend',
        'dau growth',
        'reels monetization',
        'ai search'
        ),
        bear_keywords=(
            'ad recession',
        'att opt out',
        'antitrust',
        'tiktok competition',
        'ad slowdown',
        'privacy'
        ),
    ),
    'entertainment_streaming': CategorySpec(
        number=44,
        slug='entertainment_streaming',
        display_name='Entertainment & Streaming',
        industry_id='entertainment_streaming',
        sector_group='Communication',
        definition='Hollywood movie studios, television networks, streaming platform apps, and music distribution labels.',
        algo_key_metric='Content Spend ROI (The subscriber addition volume achieved relative to multi-billion dollar content production budgets).',
        prediction_feature='App store download velocity data and subscriber cancel-and-renew cycles (churn management).',
        correlation='Consumer discretionary asset; relies heavily on continuous content hits to sustain recurring revenue pipelines.',
        whole_group_movement='Moves in tandem based on intellectual property copyright law changes and creative production labor unions.',
        metric_type='content_roi',
        correlation_type='discretionary_media',
        group_keywords=(
            'entertainment',
        'broadcasting',
        'streaming',
        'media—',
        'movie',
        'box office',
        'subscriber',
        'subscriber add'
        ),
        bull_keywords=(
            'subscriber add',
        'content hit',
        'pricing tier',
        'box office'
        ),
        bear_keywords=(
            'churn',
        'content flop',
        'strike',
        'cord cutting margin',
        'writers strike',
        'sub miss',
        'content write down'
        ),
    ),
    'environmental_waste_management': CategorySpec(
        number=45,
        slug='environmental_waste_management',
        display_name='Environmental & Waste Management',
        industry_id='environmental_waste',
        sector_group='Specialized',
        definition='Industrial providers of municipal trash collection, landfill management, hazardous waste disposal, and recycling loops.',
        algo_key_metric='Price Escalator Clauses (The legal ability to pass diesel fuel inflation costs directly onto cities).',
        prediction_feature='New real estate housing development densities and municipal municipal waste tonnage disposal trends.',
        correlation='Highly defensive industrial play; physical trash production is an unavoidable constant of human population density.',
        whole_group_movement='Trades as a highly clustered, low-volatility basket prized for steady, long-term infrastructure cash flows.',
        metric_type='price_escalator',
        correlation_type='defensive_industrial',
        group_keywords=(
            'waste management',
        'environmental',
        'pollution',
        'recycling',
        'diesel',
        'landfill',
        'tonnage',
        'pricing escalator'
        ),
        bull_keywords=(
            'pricing escalator',
        'volume tonnage',
        'municipal contract'
        ),
        bear_keywords=(
            'diesel cost',
        'volume soft',
        'recycling price',
        'fuel surcharge lag',
        'volume miss'
        ),
    ),
    'apparel_retail': CategorySpec(
        number=46,
        slug='apparel_retail',
        display_name='Apparel Retail',
        industry_id='apparel_retail',
        sector_group='Specialized',
        definition='Brick-and-mortar and e-commerce fast-fashion clothing chains, boutique shoe outlets, and sports apparel lines.',
        algo_key_metric='Gross Margin ROI (GMROII) (Inventory inventory dollar productivity tracking profitability against storage space costs).',
        prediction_feature='Seasonal weather anomalies (e.g., warm winters ruin high-margin winter coat sales cycles).',
        correlation='Highly volatile discretionary asset; highly vulnerable to consumer shifting fashion tastes and supply chain delays.',
        whole_group_movement='Moves as a single unit on mall foot traffic metrics and credit card spending datasets.',
        metric_type='gmroii',
        correlation_type='volatile_discretionary',
        group_keywords=(
            'apparel retail',
        'specialty retail',
        'footwear',
        'clothing store',
        'cotton',
        'freight',
        'apparel',
        'comp beat'
        ),
        bull_keywords=(
            'comp beat',
        'inventory clean',
        'brand heat',
        'china reopen'
        ),
        bear_keywords=(
            'warm winter',
        'inventory glut',
        'promotional',
        'supply delay',
        'inventory up',
        'weather miss'
        ),
    ),
    'marine_transportation': CategorySpec(
        number=47,
        slug='marine_transportation',
        display_name='Marine Transportation',
        industry_id='marine_shipping',
        sector_group='Specialized',
        definition='Global owners and operators of oceanic container ships, dry bulk carriers, and crude oil tankers.',
        algo_key_metric='Spot Charter Rate (The daily market price to hire a cargo ship pipeline).',
        prediction_feature='The Baltic Dry Index, global canal congestion metrics, and international trade tariff announcements.',
        correlation='Extreme volatility cyclical play; completely decoupled from standard equity markets, tracking maritime freight capacity.',
        whole_group_movement='The entire sub-sector moves uniformly based on maritime shipping rate spikes or physical canal bottlenecks.',
        metric_type='spot_charter',
        correlation_type='commodity_decoupled',
        group_keywords=(
            'marine shipping',
        'shipping',
        'tanker',
        'bulk carrier',
        'container ship',
        'baltic',
        'freight rate',
        'container'
        ),
        bull_keywords=(
            'baltic dry up',
        'spot rate spike',
        'canal congestion',
        'tanker tight'
        ),
        bear_keywords=(
            'rate collapse',
        'new supply',
        'trade slowdown',
        'rate crash',
        'demurrage'
        ),
    ),
    'independent_power_producers_energy_traders': CategorySpec(
        number=48,
        slug='independent_power_producers_energy_traders',
        display_name='Independent Power Producers',
        industry_id='independent_power_producers',
        sector_group='Specialized',
        definition='Non-utility wholesale electricity operators generating power to trade on open deregulated competitive wholesale grids.',
        algo_key_metric='Spark Spread / Dark Spread (The margin between wholesale power price and the cost of gas/coal fuel needed to make it).',
        prediction_feature='Short-term regional grid reserve capacity margins and daily physical power grid transmission constraints.',
        correlation='High-volatility commodity asset; acts like a trading desk levered to intra-day energy market price arbitrage.',
        whole_group_movement='Moves in unified blocks based on systemic electricity market price deregulation changes.',
        metric_type='spark_spread',
        correlation_type='energy_trading',
        group_keywords=(
            'independent power',
        'power producers',
        'merchant power',
        'ipp',
        'power price',
        'spark spread',
        'heat',
        'spark spread widen'
        ),
        bull_keywords=(
            'spark spread widen',
        'heat wave',
        'capacity tight',
        'data center power'
        ),
        bear_keywords=(
            'power price collapse',
        'renewable cannibalization',
        'regulatory',
        'power price negative',
        'regulatory cap'
        ),
    ),
    'commercial_services_supplies': CategorySpec(
        number=49,
        slug='commercial_services_supplies',
        display_name='Commercial Services & Supplies',
        industry_id='commercial_services',
        sector_group='Specialized',
        definition='Providers of B2B corporate office supplies, uniform cleaning services, and physical facilities security guard systems.',
        algo_key_metric='Corporate Contract Retention Rate across long-term multi-facility commercial service agreements.',
        prediction_feature='National white-collar employment levels and corporate operational expense budget expansions or cuts.',
        correlation='Steady industrial value asset; tracks corporate office density and real estate facility occupancy cycles.',
        whole_group_movement='Moves closely with commercial real estate employment data and corporate operational budget trends.',
        metric_type='contract_retention',
        correlation_type='office_cyclical',
        group_keywords=(
            'specialty business services',
        'staffing',
        'security guard',
        'uniform',
        'facility',
        'employment',
        'office',
        'white collar hiring'
        ),
        bull_keywords=(
            'white collar hiring',
        'contract renewal',
        'cross sell'
        ),
        bear_keywords=(
            'hiring freeze',
        'office vacancy',
        'wage inflation',
        'layoffs',
        'office empty'
        ),
    ),
    'distributors': CategorySpec(
        number=50,
        slug='distributors',
        display_name='Distributors',
        industry_id='distributors',
        sector_group='Specialized',
        definition='Intermediary wholesale links buying massive volume goods from manufacturers to distribute to local retail networks.',
        algo_key_metric='Working Capital Cycle Efficiency (The cash conversion speed balancing inventory inventory outlays against client collections).',
        prediction_feature='General supplier delivery times and product inventory availability pipelines across nationwide manufacturing hubs.',
        correlation='Cyclical volume-based play; profits depend on shipping logistics efficiency rather than single product innovations.',
        whole_group_movement='Moves as a single block based on broad domestic supply chain throughput metrics.',
        metric_type='working_capital',
        correlation_type='volume_cyclical',
        group_keywords=(
            'distribution',
        'wholesale',
        'industrial distribution',
        'distributor',
        'freight',
        'inventory',
        'working capital',
        'volume growth'
        ),
        bull_keywords=(
            'volume growth',
        'pricing pass',
        'inventory turn',
        'digital share'
        ),
        bear_keywords=(
            'destock',
        'freight cost',
        'customer inventory cut',
        'customer destock',
        'margin squeeze'
        ),
    ),
}

INDUSTRY_ID_TO_SPEC: dict[str, CategorySpec] = {
    'biotech': CATEGORY_SPECS['biotechnology'],
    'big_pharma': CATEGORY_SPECS['pharmaceuticals'],
    'medical_devices': CATEGORY_SPECS['medical_devices_equipment'],
    'life_sciences_tools': CATEGORY_SPECS['life_sciences_tools_services'],
    'healthcare_providers': CATEGORY_SPECS['healthcare_providers_services'],
    'healthcare_technology': CATEGORY_SPECS['healthcare_technology'],
    'residential_reits': CATEGORY_SPECS['residential_reits'],
    'commercial_office_reits': CATEGORY_SPECS['commercial_office_reits'],
    'retail_reits': CATEGORY_SPECS['retail_reits'],
    'industrial_logistics_reits': CATEGORY_SPECS['industrial_logistics_reits'],
    'specialized_reits': CATEGORY_SPECS['specialized_reits'],
    'semiconductors': CATEGORY_SPECS['semiconductors'],
    'semi_equipment': CATEGORY_SPECS['semiconductor_equipment'],
    'application_software': CATEGORY_SPECS['application_software'],
    'systems_software': CATEGORY_SPECS['systems_software'],
    'tech_hardware': CATEGORY_SPECS['technology_hardware_storage_peripherals'],
    'diversified_banks': CATEGORY_SPECS['diversified_banks'],
    'regional_banks': CATEGORY_SPECS['regional_banks'],
    'property_casualty_insurance': CATEGORY_SPECS['property_casualty_insurance'],
    'life_health_insurance': CATEGORY_SPECS['life_health_insurance'],
    'financial_data_exchanges': CATEGORY_SPECS['financial_data_capital_markets'],
    'consumer_finance': CATEGORY_SPECS['consumer_finance'],
    'integrated_oil_gas': CATEGORY_SPECS['integrated_oil_gas'],
    'oil_gas_ep': CATEGORY_SPECS['oil_gas_exploration_production'],
    'oil_gas_equipment': CATEGORY_SPECS['oil_gas_equipment_services'],
    'renewable_energy': CATEGORY_SPECS['renewable_electricity_clean_energy'],
    'electric_gas_utilities': CATEGORY_SPECS['electric_gas_utilities'],
    'auto_manufacturers': CATEGORY_SPECS['automobile_manufacturers'],
    'luxury_goods': CATEGORY_SPECS['luxury_goods_apparel_accessories'],
    'hotels_resorts_cruise': CATEGORY_SPECS['hotels_resorts_cruise_lines'],
    'restaurants_food': CATEGORY_SPECS['restaurants_food_services'],
    'hypermarkets_discount': CATEGORY_SPECS['hypermarkets_supercenters'],
    'household_personal_products': CATEGORY_SPECS['household_personal_products'],
    'packaged_foods': CATEGORY_SPECS['food_products'],
    'aerospace_defense': CATEGORY_SPECS['aerospace_defense'],
    'air_freight_logistics': CATEGORY_SPECS['air_freight_logistics'],
    'railroads': CATEGORY_SPECS['railroads'],
    'construction_machinery': CATEGORY_SPECS['construction_machinery_heavy_trucks'],
    'building_products': CATEGORY_SPECS['building_products_construction_materials'],
    'chemicals': CATEGORY_SPECS['chemicals'],
    'metals_mining': CATEGORY_SPECS['metals_mining'],
    'wireless_telecom': CATEGORY_SPECS['wireless_telecommunication_services'],
    'interactive_media': CATEGORY_SPECS['interactive_media_services'],
    'entertainment_streaming': CATEGORY_SPECS['entertainment_streaming'],
    'environmental_waste': CATEGORY_SPECS['environmental_waste_management'],
    'apparel_retail': CATEGORY_SPECS['apparel_retail'],
    'marine_shipping': CATEGORY_SPECS['marine_transportation'],
    'independent_power_producers': CATEGORY_SPECS['independent_power_producers_energy_traders'],
    'commercial_services': CATEGORY_SPECS['commercial_services_supplies'],
    'distributors': CATEGORY_SPECS['distributors'],
}


def get_spec(slug: str) -> CategorySpec | None:
    return CATEGORY_SPECS.get(str(slug or "").strip().lower())


def get_spec_by_industry_id(industry_id: str) -> CategorySpec | None:
    return INDUSTRY_ID_TO_SPEC.get(str(industry_id or "").strip().lower())
