"""Extended sector leaves — full book taxonomy under each sector parent."""

from __future__ import annotations

from investing.catalog import Topic, _t

# Extra leaves missing from the coarse SECTOR_TOPICS parents.
SECTOR_LEAF_TOPICS: tuple[Topic, ...] = (
    # Communication
    _t("internet_services", "Internet Services", "sector", parent="Communication", summary="Internet platforms and services delivering content, commerce, and cloud connectivity at scale."),
    _t("social_media", "Social Media", "sector", parent="Communication", summary="Social networks monetize attention via advertising and subscriptions amid engagement and regulation risk."),
    _t("telecommunications", "Telecommunications", "sector", parent="Communication", summary="Wireless and wireline carriers provide essential connectivity with capital-heavy networks and regulatory overlays."),
    _t("streaming", "Streaming", "sector", parent="Communication", summary="Streaming services compete for subscribers with content libraries and global distribution."),
    _t("gaming", "Gaming", "sector", parent="Communication", summary="Video game publishers and platforms monetize playtime through titles, DLC, and live services."),
    _t("digital_advertising", "Digital Advertising", "sector", parent="Communication", summary="Ad-tech and digital media capture marketing spend shifting from traditional channels."),
    # Healthcare
    _t("pharmaceuticals", "Pharmaceuticals", "sector", parent="Healthcare", summary="Large drug manufacturers develop and commercialize patented and generic medicines worldwide."),
    _t("biotechnology", "Biotechnology", "sector", parent="Healthcare", summary="Biotech firms develop novel therapies with binary clinical and regulatory outcomes."),
    _t("medical_devices", "Medical Devices", "sector", parent="Healthcare", summary="Device makers sell implants, diagnostics tools, and equipment into hospitals and clinics."),
    _t("diagnostics", "Diagnostics", "sector", parent="Healthcare", summary="Diagnostics companies enable disease detection through labs, kits, and imaging modalities."),
    _t("healthcare_services", "Healthcare Services", "sector", parent="Healthcare", summary="Service providers deliver care coordination, outpatient services, and specialty treatment networks."),
    _t("hospitals", "Hospitals", "sector", parent="Healthcare", summary="Hospital operators earn from inpatient and outpatient care with labor and reimbursement intensity."),
    _t("health_insurance", "Health Insurance", "sector", parent="Healthcare", summary="Insurers underwrite medical risk and manage networks between patients, employers, and providers."),
    _t("gene_editing", "Gene Editing", "sector", parent="Healthcare", summary="Gene-editing platforms pursue durable cures via CRISPR and related molecular tools."),
    _t("drug_manufacturing", "Drug Manufacturing", "sector", parent="Healthcare", summary="Contract and specialty manufacturers produce APIs and finished doses for branded and generic firms."),
    # Financials
    _t("banks", "Banks", "sector", parent="Financials", summary="Commercial banks take deposits and lend, earning net interest margin under capital regulation."),
    _t("investment_banks", "Investment Banks", "sector", parent="Financials", summary="Investment banks advise on M&A and underwrite securities amid deal-cycle volatility."),
    _t("asset_management", "Asset Management", "sector", parent="Financials", summary="Asset managers earn fees on AUM across active and passive strategies."),
    _t("insurance", "Insurance", "sector", parent="Financials", summary="Insurers collect premiums and invest float while managing underwriting and catastrophe risk."),
    _t("fintech", "FinTech", "sector", parent="Financials", summary="FinTech disrupts payments, lending, and brokerage with software-led distribution."),
    _t("credit_cards", "Credit Cards", "sector", parent="Financials", summary="Card networks and issuers monetize transactions and revolving credit balances."),
    _t("exchanges", "Exchanges", "sector", parent="Financials", summary="Exchanges and market infrastructure firms provide listing, matching, and data services."),
    _t("mortgage_lenders", "Mortgage Lenders", "sector", parent="Financials", summary="Mortgage originators and servicers are highly sensitive to rates and housing volumes."),
    _t("sector_private_equity", "Private Equity (Sector)", "sector", parent="Financials", summary="Listed PE sponsors and BDCs offer public access to buyout and credit strategies."),
    _t("sector_venture_capital", "Venture Capital (Sector)", "sector", parent="Financials", summary="Public VC-related vehicles and growth equity platforms capture startup ecosystem exposure."),
    # Consumer Discretionary
    _t("retail", "Retail", "sector", parent="Consumer Discretionary", summary="Brick-and-mortar and omnichannel retailers sell discretionary goods with inventory and traffic risk."),
    _t("ecommerce", "E-commerce", "sector", parent="Consumer Discretionary", summary="Online marketplaces and specialty e-tailers compete on selection, logistics, and price."),
    _t("luxury_goods", "Luxury Goods", "sector", parent="Consumer Discretionary", summary="Luxury brands monetize exclusivity and aspirational demand across cycles and geographies."),
    _t("apparel", "Apparel", "sector", parent="Consumer Discretionary", summary="Apparel makers and retailers face fashion cycles, sourcing costs, and promotional intensity."),
    _t("restaurants", "Restaurants", "sector", parent="Consumer Discretionary", summary="Restaurant chains leverage brand and unit economics with labor and commodity sensitivity."),
    _t("hotels", "Hotels", "sector", parent="Consumer Discretionary", summary="Hotel operators and franchisors earn from occupancy and RevPAR tied to travel demand."),
    _t("travel", "Travel", "sector", parent="Consumer Discretionary", summary="Online travel and leisure platforms connect consumers to trips and experiences."),
    _t("cruise_lines", "Cruise Lines", "sector", parent="Consumer Discretionary", summary="Cruise operators run floating resorts with high operating leverage to bookings."),
    _t("airlines", "Airlines", "sector", parent="Consumer Discretionary", summary="Airlines move passengers with fuel, labor, and capacity discipline as key variables."),
    _t("automobiles", "Automobiles", "sector", parent="Consumer Discretionary", summary="Auto OEMs produce vehicles with long product cycles and dealer networks."),
    _t("ev_manufacturers", "EV Manufacturers", "sector", parent="Consumer Discretionary", summary="EV makers compete on range, software, and manufacturing scale in the electrification shift."),
    _t("auto_parts", "Auto Parts", "sector", parent="Consumer Discretionary", summary="Parts suppliers feed OEMs and aftermarket channels with cyclical auto production."),
    # Staples
    _t("food_manufacturers", "Food Manufacturers", "sector", parent="Consumer Staples", summary="Packaged food companies deliver steady demand with brand and commodity cost management."),
    _t("beverage_companies", "Beverage Companies", "sector", parent="Consumer Staples", summary="Beverage firms sell soft drinks, alcohol, and hydration brands with global distribution."),
    _t("household_products", "Household Products", "sector", parent="Consumer Staples", summary="Household product makers sell cleaning and home goods with defensive cash flows."),
    _t("personal_care", "Personal Care", "sector", parent="Consumer Staples", summary="Personal care brands sell hygiene and beauty products with brand loyalty and pricing power."),
    _t("tobacco", "Tobacco", "sector", parent="Consumer Staples", summary="Tobacco companies generate high free cash flow amid regulatory and volume headwinds."),
    # Industrials
    _t("aerospace", "Aerospace", "sector", parent="Industrials", summary="Aerospace suppliers and OEMs build aircraft systems with long order backlogs."),
    _t("defense", "Defense", "sector", parent="Industrials", summary="Defense contractors supply weapons and platforms funded by multi-year government budgets."),
    _t("construction", "Construction", "sector", parent="Industrials", summary="Construction firms build infrastructure and buildings tied to public and private capex."),
    _t("engineering", "Engineering", "sector", parent="Industrials", summary="Engineering and EPCM firms design complex industrial and infrastructure projects."),
    _t("machinery", "Machinery", "sector", parent="Industrials", summary="Machinery makers sell equipment into construction, agriculture, and manufacturing cycles."),
    _t("logistics", "Logistics", "sector", parent="Industrials", summary="Logistics providers move and warehouse goods as trade and e-commerce volumes fluctuate."),
    _t("railroads", "Railroads", "sector", parent="Industrials", summary="Railroads haul freight efficiently over long distances with oligopolistic networks."),
    _t("shipping", "Shipping", "sector", parent="Industrials", summary="Ocean shipping moves bulk and container cargo with freight-rate cyclicality."),
    _t("trucking", "Trucking", "sector", parent="Industrials", summary="Trucking firms provide flexible freight with fuel, driver, and spot-rate sensitivity."),
    _t("packaging", "Packaging", "sector", parent="Industrials", summary="Packaging producers supply containers to consumer and industrial end markets."),
    # Energy
    _t("oil_exploration", "Oil Exploration", "sector", parent="Energy", summary="E&P companies explore and produce oil with oil-price and reserve risk."),
    _t("oil_refining", "Oil Refining", "sector", parent="Energy", summary="Refiners crack crude into fuels earning crack spreads through cycles."),
    _t("natural_gas", "Natural Gas", "sector", parent="Energy", summary="Natural gas producers and midstream operators supply power and heating markets."),
    _t("lng", "LNG", "sector", parent="Energy", summary="LNG exporters liquefy and ship natural gas into global trade flows."),
    _t("pipelines", "Pipelines", "sector", parent="Energy", summary="Pipeline midstream assets move hydrocarbons under fee and volume contracts."),
    _t("solar", "Solar", "sector", parent="Energy", summary="Solar developers and manufacturers ride renewable adoption and policy support."),
    _t("wind", "Wind", "sector", parent="Energy", summary="Wind power OEMs and operators build renewable generation capacity."),
    _t("nuclear", "Nuclear", "sector", parent="Energy", summary="Nuclear utilities and fuel cycle firms provide baseload low-carbon power."),
    _t("hydrogen", "Hydrogen", "sector", parent="Energy", summary="Hydrogen technology spans production, transport, and industrial decarbonization use cases."),
    _t("battery_storage", "Battery Storage", "sector", parent="Energy", summary="Battery and storage companies enable renewable firming and EV energy density."),
    # Materials
    _t("chemicals", "Chemicals", "sector", parent="Materials", summary="Chemical firms produce specialty and commodity molecules for industry."),
    _t("steel", "Steel", "sector", parent="Materials", summary="Steel producers serve construction and manufacturing with highly cyclical pricing."),
    _t("aluminum", "Aluminum", "sector", parent="Materials", summary="Aluminum smelters and fabricators supply lightweight metal for transport and packaging."),
    _t("copper", "Copper", "sector", parent="Materials", summary="Copper miners benefit from electrification demand and scarce new supply."),
    _t("lithium", "Lithium", "sector", parent="Materials", summary="Lithium producers feed battery supply chains for EVs and storage."),
    _t("rare_earths", "Rare Earths", "sector", parent="Materials", summary="Rare earth producers supply magnets and electronics critical to defense and EVs."),
    _t("cement", "Cement", "sector", parent="Materials", summary="Cement makers supply construction materials with local regional pricing."),
    _t("glass", "Glass", "sector", parent="Materials", summary="Glass manufacturers serve containers, construction, and automotive markets."),
    _t("paper", "Paper", "sector", parent="Materials", summary="Paper and pulp companies produce packaging and printing grades."),
    _t("fertilizers", "Fertilizers", "sector", parent="Materials", summary="Fertilizer producers supply nutrients critical to crop yields and food security."),
    # Utilities
    _t("electric_utilities", "Electric Utilities", "sector", parent="Utilities", summary="Electric utilities generate and distribute power under regulated returns."),
    _t("water_utilities", "Water Utilities", "sector", parent="Utilities", summary="Water utilities provide essential service with defensive, regulated cash flows."),
    _t("gas_utilities", "Gas Utilities", "sector", parent="Utilities", summary="Gas utilities distribute natural gas to homes and businesses."),
    _t("renewable_utilities", "Renewable Utilities", "sector", parent="Utilities", summary="Renewable-focused utilities and IPPs own wind, solar, and storage fleets."),
    # REIT subtype missing
    _t("reit_cell_tower", "Cell Tower REITs", "sector", parent="Real Estate", summary="Tower REITs lease antenna space to wireless carriers with long contracts."),
    # Agriculture
    _t("farming", "Farming", "sector", parent="Agriculture", summary="Farm operators grow crops and raise animals exposed to weather and commodity prices."),
    _t("ag_equipment", "Agricultural Equipment", "sector", parent="Agriculture", summary="Ag equipment makers sell tractors and implements into farm capex cycles."),
    _t("seeds", "Seeds", "sector", parent="Agriculture", summary="Seed and trait companies sell genetically improved seeds to growers."),
    _t("livestock", "Livestock", "sector", parent="Agriculture", summary="Livestock producers raise cattle, poultry, and hogs for protein demand."),
    _t("food_distribution", "Food Distribution", "sector", parent="Agriculture", summary="Distributors connect farms and processors to grocery and foodservice channels."),
    _t("fisheries", "Fisheries", "sector", parent="Agriculture", summary="Seafood producers and aquafarms supply protein with sustainability challenges."),
    # Transportation
    _t("ports", "Ports", "sector", parent="Transportation", summary="Port operators handle cargo volumes tied to global trade."),
    _t("airports", "Airports", "sector", parent="Transportation", summary="Airport operators earn from aeronautical and retail concession traffic."),
    _t("freight_forwarding", "Freight Forwarding", "sector", parent="Transportation", summary="Freight forwarders arrange multimodal shipping for shippers worldwide."),
    _t("public_transit", "Public Transit", "sector", parent="Transportation", summary="Transit-related firms and suppliers serve urban mobility systems."),
    # Space
    _t("satellites", "Satellite Companies", "sector", parent="Space", summary="Satellite operators provide imaging, broadband, and navigation services."),
    _t("launch_providers", "Launch Providers", "sector", parent="Space", summary="Launch companies put payloads into orbit competing on cost per kilogram."),
    _t("space_infrastructure", "Space Infrastructure", "sector", parent="Space", summary="Space infrastructure covers ground stations, components, and orbital services."),
    # Emerging
    _t("carbon_capture", "Carbon Capture", "sector", parent="Emerging Industries", summary="Carbon capture technologies remove or sequester CO₂ for industrial decarbonization."),
    _t("synthetic_biology", "Synthetic Biology", "sector", parent="Emerging Industries", summary="Synbio designs organisms and biomolecules for materials, food, and therapeutics."),
    _t("fusion_energy", "Fusion Energy", "sector", parent="Emerging Industries", summary="Fusion startups pursue net energy gain for abundant low-carbon power."),
    _t("3d_printing", "3D Printing", "sector", parent="Emerging Industries", summary="Additive manufacturing builds complex parts with less waste than machining."),
    _t("drone_technology", "Drone Technology", "sector", parent="Emerging Industries", summary="Drone platforms serve imaging, delivery, and defense use cases."),
    _t("autonomous_vehicles", "Autonomous Vehicles", "sector", parent="Emerging Industries", summary="AV stacks combine sensors, software, and compute for driverless mobility."),
    _t("wearable_technology", "Wearable Technology", "sector", parent="Emerging Industries", summary="Wearables track health and productivity on the body with sensor fusion."),
    _t("digital_payments", "Digital Payments", "sector", parent="Emerging Industries", summary="Digital payments rail move money online with take rates and network effects."),
    _t("blockchain_infra", "Blockchain Infrastructure", "sector", parent="Emerging Industries", summary="Blockchain infrastructure provides rails for crypto settlement and tokenization."),
    _t("clean_water", "Clean Water Technology", "sector", parent="Emerging Industries", summary="Water tech improves purification, desalination, and efficiency for scarce freshwater."),
    _t("waste_management", "Waste Management", "sector", parent="Emerging Industries", summary="Waste managers collect and process refuse with landfill and recycling assets."),
    _t("recycling", "Recycling", "sector", parent="Emerging Industries", summary="Recycling firms circularize materials streams with commodity residual exposure."),
)
