"""Auto-generated macro playbooks — one profile per industry bucket."""

from __future__ import annotations

from typing import Any

# event -> (rate_delta, expansion_delta, nasdaq_delta, note)
PLAYBOOKS: dict[str, dict[str, tuple[float, float, float, str]]] = {
    "biotech": {
        "fda_approval": (0.0, 0.0, 0.15, 'binary_positive'),
        "trial_failure": (0.0, 0.0, -0.2, 'binary_negative'),
        "offering_dilution": (-0.02, -0.04, -0.08, 'capital_raise'),
        "partnership_deal": (0.0, 0.05, 0.08, 'collaboration_premium'),
        "fda_approves": (0.0, 0.05, 0.04, 'bull_event:fda approves'),
        "topline_positive": (0.0, 0.05, 0.04, 'bull_event:topline positive'),
        "clinical_hold": (0.0, -0.05, -0.04, 'bear_event:clinical hold'),
        "trial_halted": (0.0, -0.05, -0.04, 'bear_event:trial halted'),
    },
    "big_pharma": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "fda_approval": (0.0, 0.05, 0.04, 'bull_event:fda approval'),
        "label_expansion": (0.0, 0.05, 0.04, 'bull_event:label expansion'),
        "patent_expiry": (0.0, -0.05, -0.04, 'bear_event:patent expiry'),
        "price_cap": (0.0, -0.05, -0.04, 'bear_event:price cap'),
    },
    "medical_devices": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "fda_clearance": (0.0, 0.05, 0.04, 'bull_event:fda clearance'),
        "510k": (0.0, 0.05, 0.04, 'bull_event:510k'),
        "class_1_recall": (0.0, -0.05, -0.04, 'bear_event:class 1 recall'),
        "warning_letter": (0.0, -0.05, -0.04, 'bear_event:warning letter'),
    },
    "life_sciences_tools": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "record_orders": (0.0, 0.05, 0.04, 'bull_event:record orders'),
        "backlog_up": (0.0, 0.05, 0.04, 'bull_event:backlog up'),
        "guidance_cut": (0.0, -0.05, -0.04, 'bear_event:guidance cut'),
        "funding_drought": (0.0, -0.05, -0.04, 'bear_event:funding drought'),
    },
    "healthcare_providers": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "cms_rate": (0.0, 0.05, 0.04, 'bull_event:cms rate'),
        "star_rating": (0.0, 0.05, 0.04, 'bull_event:star rating'),
        "reimbursement_cut": (0.0, -0.05, -0.04, 'bear_event:reimbursement cut'),
        "mlr_pressure": (0.0, -0.05, -0.04, 'bear_event:mlr pressure'),
    },
    "healthcare_technology": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "enterprise_deal": (0.0, 0.05, 0.04, 'bull_event:enterprise deal'),
        "platform_migration": (0.0, 0.05, 0.04, 'bull_event:platform migration'),
        "hipaa": (0.0, -0.05, -0.04, 'bear_event:hipaa'),
        "data_breach": (0.0, -0.05, -0.04, 'bear_event:data breach'),
    },
    "residential_reits": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (0.0, -0.05, -0.04, 'bear_event:yield spike'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "rent_reacceleration": (0.0, 0.05, 0.04, 'bull_event:rent reacceleration'),
        "fed_pivot": (0.0, 0.05, 0.04, 'bull_event:fed pivot'),
        "housing_starts_surge": (0.0, -0.05, -0.04, 'bear_event:housing starts surge'),
    },
    "commercial_office_reits": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "anchor_lease": (0.0, 0.05, 0.04, 'bull_event:anchor lease'),
        "occupancy_beat": (0.0, 0.05, 0.04, 'bull_event:occupancy beat'),
        "tenant_bankruptcy": (0.0, -0.05, -0.04, 'bear_event:tenant bankruptcy'),
        "cre_loan": (0.0, -0.05, -0.04, 'bear_event:cre loan'),
    },
    "retail_reits": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "tenant_sales_beat": (0.0, 0.05, 0.04, 'bull_event:tenant sales beat'),
        "re-leasing_positive": (0.0, 0.05, 0.04, 'bull_event:re-leasing positive'),
        "chapter_11": (0.0, -0.05, -0.04, 'bear_event:chapter 11'),
        "store_closure_wave": (0.0, -0.05, -0.04, 'bear_event:store closure wave'),
    },
    "industrial_logistics_reits": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "record_leasing": (0.0, 0.05, 0.04, 'bull_event:record leasing'),
        "rent_spread": (0.0, 0.05, 0.04, 'bull_event:rent spread'),
        "warehouse_glut": (0.0, -0.05, -0.04, 'bear_event:warehouse glut'),
        "demand_softening": (0.0, -0.05, -0.04, 'bear_event:demand softening'),
    },
    "specialized_reits": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "hyperscaler_deal": (0.0, 0.05, 0.04, 'bull_event:hyperscaler deal'),
        "ai_server_demand": (0.0, 0.05, 0.04, 'bull_event:ai server demand'),
        "capex_cut": (0.0, -0.05, -0.04, 'bear_event:capex cut'),
        "yield_jump": (0.0, -0.05, -0.04, 'bear_event:yield jump'),
    },
    "semiconductors": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.2, 0.3, 'hyperscaler_spend'),
        "export_ban": (-0.05, -0.15, -0.25, 'trade_war'),
        "inventory_glut": (0.0, -0.2, -0.15, 'cycle_down'),
        "beat_on_ai": (0.0, 0.05, 0.04, 'bull_event:beat on ai'),
        "guidance_raise": (0.0, 0.05, 0.04, 'bull_event:guidance raise'),
        "export_restriction": (0.0, -0.05, -0.04, 'bear_event:export restriction'),
        "inventory_days_high": (0.0, -0.05, -0.04, 'bear_event:inventory days high'),
    },
    "semi_equipment": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "tsmc_capex": (0.0, 0.05, 0.04, 'bull_event:tsmc capex'),
        "intel_fab": (0.0, 0.05, 0.04, 'bull_event:intel fab'),
        "push_out": (0.0, -0.05, -0.04, 'bear_event:push out'),
        "order_push": (0.0, -0.05, -0.04, 'bear_event:order push'),
    },
    "application_software": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "raise_nrr": (0.0, 0.05, 0.04, 'bull_event:raise nrr'),
        "large_deal": (0.0, 0.05, 0.04, 'bull_event:large deal'),
        "layoffs": (0.0, -0.05, -0.04, 'bear_event:layoffs'),
        "capex_cut_it": (0.0, -0.05, -0.04, 'bear_event:capex cut it'),
    },
    "systems_software": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "major_breach_industry": (0.0, 0.05, 0.04, 'bull_event:major breach industr'),
        "fed_mandate": (0.0, 0.05, 0.04, 'bull_event:fed mandate'),
        "zero_day": (0.0, -0.05, -0.04, 'bear_event:zero day'),
        "outage": (0.0, -0.05, -0.04, 'bear_event:outage'),
    },
    "tech_hardware": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "product_launch": (0.0, 0.05, 0.04, 'bull_event:product launch'),
        "sell_through_beat": (0.0, 0.05, 0.04, 'bull_event:sell through beat'),
        "cut_production": (0.0, -0.05, -0.04, 'bear_event:cut production'),
        "demand_warning": (0.0, -0.05, -0.04, 'bear_event:demand warning'),
    },
    "diversified_banks": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "fed_hike": (0.0, 0.05, 0.04, 'bull_event:fed hike'),
        "credit_fear": (-0.15, -0.1, -0.05, 'cecl_fear'),
        "steepening": (0.08, 0.03, 0.0, 'curve_steepen'),
        "stress_test_clear": (0.0, 0.05, 0.04, 'bull_event:stress test clear'),
        "svb": (0.0, -0.05, -0.04, 'bear_event:svb'),
        "deposit_outflow": (0.0, -0.05, -0.04, 'bear_event:deposit outflow'),
    },
    "regional_banks": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "deposit_run": (0.0, -0.05, -0.04, 'bear_event:deposit run'),
        "cre_stress": (-0.15, -0.1, 0.0, 'cre_exposure'),
        "deposit_inflows": (0.0, 0.05, 0.04, 'bull_event:deposit inflows'),
        "fdic_calm": (0.0, 0.05, 0.04, 'bull_event:fdic calm'),
        "regional_bank": (0.0, -0.05, -0.04, 'bear_event:regional bank'),
    },
    "property_casualty_insurance": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "rate_approval": (0.0, 0.05, 0.04, 'bull_event:rate approval'),
        "pricing_hard": (0.0, 0.05, 0.04, 'bull_event:pricing hard'),
        "cat_event": (0.0, -0.05, -0.04, 'bear_event:cat event'),
        "storm_landfall": (0.0, -0.05, -0.04, 'bear_event:storm landfall'),
    },
    "life_health_insurance": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "y": (0.0, 0.05, 0.04, 'bull_event:y'),
        "i": (0.0, 0.05, 0.04, 'bull_event:i'),
        "rate_cut_cycle": (0.0, -0.05, -0.04, 'bear_event:rate cut cycle'),
        "crediting_rate": (0.0, -0.05, -0.04, 'bear_event:crediting rate'),
    },
    "financial_data_exchanges": {
        "risk_on": (0.02, 0.08, 0.06, 'beta_risk_on'),
        "risk_off": (-0.02, -0.06, -0.05, 'beta_risk_off'),
        "earnings_beat_sector": (0.0, 0.06, 0.04, 'peer_sympathy'),
        "earnings_miss_sector": (0.0, -0.06, -0.04, 'peer_sympathy_neg'),
        "vol_spike": (0.0, 0.05, 0.04, 'bull_event:vol spike'),
        "record_volume": (0.0, 0.05, 0.04, 'bull_event:record volume'),
        "trading_slowdown": (0.0, -0.05, -0.04, 'bear_event:trading slowdown'),
        "fee_cut": (0.0, -0.05, -0.04, 'bear_event:fee cut'),
    },
    "consumer_finance": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "spend_data_strong": (0.0, 0.05, 0.04, 'bull_event:spend data strong'),
        "naco_stable": (0.0, 0.05, 0.04, 'bull_event:naco stable'),
        "delinquency": (0.0, -0.05, -0.04, 'bear_event:delinquency'),
        "charge-off": (0.0, -0.05, -0.04, 'bear_event:charge-off'),
    },
    "integrated_oil_gas": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.04, -0.08, 0.0, 'usd_inverse_commodity'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "opec_cut": (0.05, 0.1, 0.05, 'crude_rally'),
        "wti_spike": (0.08, 0.12, 0.06, 'commodity_beta'),
        "demand_fear": (-0.05, -0.15, -0.08, 'recession_oil'),
        "opec+": (0.0, 0.05, 0.04, 'bull_event:opec+'),
        "supply_cut": (0.0, 0.05, 0.04, 'bull_event:supply cut'),
        "demand_concern": (0.0, -0.05, -0.04, 'bear_event:demand concern'),
        "inventory_build": (0.0, -0.05, -0.04, 'bear_event:inventory build'),
    },
    "oil_gas_ep": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.04, -0.08, 0.0, 'usd_inverse_commodity'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "eia_draw": (0.0, 0.05, 0.04, 'bull_event:eia draw'),
        "rig_up": (0.0, 0.05, 0.04, 'bull_event:rig up'),
        "eia_build": (0.0, -0.05, -0.04, 'bear_event:eia build'),
        "gas_price_collapse": (0.0, -0.05, -0.04, 'bear_event:gas price collapse'),
    },
    "oil_gas_equipment": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.04, -0.08, 0.0, 'usd_inverse_commodity'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "rig_count_up": (0.0, 0.05, 0.04, 'bull_event:rig count up'),
        "dayrate_hike": (0.0, 0.05, 0.04, 'bull_event:dayrate hike'),
        "capex_guide_down": (0.0, -0.05, -0.04, 'bear_event:capex guide down'),
        "stacked_frac": (0.0, -0.05, -0.04, 'bear_event:stacked frac'),
    },
    "renewable_energy": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "tax_credit_extend": (0.0, 0.05, 0.04, 'bull_event:tax credit extend'),
        "solar_install_beat": (0.0, 0.05, 0.04, 'bull_event:solar install beat'),
        "subsidy_rollback": (0.0, -0.05, -0.04, 'bear_event:subsidy rollback'),
        "module_oversupply": (0.0, -0.05, -0.04, 'bear_event:module oversupply'),
    },
    "electric_gas_utilities": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "rate_case_approved": (0.0, 0.05, 0.04, 'bull_event:rate case approved'),
        "load_forecast_up": (0.0, 0.05, 0.04, 'bull_event:load forecast up'),
        "wildfire": (0.0, -0.05, -0.04, 'bear_event:wildfire'),
        "rate_denial": (0.0, -0.05, -0.04, 'bear_event:rate denial'),
    },
    "auto_manufacturers": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "delivery_record": (0.0, 0.05, 0.04, 'bull_event:delivery record'),
        "ev_subsidy": (0.0, 0.05, 0.04, 'bull_event:ev subsidy'),
        "uaw_strike": (0.0, -0.05, -0.04, 'bear_event:uaw strike'),
        "recall": (0.0, -0.05, -0.04, 'bear_event:recall'),
    },
    "luxury_goods": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "china_sales_beat": (0.0, 0.05, 0.04, 'bull_event:china sales beat'),
        "pricing_increase": (0.0, 0.05, 0.04, 'bull_event:pricing increase'),
        "china_weak": (0.0, -0.05, -0.04, 'bear_event:china weak'),
        "discounting": (0.0, -0.05, -0.04, 'bear_event:discounting'),
    },
    "hotels_resorts_cruise": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "revpar_beat": (0.0, 0.05, 0.04, 'bull_event:revpar beat'),
        "booking_record": (0.0, 0.05, 0.04, 'bull_event:booking record'),
        "travel_warning": (0.0, -0.05, -0.04, 'bear_event:travel warning'),
        "outbreak": (0.0, -0.05, -0.04, 'bear_event:outbreak'),
    },
    "restaurants_food": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "beef_spike": (-0.08, 0.0, 0.0, 'protein_cost_margin'),
        "wheat_spike": (-0.06, 0.0, 0.0, 'grain_input'),
        "wage_hike": (-0.1, 0.0, 0.0, 'labor_margin'),
        "traffic_up": (0.08, 0.05, 0.0, 'same_store_strength'),
        "sss_beat": (0.0, 0.05, 0.04, 'bull_event:sss beat'),
        "menu_innovation": (0.0, 0.05, 0.04, 'bull_event:menu innovation'),
        "food_safety": (0.0, -0.05, -0.04, 'bear_event:food safety'),
        "minimum_wage": (0.0, -0.05, -0.04, 'bear_event:minimum wage'),
    },
    "hypermarkets_discount": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "holiday_beat": (0.0, 0.05, 0.04, 'bull_event:holiday beat'),
        "traffic_surge": (0.0, 0.05, 0.04, 'bull_event:traffic surge'),
        "guidance_cut": (0.0, -0.05, -0.04, 'bear_event:guidance cut'),
        "inventory_markdown": (0.0, -0.05, -0.04, 'bear_event:inventory markdown'),
    },
    "household_personal_products": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "p": (0.0, 0.05, 0.04, 'bull_event:p'),
        "r": (0.0, 0.05, 0.04, 'bull_event:r'),
        "volume_decline": (0.0, -0.05, -0.04, 'bear_event:volume decline'),
        "promotional_intensity": (0.0, -0.05, -0.04, 'bear_event:promotional intensit'),
    },
    "packaged_foods": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "corn_spike": (0.0, -0.05, -0.04, 'bear_event:corn spike'),
        "glp1_headwind": (-0.1, 0.0, 0.0, 'snacking_fear'),
        "pricing_power": (0.08, 0.02, 0.0, 'brand_pricing'),
        "pricing_hold": (0.0, 0.05, 0.04, 'bull_event:pricing hold'),
        "volume_positive": (0.0, 0.05, 0.04, 'bull_event:volume positive'),
        "glucagon": (0.0, -0.05, -0.04, 'bear_event:glucagon'),
    },
    "aerospace_defense": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "ndaa": (0.0, 0.05, 0.04, 'bull_event:ndaa'),
        "contract_win": (0.0, 0.05, 0.04, 'bull_event:contract win'),
        "grounding": (0.0, -0.05, -0.04, 'bear_event:grounding'),
        "quality_issue": (0.0, -0.05, -0.04, 'bear_event:quality issue'),
    },
    "air_freight_logistics": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "peak_season_strong": (0.0, 0.05, 0.04, 'bull_event:peak season strong'),
        "yield_beat": (0.0, 0.05, 0.04, 'bull_event:yield beat'),
        "trade_war": (0.0, -0.05, -0.04, 'bear_event:trade war'),
        "fuel_surcharge": (0.0, -0.05, -0.04, 'bear_event:fuel surcharge'),
    },
    "railroads": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "carload_beat": (0.0, 0.05, 0.04, 'bull_event:carload beat'),
        "precision_scheduled_railroad": (0.0, 0.05, 0.04, 'bull_event:precision scheduled '),
        "derailment": (0.0, -0.05, -0.04, 'bear_event:derailment'),
        "strike_vote": (0.0, -0.05, -0.04, 'bear_event:strike vote'),
    },
    "construction_machinery": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "infrastructure": (0.0, 0.05, 0.04, 'bull_event:infrastructure'),
        "dealer_survey_up": (0.0, 0.05, 0.04, 'bull_event:dealer survey up'),
        "dealer_inventory_high": (0.0, -0.05, -0.04, 'bear_event:dealer inventory hig'),
        "china_demand": (0.0, -0.05, -0.04, 'bear_event:china demand'),
    },
    "building_products": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "permits_up": (0.0, 0.05, 0.04, 'bull_event:permits up'),
        "housing_starts_beat": (0.0, 0.05, 0.04, 'bull_event:housing starts beat'),
        "mortgage_rate": (0.0, -0.05, -0.04, 'bear_event:mortgage rate'),
        "housing_miss": (0.0, -0.05, -0.04, 'bear_event:housing miss'),
    },
    "chemicals": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "spread_expansion": (0.0, 0.05, 0.04, 'bull_event:spread expansion'),
        "volume_beat": (0.0, 0.05, 0.04, 'bull_event:volume beat'),
        "destocking": (0.0, -0.05, -0.04, 'bear_event:destocking'),
        "natural_gas_feed": (0.0, -0.05, -0.04, 'bear_event:natural gas feed'),
    },
    "metals_mining": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.05, -0.1, 0.0, 'commodity_inverse_usd'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "china_stimulus": (0.0, 0.05, 0.04, 'bull_event:china stimulus'),
        "lme_draw": (0.08, 0.12, 0.0, 'supply_tight'),
        "lme_cancel": (0.0, 0.05, 0.04, 'bull_event:lme cancel'),
        "china_weak": (0.0, -0.05, -0.04, 'bear_event:china weak'),
        "inventory_surge": (0.0, -0.05, -0.04, 'bear_event:inventory surge'),
    },
    "wireless_telecom": {
        "rate_hike": (-0.18, -0.04, -0.04, 'bond_yield_competition'),
        "rate_cut": (0.16, 0.04, 0.04, 'yield_proxy_bid'),
        "yield_spike": (-0.12, -0.03, -0.03, 'duration_pain'),
        "fed_pivot_dovish": (0.14, 0.05, 0.03, 'duration_relief'),
        "postpaid_net_add": (0.0, 0.05, 0.04, 'bull_event:postpaid net add'),
        "dividend_raise": (0.0, 0.05, 0.04, 'bull_event:dividend raise'),
        "price_cut": (0.0, -0.05, -0.04, 'bear_event:price cut'),
        "churn_warning": (0.0, -0.05, -0.04, 'bear_event:churn warning'),
    },
    "interactive_media": {
        "rate_hike": (-0.04, -0.06, -0.14, 'growth_multiple_compress'),
        "nasdaq_rally": (0.0, 0.06, 0.22, 'beta_rally'),
        "nasdaq_selloff": (0.0, -0.08, -0.2, 'beta_drawdown'),
        "ai_capex_up": (0.0, 0.12, 0.25, 'tech_spend_cycle'),
        "ad_beat": (0.0, 0.05, 0.04, 'bull_event:ad beat'),
        "engagement_record": (0.0, 0.05, 0.04, 'bull_event:engagement record'),
        "antitrust": (0.0, -0.05, -0.04, 'bear_event:antitrust'),
        "ad_slowdown": (0.0, -0.05, -0.04, 'bear_event:ad slowdown'),
    },
    "entertainment_streaming": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "subscriber_beat": (0.0, 0.05, 0.04, 'bull_event:subscriber beat'),
        "box_office_record": (0.0, 0.05, 0.04, 'bull_event:box office record'),
        "writers_strike": (0.0, -0.05, -0.04, 'bear_event:writers strike'),
        "sub_miss": (0.0, -0.05, -0.04, 'bear_event:sub miss'),
    },
    "environmental_waste": {
        "recession_fear": (0.04, -0.08, -0.06, 'flight_to_quality'),
        "risk_on_rally": (-0.02, 0.06, 0.04, 'cyclical_rotation_out'),
        "vix_spike": (0.06, -0.04, -0.08, 'defensive_bid'),
        "consumer_weakness": (0.03, -0.06, -0.02, 'staples_relative'),
        "price_increase": (0.0, 0.05, 0.04, 'bull_event:price increase'),
        "contract_win": (0.0, 0.05, 0.04, 'bull_event:contract win'),
        "fuel_surcharge_lag": (0.0, -0.05, -0.04, 'bear_event:fuel surcharge lag'),
        "volume_miss": (0.0, -0.05, -0.04, 'bear_event:volume miss'),
    },
    "apparel_retail": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "comp_positive": (0.0, 0.05, 0.04, 'bull_event:comp positive'),
        "margin_beat": (0.0, 0.05, 0.04, 'bull_event:margin beat'),
        "inventory_up": (0.0, -0.05, -0.04, 'bear_event:inventory up'),
        "weather_miss": (0.0, -0.05, -0.04, 'bear_event:weather miss'),
    },
    "marine_shipping": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.04, -0.08, 0.0, 'usd_inverse_commodity'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "bdi_surge": (0.0, 0.05, 0.04, 'bull_event:bdi surge'),
        "canal_delay": (0.0, 0.05, 0.04, 'bull_event:canal delay'),
        "rate_crash": (0.0, -0.05, -0.04, 'bear_event:rate crash'),
        "demurrage": (0.0, -0.05, -0.04, 'bear_event:demurrage'),
    },
    "independent_power_producers": {
        "commodity_spike": (0.04, 0.12, 0.02, 'input_or_output_beta'),
        "commodity_crash": (-0.03, -0.1, -0.02, 'margin_relief_or_pain'),
        "dollar_spike": (-0.04, -0.08, 0.0, 'usd_inverse_commodity'),
        "supply_disruption": (0.05, 0.1, 0.0, 'scarcity_premium'),
        "heat_dome": (0.0, 0.05, 0.04, 'bull_event:heat dome'),
        "power_price_spike": (0.0, 0.05, 0.04, 'bull_event:power price spike'),
        "power_price_negative": (0.0, -0.05, -0.04, 'bear_event:power price negative'),
        "regulatory_cap": (0.0, -0.05, -0.04, 'bear_event:regulatory cap'),
    },
    "commercial_services": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "jobs_report_strong": (0.0, 0.05, 0.04, 'bull_event:jobs report strong'),
        "contract_win": (0.0, 0.05, 0.04, 'bull_event:contract win'),
        "layoffs": (0.0, -0.05, -0.04, 'bear_event:layoffs'),
        "office_empty": (0.0, -0.05, -0.04, 'bear_event:office empty'),
    },
    "distributors": {
        "rate_hike": (-0.06, -0.04, -0.08, 'mixed_duration_growth'),
        "pmi_up": (0.04, 0.1, 0.06, 'cycle_and_beta'),
        "pmi_down": (-0.03, -0.08, -0.05, 'demand_softness'),
        "guidance_raise": (0.02, 0.08, 0.05, 'operating_leverage'),
        "daily_sales_up": (0.0, 0.05, 0.04, 'bull_event:daily sales up'),
        "share_gain": (0.0, 0.05, 0.04, 'bull_event:share gain'),
        "customer_destock": (0.0, -0.05, -0.04, 'bear_event:customer destock'),
        "margin_squeeze": (0.0, -0.05, -0.04, 'bear_event:margin squeeze'),
    },
}

GLOBAL_HEADLINE_RULES: list[tuple[str, str]] = [('fda approv', 'fda_approval'), ('trial fail', 'trial_failure'), ('rate hike', 'rate_hike'), ('rate cut', 'rate_cut'), ('fed pivot', 'fed_pivot_dovish'), ('opec', 'opec_cut'), ('export ban', 'export_ban'), ('beef', 'beef_spike'), ('wheat', 'wheat_spike'), ('deposit run', 'deposit_run'), ('antitrust', 'antitrust'), ('heat wave', 'heat_wave'), ('china stimulus', 'china_stimulus'), ('inventory glut', 'inventory_glut'), ('ai capex', 'ai_capex_up'), ('yield spike', 'yield_spike'), ('vix spike', 'vix_spike'), ('recession', 'recession_fear'), ('guidance raise', 'guidance_raise'), ('earnings beat', 'earnings_beat_sector')]

INDUSTRY_PROFILES: dict[str, dict[str, Any]] = {
    "biotech": {
        "name": 'Biotechnology',
        "mode": 'event_driven',
        "etf": 'IBB',
        "leaders": ['AMGN', 'GILD', 'VRTX', 'REGN', 'BIIB', 'MRNA'],
        "notes": 'R&D burn vs cash runway; binary trial outcomes; low SPY correlation.',
        "event_count": 8,
    },
    "big_pharma": {
        "name": 'Big Pharma',
        "mode": 'defensive',
        "etf": 'XPH',
        "leaders": ['LLY', 'JNJ', 'MRK', 'PFE', 'ABBV', 'NVS', 'AZN', 'BMY'],
        "notes": 'Patent cliff timeline; Medicare pricing; low-beta defensive.',
        "event_count": 8,
    },
    "medical_devices": {
        "name": 'Medical Devices',
        "mode": 'hybrid',
        "etf": 'IHI',
        "leaders": ['MDT', 'ABT', 'ISRG', 'SYK', 'BSX', 'EW', 'ZBH'],
        "notes": 'Gross margin >60%; elective surgery volume driver.',
        "event_count": 8,
    },
    "life_sciences_tools": {
        "name": 'Life Sciences Tools',
        "mode": 'follow_nasdaq',
        "etf": 'XLV',
        "leaders": ['TMO', 'DHR', 'A', 'IQV', 'CRL', 'WAT', 'TECH'],
        "notes": 'Backlog growth; VC funding into biotech drives instrument demand.',
        "event_count": 8,
    },
    "healthcare_providers": {
        "name": 'Healthcare Providers',
        "mode": 'defensive',
        "etf": 'XLV',
        "leaders": ['UNH', 'ELV', 'CI', 'HUM', 'CVS', 'HCA', 'UHS'],
        "notes": 'Bed occupancy; payer mix; CMS reimbursement updates.',
        "event_count": 8,
    },
    "healthcare_technology": {
        "name": 'Healthcare Technology',
        "mode": 'follow_nasdaq',
        "etf": 'XLV',
        "leaders": ['VEEV', 'TDOC', 'HIMS', 'DOCS', 'CERN', 'MDRX'],
        "notes": 'LTV/CAC; privacy regulation hits entire group.',
        "event_count": 8,
    },
    "residential_reits": {
        "name": 'Residential REITs',
        "mode": 'inverse_rates',
        "etf": 'REZ',
        "leaders": ['EQR', 'AVB', 'ESS', 'MAA', 'UDR', 'CPT', 'AIV'],
        "notes": 'Net effective rent; inverse to 10y Treasury.',
        "event_count": 7,
    },
    "commercial_office_reits": {
        "name": 'Commercial Office REITs',
        "mode": 'inverse_rates',
        "etf": 'VNQ',
        "leaders": ['BXP', 'VNO', 'SLG', 'KRC', 'DEI', 'OFC'],
        "notes": 'WAULT; transit ridership; CRE lending standards.',
        "event_count": 8,
    },
    "retail_reits": {
        "name": 'Retail REITs',
        "mode": 'inverse_rates',
        "etf": 'VNQ',
        "leaders": ['SPG', 'O', 'REG', 'FRT', 'KIM', 'BRX'],
        "notes": 'Tenant occupancy cost ratio; anchor tenant risk.',
        "event_count": 8,
    },
    "industrial_logistics_reits": {
        "name": 'Industrial & Logistics REITs',
        "mode": 'hybrid',
        "etf": 'IYR',
        "leaders": ['PLD', 'EXR', 'PSA', 'REXR', 'FR', 'STAG', 'EGP'],
        "notes": 'Rent reversion; e-commerce % of retail.',
        "event_count": 8,
    },
    "specialized_reits": {
        "name": 'Specialized REITs',
        "mode": 'hybrid',
        "etf": 'XLRE',
        "leaders": ['EQIX', 'AMT', 'CCI', 'DLR', 'WELL', 'PSA', 'SBAC'],
        "notes": 'PUE/churn; cloud capex from MSFT/AMZN/GOOG.',
        "event_count": 8,
    },
    "semiconductors": {
        "name": 'Semiconductors',
        "mode": 'follow_nasdaq',
        "etf": 'SMH',
        "leaders": ['NVDA', 'TSM', 'AVGO', 'AMD', 'INTC', 'QCOM', 'MU', 'ASML'],
        "notes": 'Book-to-bill; inventory days; trade war headline risk.',
        "event_count": 10,
    },
    "semi_equipment": {
        "name": 'Semiconductor Equipment',
        "mode": 'follow_nasdaq',
        "etf": 'SMH',
        "leaders": ['ASML', 'LRCX', 'AMAT', 'KLAC', 'TER', 'ONTO'],
        "notes": 'Multi-year boom/bust; moves on fab capex headlines.',
        "event_count": 8,
    },
    "application_software": {
        "name": 'Application Software',
        "mode": 'follow_nasdaq',
        "etf": 'IGV',
        "leaders": ['CRM', 'NOW', 'ADBE', 'INTU', 'WDAY', 'SNOW', 'DDOG'],
        "notes": 'NRR >110%; IT budget surveys; rate-sensitive multiples.',
        "event_count": 8,
    },
    "systems_software": {
        "name": 'Systems Software',
        "mode": 'follow_nasdaq',
        "etf": 'IGV',
        "leaders": ['MSFT', 'ORCL', 'PANW', 'CRWD', 'FTNT', 'ZS', 'NET'],
        "notes": 'Mission-critical; ransomware waves lift group.',
        "event_count": 8,
    },
    "tech_hardware": {
        "name": 'Technology Hardware',
        "mode": 'hybrid',
        "etf": 'XLK',
        "leaders": ['AAPL', 'DELL', 'HPQ', 'HPE', 'STX', 'WDC', 'LOGI'],
        "notes": 'Consumer upgrade cycles; Foxconn/assembly signals.',
        "event_count": 8,
    },
    "diversified_banks": {
        "name": 'Diversified Banks',
        "mode": 'hybrid',
        "etf": 'KBE',
        "leaders": ['JPM', 'BAC', 'WFC', 'C', 'MS', 'GS', 'USB', 'PNC'],
        "notes": 'NIM vs Fed path; stress tests move group.',
        "event_count": 10,
    },
    "regional_banks": {
        "name": 'Regional Banks',
        "mode": 'hybrid',
        "etf": 'KRE',
        "leaders": ['PNC', 'USB', 'TFC', 'FITB', 'RF', 'KEY', 'ZION'],
        "notes": 'Systemic cluster risk on one failure.',
        "event_count": 9,
    },
    "property_casualty_insurance": {
        "name": 'Property & Casualty Insurance',
        "mode": 'defensive',
        "etf": 'KIE',
        "leaders": ['PGR', 'TRV', 'ALL', 'CB', 'AIG', 'HIG', 'WRB'],
        "notes": 'Combined ratio; NOAA hurricane season.',
        "event_count": 8,
    },
    "life_health_insurance": {
        "name": 'Life & Health Insurance',
        "mode": 'inverse_rates',
        "etf": 'KIE',
        "leaders": ['MET', 'PRU', 'AFL', 'UNM', 'LNC', 'GL'],
        "notes": 'Bond book yield; demographic aging.',
        "event_count": 8,
    },
    "financial_data_exchanges": {
        "name": 'Financial Data & Exchanges',
        "mode": 'follow_market',
        "etf": 'XLF',
        "leaders": ['SPGI', 'ICE', 'CME', 'MCO', 'MSCI', 'NDAQ', 'COIN'],
        "notes": 'ADV and VIX drive exchange revenues.',
        "event_count": 8,
    },
    "consumer_finance": {
        "name": 'Consumer Finance',
        "mode": 'hybrid',
        "etf": 'XLF',
        "leaders": ['V', 'MA', 'AXP', 'COF', 'SYF', 'ALLY', 'SOFI'],
        "notes": 'NCO rate; consumer credit delinquency.',
        "event_count": 8,
    },
    "integrated_oil_gas": {
        "name": 'Integrated Oil & Gas',
        "mode": 'commodity',
        "etf": 'XLE',
        "leaders": ['XOM', 'CVX', 'SHEL', 'TTE', 'BP', 'COP'],
        "notes": 'Lockstep with WTI/Brent futures.',
        "event_count": 11,
    },
    "oil_gas_ep": {
        "name": 'Oil & Gas E&P',
        "mode": 'commodity',
        "etf": 'XOP',
        "leaders": ['EOG', 'PXD', 'DVN', 'FANG', 'MRO', 'OVV', 'APA'],
        "notes": 'Amplified oil beta; EIA inventory weekly.',
        "event_count": 8,
    },
    "oil_gas_equipment": {
        "name": 'Oil & Gas Equipment',
        "mode": 'commodity',
        "etf": 'XES',
        "leaders": ['SLB', 'HAL', 'BKR', 'NOV', 'CHX', 'FTI'],
        "notes": 'Lags crude 3-6 months.',
        "event_count": 8,
    },
    "renewable_energy": {
        "name": 'Renewable Energy',
        "mode": 'inverse_rates',
        "etf": 'ICLN',
        "leaders": ['ENPH', 'SEDG', 'FSLR', 'NEE', 'RUN', 'PLUG'],
        "notes": 'Rate-sensitive upfront capex; policy driven.',
        "event_count": 8,
    },
    "electric_gas_utilities": {
        "name": 'Electric & Gas Utilities',
        "mode": 'inverse_rates',
        "etf": 'XLU',
        "leaders": ['NEE', 'DUK', 'SO', 'D', 'AEP', 'EXC', 'SRE'],
        "notes": 'Bond proxy; drops when yields rise.',
        "event_count": 8,
    },
    "auto_manufacturers": {
        "name": 'Auto Manufacturers',
        "mode": 'hybrid',
        "etf": 'CARZ',
        "leaders": ['TSLA', 'TM', 'GM', 'F', 'RIVN', 'LCID', 'STLA'],
        "notes": 'Dealer days supply; union negotiations.',
        "event_count": 8,
    },
    "luxury_goods": {
        "name": 'Luxury Goods',
        "mode": 'hybrid',
        "etf": 'XLY',
        "leaders": ['LVMUY', 'TPR', 'RL', 'CPRI', 'RACE', 'BIRK'],
        "notes": 'HNW wealth; travel retail flows.',
        "event_count": 8,
    },
    "hotels_resorts_cruise": {
        "name": 'Hotels & Cruise',
        "mode": 'hybrid',
        "etf": 'XLY',
        "leaders": ['MAR', 'HLT', 'H', 'CCL', 'RCL', 'NCLH', 'BKNG'],
        "notes": 'RevPAR; airline passenger volumes.',
        "event_count": 8,
    },
    "restaurants_food": {
        "name": 'Restaurants',
        "mode": 'hybrid',
        "etf": 'XLY',
        "leaders": ['MCD', 'SBUX', 'YUM', 'CMG', 'QSR', 'DRI', 'TXRH'],
        "notes": 'SSS vs commodity food inputs; minimum wage.',
        "event_count": 12,
    },
    "hypermarkets_discount": {
        "name": 'Hypermarkets & Discount',
        "mode": 'defensive',
        "etf": 'XRT',
        "leaders": ['WMT', 'COST', 'TGT', 'DG', 'DLTR', 'BJ'],
        "notes": 'Counter-cyclical; gas prices affect wallet share.',
        "event_count": 8,
    },
    "household_personal_products": {
        "name": 'Household Products',
        "mode": 'defensive',
        "etf": 'XLP',
        "leaders": ['PG', 'CL', 'KMB', 'CHD', 'CLX', 'EL', 'KVUE'],
        "notes": 'Volume vs price mix; recession resilient.',
        "event_count": 8,
    },
    "packaged_foods": {
        "name": 'Packaged Foods',
        "mode": 'defensive',
        "etf": 'XLP',
        "leaders": ['KO', 'PEP', 'GIS', 'K', 'HSY', 'MDLZ', 'KHC'],
        "notes": 'Food commodity inputs; GLP-1 headwind theme.',
        "event_count": 10,
    },
    "aerospace_defense": {
        "name": 'Aerospace & Defense',
        "mode": 'defensive',
        "etf": 'ITA',
        "leaders": ['RTX', 'LMT', 'NOC', 'GD', 'BA', 'LHX', 'TDG'],
        "notes": 'Government backlog; geopolitical escalations.',
        "event_count": 8,
    },
    "air_freight_logistics": {
        "name": 'Air Freight & Logistics',
        "mode": 'hybrid',
        "etf": 'IYT',
        "leaders": ['UPS', 'FDX', 'EXPD', 'CHRW', 'XPO', 'JBHT'],
        "notes": 'Early GDP indicator; fuel and tariffs hit all.',
        "event_count": 8,
    },
    "railroads": {
        "name": 'Railroads',
        "mode": 'hybrid',
        "etf": 'IYT',
        "leaders": ['UNP', 'CSX', 'NSC', 'CP', 'CNI'],
        "notes": 'Operating ratio; weekly carload data.',
        "event_count": 8,
    },
    "construction_machinery": {
        "name": 'Construction Machinery',
        "mode": 'hybrid',
        "etf": 'XLI',
        "leaders": ['CAT', 'DE', 'CNH', 'PCAR', 'OSK', 'URI'],
        "notes": 'Dealer destocking velocity; housing starts.',
        "event_count": 8,
    },
    "building_products": {
        "name": 'Building Products',
        "mode": 'hybrid',
        "etf": 'XLI',
        "leaders": ['SHW', 'MLM', 'VMC', 'BLDR', 'OC', 'TREX'],
        "notes": 'Housing starts and mortgage rates.',
        "event_count": 8,
    },
    "chemicals": {
        "name": 'Chemicals',
        "mode": 'hybrid',
        "etf": 'XLB',
        "leaders": ['LIN', 'APD', 'ECL', 'DD', 'DOW', 'LYB', 'CE'],
        "notes": 'Spread over nat gas; early cycle.',
        "event_count": 8,
    },
    "metals_mining": {
        "name": 'Metals & Mining',
        "mode": 'commodity',
        "etf": 'XME',
        "leaders": ['FCX', 'NEM', 'GOLD', 'RIO', 'BHP', 'VALE', 'AA'],
        "notes": 'Daily metal price moves dominate.',
        "event_count": 9,
    },
    "wireless_telecom": {
        "name": 'Wireless Telecom',
        "mode": 'inverse_rates',
        "etf": 'XLC',
        "leaders": ['TMUS', 'VZ', 'T', 'LUMN', 'USM'],
        "notes": 'Bond-proxy dividend; postpaid churn.',
        "event_count": 8,
    },
    "interactive_media": {
        "name": 'Interactive Media',
        "mode": 'follow_nasdaq',
        "etf": 'XLC',
        "leaders": ['META', 'GOOGL', 'GOOG', 'SNAP', 'PINS', 'RDDT'],
        "notes": 'ARPU/DAU; digital ad budget cycle.',
        "event_count": 8,
    },
    "entertainment_streaming": {
        "name": 'Entertainment & Streaming',
        "mode": 'hybrid',
        "etf": 'XLC',
        "leaders": ['NFLX', 'DIS', 'WBD', 'PARA', 'SPOT', 'LYV'],
        "notes": 'Content ROI; subscriber net adds.',
        "event_count": 8,
    },
    "environmental_waste": {
        "name": 'Environmental & Waste',
        "mode": 'defensive',
        "etf": 'XLI',
        "leaders": ['WM', 'RSG', 'WCN', 'CWST', 'CLH'],
        "notes": 'Pricing escalators pass diesel inflation.',
        "event_count": 8,
    },
    "apparel_retail": {
        "name": 'Apparel Retail',
        "mode": 'hybrid',
        "etf": 'XRT',
        "leaders": ['TJX', 'ROST', 'LULU', 'NKE', 'UAA', 'GAP', 'ANF'],
        "notes": 'GMROII; weather affects seasonal coats.',
        "event_count": 8,
    },
    "marine_shipping": {
        "name": 'Marine Shipping',
        "mode": 'commodity',
        "etf": 'BDRY',
        "leaders": ['ZIM', 'MATX', 'DAC', 'GSL', 'SBLK', 'GOGL'],
        "notes": 'Spot charter rates; canal bottlenecks.',
        "event_count": 8,
    },
    "independent_power_producers": {
        "name": 'Independent Power Producers',
        "mode": 'commodity',
        "etf": 'XLU',
        "leaders": ['VST', 'NRG', 'CEG', 'AES', 'CWEN'],
        "notes": 'Spark/dark spread; grid constraints.',
        "event_count": 8,
    },
    "commercial_services": {
        "name": 'Commercial Services',
        "mode": 'hybrid',
        "etf": 'XLI',
        "leaders": ['ADP', 'PayX', 'CTAS', 'UNF', 'ABM', 'BCO'],
        "notes": 'White-collar employment linkage.',
        "event_count": 8,
    },
    "distributors": {
        "name": 'Distributors',
        "mode": 'hybrid',
        "etf": 'XLI',
        "leaders": ['GWW', 'FAST', 'WSO', 'POOL', 'AIT', 'CNM'],
        "notes": 'Working capital cycle; supplier lead times.',
        "event_count": 8,
    },
}

HEADLINE_EVENT_RULES: dict[str, list[tuple[str, str]]] = {
    "biotech": [('phase 3 success', 'phase_3_success'), ('fda approval', 'fda_approval'), ('breakthrough therapy', 'breakthrough_therapy'), ('trial met primary', 'trial_met_primary'), ('orphan drug', 'orphan_drug'), ('positive data', 'positive_data'), ('complete response', 'complete_response'), ('clinical hold', 'clinical_hold'), ('trial failure', 'trial_failure'), ('fda rejection', 'fda_rejection'), ('safety concern', 'safety_concern'), ('offering', 'offering'), ('dilution', 'dilution'), ('phase 2 miss', 'phase_2_miss'), ('complete response letter', 'complete_response_letter'), ('trial', 'trial_move'), ('fda', 'fda_move'), ('phase', 'phase_move'), ('biomarker', 'biomarker_move'), ('fda approves', 'fda_approves'), ('topline positive', 'topline_positive'), ('accelerated approval', 'accelerated_approval'), ('clinical hold', 'clinical_hold'), ('trial halted', 'trial_halted')],
    "big_pharma": [('beats estimates', 'beats_estimates'), ('raises guidance', 'raises_guidance'), ('patent win', 'patent_win'), ('formulary inclusion', 'formulary_inclusion'), ('blockbuster', 'blockbuster'), ('patent cliff', 'patent_cliff'), ('generic entry', 'generic_entry'), ('medicare negotiation', 'medicare_negotiation'), ('fda warning letter', 'fda_warning_letter'), ('recall', 'recall'), ('prescription', 'prescription_move'), ('formulary', 'formulary_move'), ('patent', 'patent_move'), ('fda approval', 'fda_approval'), ('label expansion', 'label_expansion'), ('patent expiry', 'patent_expiry'), ('price cap', 'price_cap'), ('generic launch', 'generic_launch')],
    "medical_devices": [('procedure volume', 'procedure_volume'), ('hospital capex', 'hospital_capex'), ('robotics adoption', 'robotics_adoption'), ('guidance raise', 'guidance_raise'), ('hospital budget cut', 'hospital_budget_cut'), ('recall', 'recall'), ('reimbursement cut', 'reimbursement_cut'), ('elective delay', 'elective_delay'), ('surgery', 'surgery_move'), ('hospital', 'hospital_move'), ('implant', 'implant_move'), ('fda clearance', 'fda_clearance'), ('510k', '510k'), ('class 1 recall', 'class_1_recall'), ('warning letter', 'warning_letter')],
    "life_sciences_tools": [('backlog growth', 'backlog_growth'), ('biotech funding', 'biotech_funding'), ('instrument demand', 'instrument_demand'), ('academic grants', 'academic_grants'), ('biotech funding winter', 'biotech_funding_winter'), ('capex pause', 'capex_pause'), ('china weakness', 'china_weakness'), ('instrument', 'instrument_move'), ('sequencing', 'sequencing_move'), ('lab', 'lab_move'), ('record orders', 'record_orders'), ('backlog up', 'backlog_up'), ('guidance cut', 'guidance_cut'), ('funding drought', 'funding_drought')],
    "healthcare_providers": [('membership growth', 'membership_growth'), ('medical loss ratio beat', 'medical_loss_ratio_beat'), ('rate increase', 'rate_increase'), ('utilization stable', 'utilization_stable'), ('mlr miss', 'mlr_miss'), ('medicare cut', 'medicare_cut'), ('nurse wage inflation', 'nurse_wage_inflation'), ('utilization spike', 'utilization_spike'), ('medicare', 'medicare_move'), ('medicaid', 'medicaid_move'), ('mlr', 'mlr_move'), ('bed', 'bed_move'), ('cms rate', 'cms_rate'), ('star rating', 'star_rating'), ('reimbursement cut', 'reimbursement_cut'), ('mlr pressure', 'mlr_pressure')],
    "healthcare_technology": [('contract win', 'contract_win'), ('hospital go-live', 'hospital_go-live'), ('saas growth', 'saas_growth'), ('ARR beat', 'ARR_beat'), ('security breach', 'security_breach'), ('privacy fine', 'privacy_fine'), ('churn', 'churn'), ('telehealth cut', 'telehealth_cut'), ('telehealth', 'telehealth_move'), ('ehr', 'ehr_move'), ('hipaa', 'hipaa_move'), ('enterprise deal', 'enterprise_deal'), ('platform migration', 'platform_migration'), ('hipaa', 'hipaa'), ('data breach', 'data_breach'), (' outage', '_outage')],
    "residential_reits": [('rent growth', 'rent_growth'), ('occupancy up', 'occupancy_up'), ('concession down', 'concession_down'), ('rate cut', 'rate_cut'), ('rent decline', 'rent_decline'), ('supply surge', 'supply_surge'), ('rate hike', 'rate_hike'), ('concession increase', 'concession_increase'), ('rent', 'rent_move'), ('multifamily', 'multifamily_move'), ('apartment', 'apartment_move'), ('mortgage', 'mortgage_move'), ('rent reacceleration', 'rent_reacceleration'), ('fed pivot', 'fed_pivot'), ('yield spike', 'yield_spike'), ('housing starts surge', 'housing_starts_surge')],
    "commercial_office_reits": [('return to office', 'return_to_office'), ('lease signed', 'lease_signed'), ('occupancy stabil', 'occupancy_stabil'), ('wault extended', 'wault_extended'), ('default', 'default'), ('vacancy rise', 'vacancy_rise'), ('cre stress', 'cre_stress'), ('remote work', 'remote_work'), ('office', 'office_move'), ('wault', 'wault_move'), ('occupancy', 'occupancy_move'), ('anchor lease', 'anchor_lease'), ('occupancy beat', 'occupancy_beat'), ('tenant bankruptcy', 'tenant_bankruptcy'), ('cre loan', 'cre_loan')],
    "retail_reits": [('foot traffic', 'foot_traffic'), ('tenant sales', 'tenant_sales'), ('re-leasing spread', 're-leasing_spread'), ('occupancy cost ratio ok', 'occupancy_cost_ratio_ok'), ('anchor closure', 'anchor_closure'), ('bankruptcy', 'bankruptcy'), ('retail apocalypse', 'retail_apocalypse'), ('rent cut', 'rent_cut'), ('mall', 'mall_move'), ('foot traffic', 'foot traffic_move'), ('tenant', 'tenant_move'), ('tenant sales beat', 'tenant_sales_beat'), ('re-leasing positive', 're-leasing_positive'), ('chapter 11', 'chapter_11'), ('store closure wave', 'store_closure_wave')],
    "industrial_logistics_reits": [('rent reversion', 'rent_reversion'), ('e-commerce demand', 'e-commerce_demand'), ('supply chain', 'supply_chain'), ('development yield', 'development_yield'), ('amazon slowdown', 'amazon_slowdown'), ('oversupply', 'oversupply'), ('cap rate expansion', 'cap_rate_expansion'), ('warehouse', 'warehouse_move'), ('fulfillment', 'fulfillment_move'), ('storage', 'storage_move'), ('record leasing', 'record_leasing'), ('rent spread', 'rent_spread'), ('warehouse glut', 'warehouse_glut'), ('demand softening', 'demand_softening')],
    "specialized_reits": [('ai demand', 'ai_demand'), ('cloud capex', 'cloud_capex'), ('tower lease', 'tower_lease'), ('power capacity', 'power_capacity'), ('rate spike', 'rate_spike'), ('hyperscaler pause', 'hyperscaler_pause'), ('interest expense', 'interest_expense'), ('data center', 'data center_move'), ('tower', 'tower_move'), ('ai server', 'ai server_move'), ('hyperscaler deal', 'hyperscaler_deal'), ('ai server demand', 'ai_server_demand'), ('capex cut', 'capex_cut'), ('yield jump', 'yield_jump')],
    "semiconductors": [('ai demand', 'ai_demand'), ('book-to-bill', 'book-to-bill'), ('supply tight', 'supply_tight'), ('export license', 'export_license'), ('data center', 'data_center'), ('inventory glut', 'inventory_glut'), ('export ban', 'export_ban'), ('cycle downturn', 'cycle_downturn'), ('book-to-bill below 1', 'book-to-bill_below_1'), ('wafer', 'wafer_move'), ('chip', 'chip_move'), ('foundry', 'foundry_move'), ('hbm', 'hbm_move'), ('beat on ai', 'beat_on_ai'), ('guidance raise', 'guidance_raise'), ('tsmc capacity', 'tsmc_capacity'), ('export restriction', 'export_restriction'), ('inventory days high', 'inventory_days_high')],
    "semi_equipment": [('fab build', 'fab_build'), ('capex raise', 'capex_raise'), ('chips act', 'chips_act'), ('order backlog', 'order_backlog'), ('fab pause', 'fab_pause'), ('capex cut', 'capex_cut'), ('order cancel', 'order_cancel'), ('lithography', 'lithography_move'), ('fab', 'fab_move'), ('capex', 'capex_move'), ('tsmc capex', 'tsmc_capex'), ('intel fab', 'intel_fab'), ('push out', 'push_out'), ('order push', 'order_push')],
    "application_software": [('nrr above 110', 'nrr_above_110'), ('billings beat', 'billings_beat'), ('seat expansion', 'seat_expansion'), ('ai copilot', 'ai_copilot'), ('nrr decline', 'nrr_decline'), ('churn', 'churn'), ('budget freeze', 'budget_freeze'), ('multiple compression', 'multiple_compression'), ('saas', 'saas_move'), ('subscription', 'subscription_move'), ('seat', 'seat_move'), ('raise nrr', 'raise_nrr'), ('large deal', 'large_deal'), ('layoffs', 'layoffs'), ('capex cut it', 'capex_cut_it')],
    "systems_software": [('arr growth', 'arr_growth'), ('ransomware spike', 'ransomware_spike'), ('cloud migration', 'cloud_migration'), ('platform stickiness', 'platform_stickiness'), ('breach at peer', 'breach_at_peer'), ('budget defer', 'budget_defer'), ('open source threat', 'open_source_threat'), ('cyber', 'cyber_move'), ('cloud', 'cloud_move'), ('database', 'database_move'), ('major breach industry', 'major_breach_industry'), ('fed mandate', 'fed_mandate'), ('zero day', 'zero_day'), ('outage', 'outage')],
    "tech_hardware": [('upgrade cycle', 'upgrade_cycle'), ('iphone demand', 'iphone_demand'), ('pc recovery', 'pc_recovery'), ('holiday strong', 'holiday_strong'), ('inventory channel', 'inventory_channel'), ('demand miss', 'demand_miss'), ('component cost', 'component_cost'), ('china weak', 'china_weak'), ('iphone', 'iphone_move'), ('pc', 'pc_move'), ('smartphone', 'smartphone_move'), ('foxconn', 'foxconn_move'), ('product launch', 'product_launch'), ('sell through beat', 'sell_through_beat'), ('cut production', 'cut_production'), ('demand warning', 'demand_warning')],
    "diversified_banks": [('nim expansion', 'nim_expansion'), ('net interest income', 'net_interest_income'), ('stress test pass', 'stress_test_pass'), ('loan growth', 'loan_growth'), ('credit loss', 'credit_loss'), ('deposit flight', 'deposit_flight'), ('regulatory fine', 'regulatory_fine'), ('inversion', 'inversion'), ('nim', 'nim_move'), ('deposit', 'deposit_move'), ('loan', 'loan_move'), ('fed hike', 'fed_hike'), ('stress test clear', 'stress_test_clear'), ('svb', 'svb'), ('deposit outflow', 'deposit_outflow'), ('cecl spike', 'cecl_spike')],
    "regional_banks": [('deposit stable', 'deposit_stable'), ('cre manageable', 'cre_manageable'), ('buyback', 'buyback'), ('cre exposure', 'cre_exposure'), ('unrealized losses', 'unrealized_losses'), ('deposit beta spike', 'deposit_beta_spike'), ('run risk', 'run_risk'), ('cre', 'cre_move'), ('deposit beta', 'deposit beta_move'), ('unrealized', 'unrealized_move'), ('deposit inflows', 'deposit_inflows'), ('fdic calm', 'fdic_calm'), ('regional bank', 'regional_bank'), ('deposit run', 'deposit_run'), ('cre default', 'cre_default')],
    "property_casualty_insurance": [('combined ratio beat', 'combined_ratio_beat'), ('rate increase approved', 'rate_increase_approved'), ('pricing firm', 'pricing_firm'), ('cat loss', 'cat_loss'), ('hurricane', 'hurricane'), ('wildfire', 'wildfire'), ('combined ratio miss', 'combined_ratio_miss'), ('hurricane', 'hurricane_move'), ('wildfire', 'wildfire_move'), ('combined ratio', 'combined ratio_move'), ('rate approval', 'rate_approval'), ('pricing hard', 'pricing_hard'), ('cat event', 'cat_event'), ('storm landfall', 'storm_landfall')],
    "life_health_insurance": [('investment income', 'investment_income'), ('long bond yield', 'long_bond_yield'), ('mortality stable', 'mortality_stable'), ('longevity', 'longevity'), ('rate cut', 'rate_cut'), ('alternative asset markdown', 'alternative_asset_markdown'), ('annuity', 'annuity_move'), ('mortality', 'mortality_move'), ('long bond', 'long bond_move'), ('y', 'y'), ('i', 'i'), ('e', 'e'), ('l', 'l'), ('d', 'd'), (' ', '_'), ('c', 'c'), ('u', 'u'), ('r', 'r'), ('v', 'v'), ('e', 'e'), (' ', '_'), ('s', 's'), ('t', 't'), ('e', 'e')],
    "financial_data_exchanges": [('trading volume', 'trading_volume'), ('vix elevated', 'vix_elevated'), ('aum growth', 'aum_growth'), ('data subscription', 'data_subscription'), ('volume drought', 'volume_drought'), ('fee pressure', 'fee_pressure'), ('crypto winter', 'crypto_winter'), ('volume', 'volume_move'), ('vix', 'vix_move'), ('aum', 'aum_move'), ('vol spike', 'vol_spike'), ('record volume', 'record_volume'), ('trading slowdown', 'trading_slowdown'), ('fee cut', 'fee_cut')],
    "consumer_finance": [('spend growth', 'spend_growth'), ('delinquency stable', 'delinquency_stable'), ('loan growth', 'loan_growth'), ('charge-off rise', 'charge-off_rise'), ('delinquency spike', 'delinquency_spike'), ('rate cap', 'rate_cap'), ('recession fear', 'recession_fear'), ('delinquency', 'delinquency_move'), ('charge-off', 'charge-off_move'), ('revolving', 'revolving_move'), ('spend data strong', 'spend_data_strong'), ('naco stable', 'naco_stable'), ('delinquency', 'delinquency'), ('charge-off', 'charge-off'), ('bnpl stress', 'bnpl_stress')],
    "integrated_oil_gas": [('opec cut', 'opec_cut'), ('crude rally', 'crude_rally'), ('refining margin', 'refining_margin'), ('buyback', 'buyback'), ('demand destruction', 'demand_destruction'), ('opec increase', 'opec_increase'), ('windfall tax', 'windfall_tax'), ('wti', 'wti_move'), ('brent', 'brent_move'), ('crude', 'crude_move'), ('opec', 'opec_move'), ('opec+', 'opec+'), ('supply cut', 'supply_cut'), ('demand concern', 'demand_concern'), ('inventory build', 'inventory_build')],
    "oil_gas_ep": [('production beat', 'production_beat'), ('hedge gain', 'hedge_gain'), ('rig count', 'rig_count'), ('permit', 'permit'), ('gas glut', 'gas_glut'), ('basis blowout', 'basis_blowout'), ('decline curve', 'decline_curve'), ('natural gas', 'natural gas_move'), ('wti', 'wti_move'), ('rig', 'rig_move'), ('eia', 'eia_move'), ('eia draw', 'eia_draw'), ('rig up', 'rig_up'), ('eia build', 'eia_build'), ('gas price collapse', 'gas_price_collapse')],
    "oil_gas_equipment": [('rig count', 'rig_count'), ('international capex', 'international_capex'), ('dayrate', 'dayrate'), ('capex cut', 'capex_cut'), ('utilization fall', 'utilization_fall'), ('frac spread narrow', 'frac_spread_narrow'), ('rig', 'rig_move'), ('dayrate', 'dayrate_move'), ('frac', 'frac_move'), ('rig count up', 'rig_count_up'), ('dayrate hike', 'dayrate_hike'), ('capex guide down', 'capex_guide_down'), ('stacked frac', 'stacked_frac')],
    "renewable_energy": [('ira credit', 'ira_credit'), ('solar demand', 'solar_demand'), ('lcoe decline', 'lcoe_decline'), ('policy support', 'policy_support'), ('rate hike', 'rate_hike'), ('subsidy cut', 'subsidy_cut'), ('module glut', 'module_glut'), ('interconnection delay', 'interconnection_delay'), ('solar', 'solar_move'), ('wind', 'wind_move'), ('lcoe', 'lcoe_move'), ('ira', 'ira_move'), ('tax credit extend', 'tax_credit_extend'), ('solar install beat', 'solar_install_beat'), ('subsidy rollback', 'subsidy_rollback'), ('module oversupply', 'module_oversupply')],
    "electric_gas_utilities": [('allowed roe', 'allowed_roe'), ('rate case win', 'rate_case_win'), ('load growth', 'load_growth'), ('data center power', 'data_center_power'), ('rate case loss', 'rate_case_loss'), ('wildfire liability', 'wildfire_liability'), ('yield competition', 'yield_competition'), ('utility', 'utility_move'), ('grid', 'grid_move'), ('allowed roe', 'allowed roe_move'), ('rate case approved', 'rate_case_approved'), ('load forecast up', 'load_forecast_up'), ('wildfire', 'wildfire'), ('rate denial', 'rate_denial')],
    "auto_manufacturers": [('delivery beat', 'delivery_beat'), ('ev demand', 'ev_demand'), ('inventory days low', 'inventory_days_low'), ('incentive cut', 'incentive_cut'), ('strike', 'strike'), ('inventory glut', 'inventory_glut'), ('price war', 'price_war'), ('recall', 'recall'), ('steel', 'steel_move'), ('lithium', 'lithium_move'), ('battery', 'battery_move'), ('auto loan', 'auto loan_move'), ('delivery record', 'delivery_record'), ('ev subsidy', 'ev_subsidy'), ('uaw strike', 'uaw_strike'), ('recall', 'recall'), ('price cut', 'price_cut')],
    "luxury_goods": [('china reopen', 'china_reopen'), ('pricing power', 'pricing_power'), ('tourist spend', 'tourist_spend'), ('hnw growth', 'hnw_growth'), ('china slowdown', 'china_slowdown'), ('asp reduction', 'asp_reduction'), ('counterfeit', 'counterfeit'), ('wealth shock', 'wealth_shock'), ('luxury', 'luxury_move'), ('tourist', 'tourist_move'), ('yuan', 'yuan_move'), ('china sales beat', 'china_sales_beat'), ('pricing increase', 'pricing_increase'), ('china weak', 'china_weak'), ('discounting', 'discounting')],
    "hotels_resorts_cruise": [('revpar up', 'revpar_up'), ('booking strong', 'booking_strong'), ('load factor', 'load_factor'), ('business travel', 'business_travel'), ('outbreak', 'outbreak'), ('fuel surcharge', 'fuel_surcharge'), ('geopolitical travel', 'geopolitical_travel'), ('revpar miss', 'revpar_miss'), ('revpar', 'revpar_move'), ('occupancy', 'occupancy_move'), ('cruise', 'cruise_move'), ('jet fuel', 'jet fuel_move'), ('revpar beat', 'revpar_beat'), ('booking record', 'booking_record'), ('travel warning', 'travel_warning'), ('outbreak', 'outbreak'), ('port closure', 'port_closure')],
    "restaurants_food": [('same store sales', 'same_store_sales'), ('digital mix', 'digital_mix'), ('menu price', 'menu_price'), ('traffic up', 'traffic_up'), ('food cost inflation', 'food_cost_inflation'), ('wage inflation', 'wage_inflation'), ('traffic down', 'traffic_down'), ('e.coli', 'e.coli'), ('beef', 'beef_move'), ('wheat', 'wheat_move'), ('dairy', 'dairy_move'), ('coffee', 'coffee_move'), ('corn', 'corn_move'), ('food cost', 'food cost_move'), ('sss beat', 'sss_beat'), ('menu innovation', 'menu_innovation'), ('food safety', 'food_safety'), ('minimum wage', 'minimum_wage'), ('beef price', 'beef_price')],
    "hypermarkets_discount": [('traffic up', 'traffic_up'), ('market share gain', 'market_share_gain'), ('inventory turn', 'inventory_turn'), ('gas savings', 'gas_savings'), ('shrink', 'shrink'), ('theft', 'theft'), ('margin pressure', 'margin_pressure'), ('inventory glut', 'inventory_glut'), ('gasoline', 'gasoline_move'), ('consumer', 'consumer_move'), ('shrink', 'shrink_move'), ('holiday beat', 'holiday_beat'), ('traffic surge', 'traffic_surge'), ('guidance cut', 'guidance_cut'), ('inventory markdown', 'inventory_markdown')],
    "household_personal_products": [('pricing power', 'pricing_power'), ('volume stable', 'volume_stable'), ('premium mix', 'premium_mix'), ('private label share', 'private_label_share'), ('input cost', 'input_cost'), ('china weak', 'china_weak'), ('pulp', 'pulp_move'), ('chemical', 'chemical_move'), ('soap', 'soap_move'), ('p', 'p'), ('r', 'r'), ('i', 'i'), ('c', 'c'), ('e', 'e'), (' ', '_'), ('i', 'i'), ('n', 'n'), ('c', 'c'), ('r', 'r'), ('e', 'e'), ('a', 'a'), ('s', 's'), ('e', 'e'), (' ', '_')],
    "packaged_foods": [('pricing', 'pricing'), ('volume return', 'volume_return'), ('snacking trend', 'snacking_trend'), ('distribution gain', 'distribution_gain'), ('glut', 'glut'), ('grain cost', 'grain_cost'), ('trade down private label', 'trade_down_private_label'), ('obesity drug', 'obesity_drug'), ('corn', 'corn_move'), ('wheat', 'wheat_move'), ('cocoa', 'cocoa_move'), ('sugar', 'sugar_move'), ('beef', 'beef_move'), ('grain', 'grain_move'), ('pricing hold', 'pricing_hold'), ('volume positive', 'volume_positive'), ('corn spike', 'corn_spike'), ('glucagon', 'glucagon'), ('weight loss headwind', 'weight_loss_headwind')],
    "aerospace_defense": [('defense budget', 'defense_budget'), ('backlog record', 'backlog_record'), ('flight hours', 'flight_hours'), ('contract award', 'contract_award'), ('program delay', 'program_delay'), ('grounding', 'grounding'), ('budget cut', 'budget_cut'), ('strike', 'strike'), ('defense', 'defense_move'), ('backlog', 'backlog_move'), ('faa', 'faa_move'), ('ndaa', 'ndaa'), ('contract win', 'contract_win'), ('geopolitical', 'geopolitical'), ('grounding', 'grounding'), ('quality issue', 'quality_issue')],
    "air_freight_logistics": [('parcel volume', 'parcel_volume'), ('yield up', 'yield_up'), ('e-commerce ship', 'e-commerce_ship'), ('tender reject', 'tender_reject'), ('volume miss', 'volume_miss'), ('jet fuel', 'jet_fuel'), ('trade tariff', 'trade_tariff'), ('capacity add', 'capacity_add'), ('jet fuel', 'jet fuel_move'), ('diesel', 'diesel_move'), ('parcel', 'parcel_move'), ('freight', 'freight_move'), ('peak season strong', 'peak_season_strong'), ('yield beat', 'yield_beat'), ('trade war', 'trade_war'), ('fuel surcharge', 'fuel_surcharge'), ('volume guide down', 'volume_guide_down')],
    "railroads": [('carload up', 'carload_up'), ('operating ratio improve', 'operating_ratio_improve'), ('pricing', 'pricing'), ('intermodal', 'intermodal'), ('coal decline', 'coal_decline'), ('strike', 'strike'), ('weather', 'weather'), ('regulatory', 'regulatory'), ('coal', 'coal_move'), ('grain', 'grain_move'), ('intermodal', 'intermodal_move'), ('carload', 'carload_move'), ('carload beat', 'carload_beat'), ('precision scheduled railroading', 'precision_scheduled_railroad'), ('derailment', 'derailment'), ('strike vote', 'strike_vote')],
    "construction_machinery": [('dealer inventory down', 'dealer_inventory_down'), ('infrastructure bill', 'infrastructure_bill'), ('mining capex', 'mining_capex'), ('backlog', 'backlog'), ('dealer destock', 'dealer_destock'), ('china weak', 'china_weak'), ('farm income down', 'farm_income_down'), ('steel', 'steel_move'), ('copper', 'copper_move'), ('infrastructure', 'infrastructure_move'), ('infrastructure', 'infrastructure'), ('dealer survey up', 'dealer_survey_up'), ('dealer inventory high', 'dealer_inventory_high'), ('china demand', 'china_demand')],
    "building_products": [('housing starts', 'housing_starts'), ('repair remodel', 'repair_remodel'), ('pricing', 'pricing'), ('capacity util', 'capacity_util'), ('mortgage rate spike', 'mortgage_rate_spike'), ('housing slowdown', 'housing_slowdown'), ('input cost', 'input_cost'), ('lumber', 'lumber_move'), ('cement', 'cement_move'), ('housing starts', 'housing starts_move'), ('mortgage', 'mortgage_move'), ('permits up', 'permits_up'), ('housing starts beat', 'housing_starts_beat'), ('mortgage rate', 'mortgage_rate'), ('housing miss', 'housing_miss')],
    "chemicals": [('spread widen', 'spread_widen'), ('volume up', 'volume_up'), ('auto build', 'auto_build'), ('crop acreage', 'crop_acreage'), ('gas feedstock spike', 'gas_feedstock_spike'), ('destock', 'destock'), ('china demand', 'china_demand'), ('natural gas', 'natural gas_move'), ('ethylene', 'ethylene_move'), ('fertilizer', 'fertilizer_move'), ('potash', 'potash_move'), ('spread expansion', 'spread_expansion'), ('volume beat', 'volume_beat'), ('destocking', 'destocking'), ('natural gas feed', 'natural_gas_feed')],
    "metals_mining": [('copper squeeze', 'copper_squeeze'), ('china stimulus', 'china_stimulus'), ('gold safe haven', 'gold_safe_haven'), ('lme draw', 'lme_draw'), ('china property', 'china_property'), ('dollar strong', 'dollar_strong'), ('inventory build', 'inventory_build'), ('copper', 'copper_move'), ('gold', 'gold_move'), ('iron ore', 'iron ore_move'), ('lme', 'lme_move'), ('steel', 'steel_move'), ('china stimulus', 'china_stimulus'), ('lme cancel', 'lme_cancel'), ('china weak', 'china_weak'), ('inventory surge', 'inventory_surge')],
    "wireless_telecom": [('churn low', 'churn_low'), ('arpu up', 'arpu_up'), ('fiber build', 'fiber_build'), ('dividend safe', 'dividend_safe'), ('price war', 'price_war'), ('churn spike', 'churn_spike'), ('capex overhang', 'capex_overhang'), ('yield competition', 'yield_competition'), ('spectrum', 'spectrum_move'), ('churn', 'churn_move'), ('arpu', 'arpu_move'), ('postpaid net add', 'postpaid_net_add'), ('dividend raise', 'dividend_raise'), ('price cut', 'price_cut'), ('churn warning', 'churn_warning')],
    "interactive_media": [('ad spend', 'ad_spend'), ('dau growth', 'dau_growth'), ('reels monetization', 'reels_monetization'), ('ai search', 'ai_search'), ('ad recession', 'ad_recession'), ('att opt out', 'att_opt_out'), ('antitrust', 'antitrust'), ('tiktok competition', 'tiktok_competition'), ('advertising', 'advertising_move'), ('pixel', 'pixel_move'), ('dau', 'dau_move'), ('ad beat', 'ad_beat'), ('engagement record', 'engagement_record'), ('antitrust', 'antitrust'), ('ad slowdown', 'ad_slowdown'), ('privacy', 'privacy')],
    "entertainment_streaming": [('subscriber add', 'subscriber_add'), ('content hit', 'content_hit'), ('pricing tier', 'pricing_tier'), ('box office', 'box_office'), ('churn', 'churn'), ('content flop', 'content_flop'), ('strike', 'strike'), ('cord cutting margin', 'cord_cutting_margin'), ('streaming', 'streaming_move'), ('box office', 'box office_move'), ('subscriber', 'subscriber_move'), ('subscriber beat', 'subscriber_beat'), ('box office record', 'box_office_record'), ('writers strike', 'writers_strike'), ('sub miss', 'sub_miss'), ('content write down', 'content_write_down')],
    "environmental_waste": [('pricing escalator', 'pricing_escalator'), ('volume tonnage', 'volume_tonnage'), ('municipal contract', 'municipal_contract'), ('diesel cost', 'diesel_cost'), ('volume soft', 'volume_soft'), ('recycling price', 'recycling_price'), ('diesel', 'diesel_move'), ('landfill', 'landfill_move'), ('tonnage', 'tonnage_move'), ('price increase', 'price_increase'), ('contract win', 'contract_win'), ('fuel surcharge lag', 'fuel_surcharge_lag'), ('volume miss', 'volume_miss')],
    "apparel_retail": [('comp beat', 'comp_beat'), ('inventory clean', 'inventory_clean'), ('brand heat', 'brand_heat'), ('china reopen', 'china_reopen'), ('warm winter', 'warm_winter'), ('inventory glut', 'inventory_glut'), ('promotional', 'promotional'), ('supply delay', 'supply_delay'), ('cotton', 'cotton_move'), ('freight', 'freight_move'), ('apparel', 'apparel_move'), ('comp positive', 'comp_positive'), ('margin beat', 'margin_beat'), ('inventory up', 'inventory_up'), ('weather miss', 'weather_miss')],
    "marine_shipping": [('baltic dry up', 'baltic_dry_up'), ('spot rate spike', 'spot_rate_spike'), ('canal congestion', 'canal_congestion'), ('tanker tight', 'tanker_tight'), ('rate collapse', 'rate_collapse'), ('new supply', 'new_supply'), ('trade slowdown', 'trade_slowdown'), ('baltic', 'baltic_move'), ('freight rate', 'freight rate_move'), ('tanker', 'tanker_move'), ('container', 'container_move'), ('bdi surge', 'bdi_surge'), ('canal delay', 'canal_delay'), ('rate crash', 'rate_crash'), ('demurrage', 'demurrage')],
    "independent_power_producers": [('spark spread widen', 'spark_spread_widen'), ('heat wave', 'heat_wave'), ('capacity tight', 'capacity_tight'), ('data center power', 'data_center_power'), ('power price collapse', 'power_price_collapse'), ('renewable cannibalization', 'renewable_cannibalization'), ('regulatory', 'regulatory'), ('power price', 'power price_move'), ('spark spread', 'spark spread_move'), ('heat', 'heat_move'), ('heat dome', 'heat_dome'), ('power price spike', 'power_price_spike'), ('power price negative', 'power_price_negative'), ('regulatory cap', 'regulatory_cap')],
    "commercial_services": [('white collar hiring', 'white_collar_hiring'), ('contract renewal', 'contract_renewal'), ('cross sell', 'cross_sell'), ('hiring freeze', 'hiring_freeze'), ('office vacancy', 'office_vacancy'), ('wage inflation', 'wage_inflation'), ('employment', 'employment_move'), ('office', 'office_move'), ('staffing', 'staffing_move'), ('jobs report strong', 'jobs_report_strong'), ('contract win', 'contract_win'), ('layoffs', 'layoffs'), ('office empty', 'office_empty')],
    "distributors": [('volume growth', 'volume_growth'), ('pricing pass', 'pricing_pass'), ('inventory turn', 'inventory_turn'), ('digital share', 'digital_share'), ('destock', 'destock'), ('freight cost', 'freight_cost'), ('customer inventory cut', 'customer_inventory_cut'), ('freight', 'freight_move'), ('inventory', 'inventory_move'), ('working capital', 'working capital_move'), ('daily sales up', 'daily_sales_up'), ('share gain', 'share_gain'), ('customer destock', 'customer_destock'), ('margin squeeze', 'margin_squeeze')],
}
