"""Auto-generated name/sector/suffix lexicon for industry classification."""

from __future__ import annotations

from analytics.industries.base import ClassificationResult
from analytics.industries.registry import get_handler

SECTOR_DEFAULTS: dict[str, str] = {
    'technology': 'application_software',
    'healthcare': 'healthcare_providers',
    'financial services': 'diversified_banks',
    'financial': 'diversified_banks',
    'energy': 'oil_gas_ep',
    'utilities': 'electric_gas_utilities',
    'consumer cyclical': 'apparel_retail',
    'consumer defensive': 'packaged_foods',
    'industrials': 'commercial_services',
    'basic materials': 'metals_mining',
    'communication services': 'interactive_media',
    'real estate': 'specialized_reits',
}

SYMBOL_SUFFIX: dict[str, str] = {
    'BIO': 'biotech',
    'PHM': 'big_pharma',
    'RX': 'big_pharma',
    'BANK': 'regional_banks',
    'REIT': 'specialized_reits',
    'OIL': 'oil_gas_ep',
    'GAS': 'oil_gas_ep',
    'TECH': 'application_software',
    'SOFT': 'application_software',
    'CHIP': 'semiconductors',
    'SEMI': 'semiconductors',
    'AIR': 'aerospace_defense',
    'SHIP': 'marine_shipping',
    'RAIL': 'railroads',
    'MIN': 'metals_mining',
    'GOLD': 'metals_mining',
    'SILV': 'metals_mining',
    'COAL': 'metals_mining',
    'SOLAR': 'renewable_energy',
    'WIND': 'renewable_energy',
    'HOTEL': 'hotels_resorts_cruise',
    'FOOD': 'packaged_foods',
    'REST': 'restaurants_food',
    'INS': 'life_health_insurance',
    'INSU': 'property_casualty_insurance',
    'MED': 'medical_devices',
    'HOSP': 'healthcare_providers',
    'LAB': 'life_sciences_tools',
    'DRUG': 'big_pharma',
    'PHAR': 'big_pharma',
    'GENE': 'biotech',
    'CELL': 'biotech',
    'DATA': 'financial_data_exchanges',
    'PAY': 'consumer_finance',
    'FIN': 'consumer_finance',
    'MORT': 'residential_reits',
    'APT': 'residential_reits',
    'LOG': 'air_freight_logistics',
    'TRUK': 'air_freight_logistics',
    'AUTO': 'auto_manufacturers',
    'EV': 'auto_manufacturers',
    'UTIL': 'electric_gas_utilities',
    'PWR': 'independent_power_producers',
    'WASTE': 'environmental_waste',
    'WAST': 'environmental_waste',
    'CHEM': 'chemicals',
    'STEEL': 'metals_mining',
    'COPPER': 'metals_mining',
    'LITH': 'metals_mining',
    'LITHIUM': 'metals_mining',
    'URAN': 'metals_mining',
    'NUCL': 'independent_power_producers',
    'GAME': 'interactive_media',
    'MEDIA': 'entertainment_streaming',
    'STREAM': 'entertainment_streaming',
    'TELE': 'wireless_telecom',
    'TEL': 'wireless_telecom',
    'FIBER': 'wireless_telecom',
    '5G': 'wireless_telecom',
    'CLOUD': 'application_software',
    'SAAS': 'application_software',
    'AI': 'application_software',
    'ML': 'application_software',
    'CYBR': 'systems_software',
    'SEC': 'systems_software',
    'DEF': 'aerospace_defense',
    'ARM': 'aerospace_defense',
    'SPACE': 'aerospace_defense',
    'SAT': 'wireless_telecom',
    'CRUISE': 'hotels_resorts_cruise',
    'RESORT': 'hotels_resorts_cruise',
    'LUX': 'luxury_goods',
    'JEWEL': 'luxury_goods',
    'APP': 'apparel_retail',
    'WEAR': 'apparel_retail',
    'SHOE': 'apparel_retail',
    'FOOT': 'apparel_retail',
    'MALL': 'retail_reits',
    'SHOP': 'retail_reits',
    'WARE': 'industrial_logistics_reits',
    'STOR': 'industrial_logistics_reits',
    'DIST': 'distributors',
    'WHOLE': 'distributors',
    'PACK': 'packaged_foods',
    'SNACK': 'packaged_foods',
    'BEV': 'packaged_foods',
    'BREW': 'packaged_foods',
    'COFF': 'restaurants_food',
    'PIZZ': 'restaurants_food',
    'BURG': 'restaurants_food',
    'CAFE': 'restaurants_food',
    'DINE': 'restaurants_food',
    'EDU': 'commercial_services',
    'STAFF': 'commercial_services',
    'SERV': 'commercial_services',
    'CONS': 'commercial_services',
    'AD': 'interactive_media',
    'ADS': 'interactive_media',
    'NET': 'interactive_media',
    'WEB': 'interactive_media',
    'SOCIAL': 'interactive_media',
    'META': 'interactive_media',
    'VID': 'entertainment_streaming',
    'FILM': 'entertainment_streaming',
    'STUDIO': 'entertainment_streaming',
    'MUSIC': 'entertainment_streaming',
    'EQUIP': 'construction_machinery',
    'MACH': 'construction_machinery',
    'CAT': 'construction_machinery',
    'DOZ': 'construction_machinery',
    'BLDG': 'building_products',
    'ROOF': 'building_products',
    'HVAC': 'building_products',
    'PIPE': 'building_products',
    'PLUMB': 'building_products',
    'LUMBER': 'building_products',
    'TIMBER': 'building_products',
    'FARM': 'packaged_foods',
    'AGRI': 'packaged_foods',
    'CROP': 'packaged_foods',
    'SEED': 'packaged_foods',
    'FERT': 'chemicals',
    'PEST': 'chemicals',
    'POLY': 'chemicals',
    'PLAST': 'chemicals',
    'RESIN': 'chemicals',
    'PAINT': 'chemicals',
    'COAT': 'chemicals',
    'ADH': 'chemicals',
    'REFIN': 'integrated_oil_gas',
    'PIPELINE': 'integrated_oil_gas',
    'MIDSTREAM': 'integrated_oil_gas',
    'DRILL': 'oil_gas_equipment',
    'RIG': 'oil_gas_equipment',
    'FRAC': 'oil_gas_equipment',
    'SHALE': 'oil_gas_ep',
    'LNG': 'integrated_oil_gas',
    'PROP': 'oil_gas_ep',
    'EXPL': 'oil_gas_ep',
    'EXCHANGE': 'financial_data_exchanges',
    'BROKER': 'financial_data_exchanges',
    'TRADE': 'financial_data_exchanges',
    'CLEAR': 'financial_data_exchanges',
    'CARD': 'consumer_finance',
    'LEND': 'consumer_finance',
    'LOAN': 'consumer_finance',
    'CRED': 'consumer_finance',
    'MORTG': 'consumer_finance',
    'LEASE': 'consumer_finance',
    'RENT': 'residential_reits',
    'APTMT': 'residential_reits',
    'MULTI': 'residential_reits',
    'OFFICE': 'commercial_office_reits',
    'TOWER': 'commercial_office_reits',
    'INDUSTRIAL': 'industrial_logistics_reits',
    'DC': 'specialized_reits',
    'DATAC': 'specialized_reits',
    'HEALTH': 'healthcare_providers',
    'CLINIC': 'healthcare_providers',
    'NURS': 'healthcare_providers',
    'DIAL': 'healthcare_providers',
    'THERA': 'biotech',
    'ONCO': 'biotech',
    'IMMUN': 'biotech',
    'VACC': 'biotech',
    'MRNA': 'biotech',
    'RNA': 'biotech',
    'DNA': 'biotech',
    'GENOM': 'biotech',
    'PROTE': 'biotech',
    'ANTIB': 'big_pharma',
    'VAX': 'big_pharma',
    'DIAG': 'life_sciences_tools',
    'ASSAY': 'life_sciences_tools',
    'REAG': 'life_sciences_tools',
    'SCOPE': 'medical_devices',
    'IMPL': 'medical_devices',
    'ORTHO': 'medical_devices',
    'CARDIO': 'medical_devices',
    'DIAB': 'medical_devices',
    'PUMP': 'medical_devices',
    'ROBOT': 'medical_devices',
    'SURG': 'medical_devices',
    'EHR': 'healthcare_technology',
    'TELEHEALTH': 'healthcare_technology',
    'PHARM': 'big_pharma',
    'RXCO': 'big_pharma',
    'GENERIC': 'big_pharma',
    'BIOSIM': 'big_pharma',
}

NAME_RULES: dict[str, list[tuple[str, float]]] = {
    "biotech": [
        ('biotechnology', 0.72),
        ('biotech', 0.72),
        ('genomic', 0.72),
        ('gene editing', 0.72),
        ('cell therapy', 0.72),
        ('immuno-oncology', 0.72),
        ('trial', 0.65),
        ('fda', 0.65),
        ('phase', 0.65),
        ('biomarker', 0.65),
        ('phase 3 success', 0.58),
        ('fda approval', 0.58),
        ('breakthrough therapy', 0.58),
        ('trial met primary', 0.58),
        ('orphan drug', 0.58),
        ('positive data', 0.58),
        ('clinical hold', 0.55),
        ('trial failure', 0.55),
        ('fda rejection', 0.55),
        ('safety concern', 0.55),
        ('biotechnology', 0.6),
    ],
    "big_pharma": [
        ('drug manufacturers', 0.72),
        ('pharmaceutical', 0.72),
        ('big pharma', 0.72),
        ('prescription', 0.65),
        ('formulary', 0.65),
        ('patent', 0.65),
        ('beats estimates', 0.58),
        ('raises guidance', 0.58),
        ('patent win', 0.58),
        ('formulary inclusion', 0.58),
        ('blockbuster', 0.58),
        ('patent cliff', 0.55),
        ('generic entry', 0.55),
        ('medicare negotiation', 0.55),
        ('fda warning letter', 0.55),
        ('pharma', 0.6),
    ],
    "medical_devices": [
        ('medical devices', 0.72),
        ('medical instruments', 0.72),
        ('surgical', 0.72),
        ('orthopedic', 0.72),
        ('pacemaker', 0.72),
        ('surgery', 0.65),
        ('hospital', 0.65),
        ('implant', 0.65),
        ('procedure volume', 0.58),
        ('hospital capex', 0.58),
        ('robotics adoption', 0.58),
        ('guidance raise', 0.58),
        ('hospital budget cut', 0.55),
        ('recall', 0.55),
        ('reimbursement cut', 0.55),
        ('elective delay', 0.55),
        ('medical', 0.6),
        ('devices', 0.6),
    ],
    "life_sciences_tools": [
        ('diagnostics', 0.72),
        ('life sciences', 0.72),
        ('research', 0.72),
        ('laboratory', 0.72),
        ('contract research', 0.72),
        ('cro', 0.72),
        ('instrument', 0.65),
        ('sequencing', 0.65),
        ('lab', 0.65),
        ('backlog growth', 0.58),
        ('biotech funding', 0.58),
        ('instrument demand', 0.58),
        ('academic grants', 0.58),
        ('biotech funding winter', 0.55),
        ('capex pause', 0.55),
        ('china weakness', 0.55),
        ('sciences', 0.6),
        ('tools', 0.6),
    ],
    "healthcare_providers": [
        ('health care plans', 0.72),
        ('hospitals', 0.72),
        ('healthcare providers', 0.72),
        ('managed care', 0.72),
        ('health services', 0.72),
        ('medicare', 0.65),
        ('medicaid', 0.65),
        ('mlr', 0.65),
        ('bed', 0.65),
        ('membership growth', 0.58),
        ('medical loss ratio beat', 0.58),
        ('rate increase', 0.58),
        ('utilization stable', 0.58),
        ('mlr miss', 0.55),
        ('medicare cut', 0.55),
        ('nurse wage inflation', 0.55),
        ('utilization spike', 0.55),
        ('healthcare', 0.6),
        ('providers', 0.6),
    ],
    "healthcare_technology": [
        ('health information', 0.72),
        ('healthcare technology', 0.72),
        ('health tech', 0.72),
        ('telehealth', 0.72),
        ('ehr', 0.72),
        ('telehealth', 0.65),
        ('ehr', 0.65),
        ('hipaa', 0.65),
        ('contract win', 0.58),
        ('hospital go-live', 0.58),
        ('saas growth', 0.58),
        ('ARR beat', 0.58),
        ('security breach', 0.55),
        ('privacy fine', 0.55),
        ('churn', 0.55),
        ('telehealth cut', 0.55),
        ('healthcare', 0.6),
        ('technology', 0.6),
    ],
    "residential_reits": [
        ('residential reit', 0.72),
        ('reit—residential', 0.72),
        ('apartment reit', 0.72),
        ('multifamily', 0.72),
        ('rent', 0.65),
        ('multifamily', 0.65),
        ('apartment', 0.65),
        ('mortgage', 0.65),
        ('rent growth', 0.58),
        ('occupancy up', 0.58),
        ('concession down', 0.58),
        ('rate cut', 0.58),
        ('rent decline', 0.55),
        ('supply surge', 0.55),
        ('rate hike', 0.55),
        ('concession increase', 0.55),
        ('residential', 0.6),
        ('reits', 0.6),
    ],
    "commercial_office_reits": [
        ('office reit', 0.72),
        ('reit—office', 0.72),
        ('commercial office', 0.72),
        ('office', 0.65),
        ('wault', 0.65),
        ('occupancy', 0.65),
        ('return to office', 0.58),
        ('lease signed', 0.58),
        ('occupancy stabil', 0.58),
        ('wault extended', 0.58),
        ('default', 0.55),
        ('vacancy rise', 0.55),
        ('cre stress', 0.55),
        ('remote work', 0.55),
        ('commercial', 0.6),
        ('office', 0.6),
        ('reits', 0.6),
    ],
    "retail_reits": [
        ('retail reit', 0.72),
        ('reit—retail', 0.72),
        ('shopping center', 0.72),
        ('mall reit', 0.72),
        ('mall', 0.65),
        ('foot traffic', 0.65),
        ('tenant', 0.65),
        ('foot traffic', 0.58),
        ('tenant sales', 0.58),
        ('re-leasing spread', 0.58),
        ('occupancy cost ratio ok', 0.58),
        ('anchor closure', 0.55),
        ('bankruptcy', 0.55),
        ('retail apocalypse', 0.55),
        ('rent cut', 0.55),
        ('retail', 0.6),
        ('reits', 0.6),
    ],
    "industrial_logistics_reits": [
        ('industrial reit', 0.72),
        ('reit—industrial', 0.72),
        ('warehouse', 0.72),
        ('logistics reit', 0.72),
        ('self storage', 0.72),
        ('warehouse', 0.65),
        ('fulfillment', 0.65),
        ('storage', 0.65),
        ('rent reversion', 0.58),
        ('e-commerce demand', 0.58),
        ('supply chain', 0.58),
        ('development yield', 0.58),
        ('amazon slowdown', 0.55),
        ('oversupply', 0.55),
        ('cap rate expansion', 0.55),
        ('industrial', 0.6),
        ('logistics', 0.6),
        ('reits', 0.6),
    ],
    "specialized_reits": [
        ('data center', 0.72),
        ('cell tower', 0.72),
        ('reit—specialty', 0.72),
        ('reit—diversified', 0.72),
        ('healthcare reit', 0.72),
        ('tower reit', 0.72),
        ('data center', 0.65),
        ('tower', 0.65),
        ('ai server', 0.65),
        ('ai demand', 0.58),
        ('cloud capex', 0.58),
        ('tower lease', 0.58),
        ('power capacity', 0.58),
        ('rate spike', 0.55),
        ('hyperscaler pause', 0.55),
        ('interest expense', 0.55),
        ('specialized', 0.6),
        ('reits', 0.6),
    ],
    "semiconductors": [
        ('semiconductor', 0.72),
        ('semiconductors', 0.72),
        ('chip', 0.72),
        ('gpu', 0.72),
        ('foundry', 0.72),
        ('wafer', 0.65),
        ('chip', 0.65),
        ('foundry', 0.65),
        ('hbm', 0.65),
        ('ai demand', 0.58),
        ('book-to-bill', 0.58),
        ('supply tight', 0.58),
        ('export license', 0.58),
        ('data center', 0.58),
        ('inventory glut', 0.55),
        ('export ban', 0.55),
        ('cycle downturn', 0.55),
        ('book-to-bill below 1', 0.55),
        ('semiconductors', 0.6),
    ],
    "semi_equipment": [
        ('semiconductor equipment', 0.72),
        ('wafer fab', 0.72),
        ('lithography', 0.72),
        ('lithography', 0.65),
        ('fab', 0.65),
        ('capex', 0.65),
        ('fab build', 0.58),
        ('capex raise', 0.58),
        ('chips act', 0.58),
        ('order backlog', 0.58),
        ('fab pause', 0.55),
        ('capex cut', 0.55),
        ('order cancel', 0.55),
        ('semiconductor', 0.6),
        ('equipment', 0.6),
    ],
    "application_software": [
        ('software—application', 0.72),
        ('software application', 0.72),
        ('saas', 0.72),
        ('enterprise software', 0.72),
        ('saas', 0.65),
        ('subscription', 0.65),
        ('seat', 0.65),
        ('nrr above 110', 0.58),
        ('billings beat', 0.58),
        ('seat expansion', 0.58),
        ('ai copilot', 0.58),
        ('nrr decline', 0.55),
        ('churn', 0.55),
        ('budget freeze', 0.55),
        ('multiple compression', 0.55),
        ('application', 0.6),
        ('software', 0.6),
    ],
    "systems_software": [
        ('software—infra', 0.72),
        ('systems software', 0.72),
        ('cybersecurity', 0.72),
        ('security software', 0.72),
        ('database', 0.72),
        ('cyber', 0.65),
        ('cloud', 0.65),
        ('database', 0.65),
        ('arr growth', 0.58),
        ('ransomware spike', 0.58),
        ('cloud migration', 0.58),
        ('platform stickiness', 0.58),
        ('breach at peer', 0.55),
        ('budget defer', 0.55),
        ('open source threat', 0.55),
        ('systems', 0.6),
        ('software', 0.6),
    ],
    "tech_hardware": [
        ('computer hardware', 0.72),
        ('consumer electronics', 0.72),
        ('technology hardware', 0.72),
        ('storage device', 0.72),
        ('iphone', 0.65),
        ('pc', 0.65),
        ('smartphone', 0.65),
        ('foxconn', 0.65),
        ('upgrade cycle', 0.58),
        ('iphone demand', 0.58),
        ('pc recovery', 0.58),
        ('holiday strong', 0.58),
        ('inventory channel', 0.55),
        ('demand miss', 0.55),
        ('component cost', 0.55),
        ('china weak', 0.55),
        ('technology', 0.6),
        ('hardware', 0.6),
    ],
    "diversified_banks": [
        ('banks—diversified', 0.72),
        ('diversified banks', 0.72),
        ('money center', 0.72),
        ('nim', 0.65),
        ('deposit', 0.65),
        ('loan', 0.65),
        ('nim expansion', 0.58),
        ('net interest income', 0.58),
        ('stress test pass', 0.58),
        ('loan growth', 0.58),
        ('credit loss', 0.55),
        ('deposit flight', 0.55),
        ('regulatory fine', 0.55),
        ('inversion', 0.55),
        ('diversified', 0.6),
        ('banks', 0.6),
    ],
    "regional_banks": [
        ('banks—regional', 0.72),
        ('regional banks', 0.72),
        ('cre', 0.65),
        ('deposit beta', 0.65),
        ('unrealized', 0.65),
        ('deposit stable', 0.58),
        ('cre manageable', 0.58),
        ('buyback', 0.58),
        ('cre exposure', 0.55),
        ('unrealized losses', 0.55),
        ('deposit beta spike', 0.55),
        ('run risk', 0.55),
        ('regional', 0.6),
        ('banks', 0.6),
    ],
    "property_casualty_insurance": [
        ('insurance—property', 0.72),
        ('property & casualty', 0.72),
        ('pc insurance', 0.72),
        ('hurricane', 0.65),
        ('wildfire', 0.65),
        ('combined ratio', 0.65),
        ('combined ratio beat', 0.58),
        ('rate increase approved', 0.58),
        ('pricing firm', 0.58),
        ('cat loss', 0.55),
        ('hurricane', 0.55),
        ('wildfire', 0.55),
        ('combined ratio miss', 0.55),
        ('property', 0.6),
        ('casualty', 0.6),
        ('insurance', 0.6),
    ],
    "life_health_insurance": [
        ('insurance—life', 0.72),
        ('life insurance', 0.72),
        ('insurance—diversified', 0.72),
        ('annuity', 0.65),
        ('mortality', 0.65),
        ('long bond', 0.65),
        ('investment income', 0.58),
        ('long bond yield', 0.58),
        ('mortality stable', 0.58),
        ('longevity', 0.55),
        ('rate cut', 0.55),
        ('alternative asset markdown', 0.55),
        ('health', 0.6),
        ('insurance', 0.6),
    ],
    "financial_data_exchanges": [
        ('financial data', 0.72),
        ('capital markets', 0.72),
        ('exchange', 0.72),
        ('asset management', 0.72),
        ('rating agency', 0.72),
        ('volume', 0.65),
        ('vix', 0.65),
        ('aum', 0.65),
        ('trading volume', 0.58),
        ('vix elevated', 0.58),
        ('aum growth', 0.58),
        ('data subscription', 0.58),
        ('volume drought', 0.55),
        ('fee pressure', 0.55),
        ('crypto winter', 0.55),
        ('financial', 0.6),
        ('exchanges', 0.6),
    ],
    "consumer_finance": [
        ('credit services', 0.72),
        ('consumer finance', 0.72),
        ('credit card', 0.72),
        ('payment', 0.72),
        ('delinquency', 0.65),
        ('charge-off', 0.65),
        ('revolving', 0.65),
        ('spend growth', 0.58),
        ('delinquency stable', 0.58),
        ('loan growth', 0.58),
        ('charge-off rise', 0.55),
        ('delinquency spike', 0.55),
        ('rate cap', 0.55),
        ('recession fear', 0.55),
        ('consumer', 0.6),
        ('finance', 0.6),
    ],
    "integrated_oil_gas": [
        ('oil & gas integrated', 0.72),
        ('integrated oil', 0.72),
        ('supermajor', 0.72),
        ('wti', 0.65),
        ('brent', 0.65),
        ('crude', 0.65),
        ('opec', 0.65),
        ('opec cut', 0.58),
        ('crude rally', 0.58),
        ('refining margin', 0.58),
        ('buyback', 0.58),
        ('demand destruction', 0.55),
        ('opec increase', 0.55),
        ('windfall tax', 0.55),
        ('integrated', 0.6),
    ],
    "oil_gas_ep": [
        ('oil & gas e&p', 0.72),
        ('exploration', 0.72),
        ('upstream', 0.72),
        ('natural gas', 0.65),
        ('wti', 0.65),
        ('rig', 0.65),
        ('eia', 0.65),
        ('production beat', 0.58),
        ('hedge gain', 0.58),
        ('rig count', 0.58),
        ('permit', 0.58),
        ('gas glut', 0.55),
        ('basis blowout', 0.55),
        ('decline curve', 0.55),
    ],
    "oil_gas_equipment": [
        ('oil & gas equipment', 0.72),
        ('oilfield services', 0.72),
        ('drilling', 0.72),
        ('rig', 0.65),
        ('dayrate', 0.65),
        ('frac', 0.65),
        ('rig count', 0.58),
        ('international capex', 0.58),
        ('dayrate', 0.58),
        ('capex cut', 0.55),
        ('utilization fall', 0.55),
        ('frac spread narrow', 0.55),
        ('equipment', 0.6),
    ],
    "renewable_energy": [
        ('solar', 0.72),
        ('renewable', 0.72),
        ('clean energy', 0.72),
        ('wind energy', 0.72),
        ('solar', 0.65),
        ('wind', 0.65),
        ('lcoe', 0.65),
        ('ira', 0.65),
        ('ira credit', 0.58),
        ('solar demand', 0.58),
        ('lcoe decline', 0.58),
        ('policy support', 0.58),
        ('rate hike', 0.55),
        ('subsidy cut', 0.55),
        ('module glut', 0.55),
        ('interconnection delay', 0.55),
        ('renewable', 0.6),
        ('energy', 0.6),
    ],
    "electric_gas_utilities": [
        ('utilities—', 0.72),
        ('electric utilities', 0.72),
        ('gas utilities', 0.72),
        ('regulated utility', 0.72),
        ('utility', 0.65),
        ('grid', 0.65),
        ('allowed roe', 0.65),
        ('allowed roe', 0.58),
        ('rate case win', 0.58),
        ('load growth', 0.58),
        ('data center power', 0.58),
        ('rate case loss', 0.55),
        ('wildfire liability', 0.55),
        ('yield competition', 0.55),
        ('electric', 0.6),
        ('utilities', 0.6),
    ],
    "auto_manufacturers": [
        ('auto manufacturers', 0.72),
        ('automobile', 0.72),
        ('motor vehicles', 0.72),
        ('steel', 0.65),
        ('lithium', 0.65),
        ('battery', 0.65),
        ('auto loan', 0.65),
        ('delivery beat', 0.58),
        ('ev demand', 0.58),
        ('inventory days low', 0.58),
        ('incentive cut', 0.58),
        ('strike', 0.55),
        ('inventory glut', 0.55),
        ('price war', 0.55),
        ('recall', 0.55),
        ('manufacturers', 0.6),
    ],
    "luxury_goods": [
        ('luxury', 0.72),
        ('apparel—luxury', 0.72),
        ('designer', 0.72),
        ('premium fashion', 0.72),
        ('luxury', 0.65),
        ('tourist', 0.65),
        ('yuan', 0.65),
        ('china reopen', 0.58),
        ('pricing power', 0.58),
        ('tourist spend', 0.58),
        ('hnw growth', 0.58),
        ('china slowdown', 0.55),
        ('asp reduction', 0.55),
        ('counterfeit', 0.55),
        ('wealth shock', 0.55),
        ('luxury', 0.6),
        ('goods', 0.6),
    ],
    "hotels_resorts_cruise": [
        ('hotels', 0.72),
        ('resorts', 0.72),
        ('cruise', 0.72),
        ('lodging', 0.72),
        ('casino resort', 0.72),
        ('revpar', 0.65),
        ('occupancy', 0.65),
        ('cruise', 0.65),
        ('jet fuel', 0.65),
        ('revpar up', 0.58),
        ('booking strong', 0.58),
        ('load factor', 0.58),
        ('business travel', 0.58),
        ('outbreak', 0.55),
        ('fuel surcharge', 0.55),
        ('geopolitical travel', 0.55),
        ('revpar miss', 0.55),
        ('hotels', 0.6),
        ('cruise', 0.6),
    ],
    "restaurants_food": [
        ('restaurants', 0.72),
        ('food service', 0.72),
        ('fast food', 0.72),
        ('casual dining', 0.72),
        ('beef', 0.65),
        ('wheat', 0.65),
        ('dairy', 0.65),
        ('coffee', 0.65),
        ('corn', 0.65),
        ('food cost', 0.65),
        ('same store sales', 0.58),
        ('digital mix', 0.58),
        ('menu price', 0.58),
        ('traffic up', 0.58),
        ('food cost inflation', 0.55),
        ('wage inflation', 0.55),
        ('traffic down', 0.55),
        ('e.coli', 0.55),
        ('restaurants', 0.6),
    ],
    "hypermarkets_discount": [
        ('discount stores', 0.72),
        ('department stores', 0.72),
        ('hypermarket', 0.72),
        ('supercenter', 0.72),
        ('gasoline', 0.65),
        ('consumer', 0.65),
        ('shrink', 0.65),
        ('traffic up', 0.58),
        ('market share gain', 0.58),
        ('inventory turn', 0.58),
        ('gas savings', 0.58),
        ('shrink', 0.55),
        ('theft', 0.55),
        ('margin pressure', 0.55),
        ('inventory glut', 0.55),
        ('hypermarkets', 0.6),
        ('discount', 0.6),
    ],
    "household_personal_products": [
        ('household', 0.72),
        ('personal products', 0.72),
        ('soap', 0.72),
        ('cosmetics', 0.72),
        ('cleaning', 0.72),
        ('pulp', 0.65),
        ('chemical', 0.65),
        ('soap', 0.65),
        ('pricing power', 0.58),
        ('volume stable', 0.58),
        ('premium mix', 0.58),
        ('private label share', 0.55),
        ('input cost', 0.55),
        ('china weak', 0.55),
        ('household', 0.6),
        ('products', 0.6),
    ],
    "packaged_foods": [
        ('packaged foods', 0.72),
        ('food products', 0.72),
        ('confectioners', 0.72),
        ('beverages—non-alcoholic', 0.72),
        ('corn', 0.65),
        ('wheat', 0.65),
        ('cocoa', 0.65),
        ('sugar', 0.65),
        ('beef', 0.65),
        ('grain', 0.65),
        ('pricing', 0.58),
        ('volume return', 0.58),
        ('snacking trend', 0.58),
        ('distribution gain', 0.58),
        ('glut', 0.55),
        ('grain cost', 0.55),
        ('trade down private label', 0.55),
        ('obesity drug', 0.55),
        ('packaged', 0.6),
        ('foods', 0.6),
    ],
    "aerospace_defense": [
        ('aerospace', 0.72),
        ('defense', 0.72),
        ('aircraft', 0.72),
        ('military', 0.72),
        ('space', 0.72),
        ('defense', 0.65),
        ('backlog', 0.65),
        ('faa', 0.65),
        ('defense budget', 0.58),
        ('backlog record', 0.58),
        ('flight hours', 0.58),
        ('contract award', 0.58),
        ('program delay', 0.55),
        ('grounding', 0.55),
        ('budget cut', 0.55),
        ('strike', 0.55),
        ('aerospace', 0.6),
        ('defense', 0.6),
    ],
    "air_freight_logistics": [
        ('integrated freight', 0.72),
        ('logistics', 0.72),
        ('courier', 0.72),
        ('air freight', 0.72),
        ('jet fuel', 0.65),
        ('diesel', 0.65),
        ('parcel', 0.65),
        ('freight', 0.65),
        ('parcel volume', 0.58),
        ('yield up', 0.58),
        ('e-commerce ship', 0.58),
        ('tender reject', 0.58),
        ('volume miss', 0.55),
        ('jet fuel', 0.55),
        ('trade tariff', 0.55),
        ('capacity add', 0.55),
        ('freight', 0.6),
        ('logistics', 0.6),
    ],
    "railroads": [
        ('railroads', 0.72),
        ('rail freight', 0.72),
        ('class i rail', 0.72),
        ('coal', 0.65),
        ('grain', 0.65),
        ('intermodal', 0.65),
        ('carload', 0.65),
        ('carload up', 0.58),
        ('operating ratio improve', 0.58),
        ('pricing', 0.58),
        ('intermodal', 0.58),
        ('coal decline', 0.55),
        ('strike', 0.55),
        ('weather', 0.55),
        ('regulatory', 0.55),
        ('railroads', 0.6),
    ],
    "construction_machinery": [
        ('farm & construction', 0.72),
        ('construction machinery', 0.72),
        ('heavy machinery', 0.72),
        ('agricultural machinery', 0.72),
        ('steel', 0.65),
        ('copper', 0.65),
        ('infrastructure', 0.65),
        ('dealer inventory down', 0.58),
        ('infrastructure bill', 0.58),
        ('mining capex', 0.58),
        ('backlog', 0.58),
        ('dealer destock', 0.55),
        ('china weak', 0.55),
        ('farm income down', 0.55),
        ('construction', 0.6),
        ('machinery', 0.6),
    ],
    "building_products": [
        ('building products', 0.72),
        ('building materials', 0.72),
        (' lumber', 0.72),
        ('cement', 0.72),
        ('roofing', 0.72),
        ('lumber', 0.65),
        ('cement', 0.65),
        ('housing starts', 0.65),
        ('mortgage', 0.65),
        ('housing starts', 0.58),
        ('repair remodel', 0.58),
        ('pricing', 0.58),
        ('capacity util', 0.58),
        ('mortgage rate spike', 0.55),
        ('housing slowdown', 0.55),
        ('input cost', 0.55),
        ('building', 0.6),
        ('products', 0.6),
    ],
    "chemicals": [
        ('chemicals', 0.72),
        ('specialty chemicals', 0.72),
        ('agricultural inputs', 0.72),
        ('fertilizer', 0.72),
        ('natural gas', 0.65),
        ('ethylene', 0.65),
        ('fertilizer', 0.65),
        ('potash', 0.65),
        ('spread widen', 0.58),
        ('volume up', 0.58),
        ('auto build', 0.58),
        ('crop acreage', 0.58),
        ('gas feedstock spike', 0.55),
        ('destock', 0.55),
        ('china demand', 0.55),
        ('chemicals', 0.6),
    ],
    "metals_mining": [
        ('gold', 0.72),
        ('silver', 0.72),
        ('copper', 0.72),
        ('steel', 0.72),
        ('aluminum', 0.72),
        ('mining', 0.72),
        ('metals', 0.72),
        ('copper', 0.65),
        ('gold', 0.65),
        ('iron ore', 0.65),
        ('lme', 0.65),
        ('steel', 0.65),
        ('copper squeeze', 0.58),
        ('china stimulus', 0.58),
        ('gold safe haven', 0.58),
        ('lme draw', 0.58),
        ('china property', 0.55),
        ('dollar strong', 0.55),
        ('inventory build', 0.55),
        ('metals', 0.6),
        ('mining', 0.6),
    ],
    "wireless_telecom": [
        ('telecom services', 0.72),
        ('wireless', 0.72),
        ('communication services', 0.72),
        ('spectrum', 0.65),
        ('churn', 0.65),
        ('arpu', 0.65),
        ('churn low', 0.58),
        ('arpu up', 0.58),
        ('fiber build', 0.58),
        ('dividend safe', 0.58),
        ('price war', 0.55),
        ('churn spike', 0.55),
        ('capex overhang', 0.55),
        ('yield competition', 0.55),
        ('wireless', 0.6),
        ('telecom', 0.6),
    ],
    "interactive_media": [
        ('internet content', 0.72),
        ('interactive media', 0.72),
        ('search', 0.72),
        ('social media', 0.72),
        ('online advertising', 0.72),
        ('advertising', 0.65),
        ('pixel', 0.65),
        ('dau', 0.65),
        ('ad spend', 0.58),
        ('dau growth', 0.58),
        ('reels monetization', 0.58),
        ('ai search', 0.58),
        ('ad recession', 0.55),
        ('att opt out', 0.55),
        ('antitrust', 0.55),
        ('tiktok competition', 0.55),
        ('interactive', 0.6),
        ('media', 0.6),
    ],
    "entertainment_streaming": [
        ('entertainment', 0.72),
        ('broadcasting', 0.72),
        ('streaming', 0.72),
        ('media—', 0.72),
        ('movie', 0.72),
        ('streaming', 0.65),
        ('box office', 0.65),
        ('subscriber', 0.65),
        ('subscriber add', 0.58),
        ('content hit', 0.58),
        ('pricing tier', 0.58),
        ('box office', 0.58),
        ('churn', 0.55),
        ('content flop', 0.55),
        ('strike', 0.55),
        ('cord cutting margin', 0.55),
        ('entertainment', 0.6),
        ('streaming', 0.6),
    ],
    "environmental_waste": [
        ('waste management', 0.72),
        ('environmental', 0.72),
        ('pollution', 0.72),
        ('recycling', 0.72),
        ('diesel', 0.65),
        ('landfill', 0.65),
        ('tonnage', 0.65),
        ('pricing escalator', 0.58),
        ('volume tonnage', 0.58),
        ('municipal contract', 0.58),
        ('diesel cost', 0.55),
        ('volume soft', 0.55),
        ('recycling price', 0.55),
        ('environmental', 0.6),
        ('waste', 0.6),
    ],
    "apparel_retail": [
        ('apparel retail', 0.72),
        ('specialty retail', 0.72),
        ('footwear', 0.72),
        ('clothing store', 0.72),
        ('cotton', 0.65),
        ('freight', 0.65),
        ('apparel', 0.65),
        ('comp beat', 0.58),
        ('inventory clean', 0.58),
        ('brand heat', 0.58),
        ('china reopen', 0.58),
        ('warm winter', 0.55),
        ('inventory glut', 0.55),
        ('promotional', 0.55),
        ('supply delay', 0.55),
        ('apparel', 0.6),
        ('retail', 0.6),
    ],
    "marine_shipping": [
        ('marine shipping', 0.72),
        ('shipping', 0.72),
        ('tanker', 0.72),
        ('bulk carrier', 0.72),
        ('container ship', 0.72),
        ('baltic', 0.65),
        ('freight rate', 0.65),
        ('tanker', 0.65),
        ('container', 0.65),
        ('baltic dry up', 0.58),
        ('spot rate spike', 0.58),
        ('canal congestion', 0.58),
        ('tanker tight', 0.58),
        ('rate collapse', 0.55),
        ('new supply', 0.55),
        ('trade slowdown', 0.55),
        ('marine', 0.6),
        ('shipping', 0.6),
    ],
    "independent_power_producers": [
        ('independent power', 0.72),
        ('power producers', 0.72),
        ('merchant power', 0.72),
        ('ipp', 0.72),
        ('power price', 0.65),
        ('spark spread', 0.65),
        ('heat', 0.65),
        ('spark spread widen', 0.58),
        ('heat wave', 0.58),
        ('capacity tight', 0.58),
        ('data center power', 0.58),
        ('power price collapse', 0.55),
        ('renewable cannibalization', 0.55),
        ('regulatory', 0.55),
        ('independent', 0.6),
        ('power', 0.6),
        ('producers', 0.6),
    ],
    "commercial_services": [
        ('specialty business services', 0.72),
        ('staffing', 0.72),
        ('security guard', 0.72),
        ('uniform', 0.72),
        ('facility', 0.72),
        ('employment', 0.65),
        ('office', 0.65),
        ('staffing', 0.65),
        ('white collar hiring', 0.58),
        ('contract renewal', 0.58),
        ('cross sell', 0.58),
        ('hiring freeze', 0.55),
        ('office vacancy', 0.55),
        ('wage inflation', 0.55),
        ('commercial', 0.6),
        ('services', 0.6),
    ],
    "distributors": [
        ('distribution', 0.72),
        ('wholesale', 0.72),
        ('industrial distribution', 0.72),
        ('distributor', 0.72),
        ('freight', 0.65),
        ('inventory', 0.65),
        ('working capital', 0.65),
        ('volume growth', 0.58),
        ('pricing pass', 0.58),
        ('inventory turn', 0.58),
        ('digital share', 0.58),
        ('destock', 0.55),
        ('freight cost', 0.55),
        ('customer inventory cut', 0.55),
        ('distributors', 0.6),
    ],
}


def _result(iid: str, confidence: float, reason: str) -> ClassificationResult:
    handler = get_handler(iid)
    return ClassificationResult(
        industry_id=iid,
        industry_name=handler.INDUSTRY_NAME,
        confidence=confidence,
        etf_proxy=handler.ETF_PROXY,
        comovement_mode=handler.COMOVEMENT_MODE.value,
        reasons=[reason],
    )


def match_name_lexicon(
    company_name: str,
    sector: str = "",
    yahoo_industry: str = "",
) -> ClassificationResult | None:
    blob = f"{company_name} {sector} {yahoo_industry}".lower()
    if not blob.strip():
        return None
    best: ClassificationResult | None = None
    for iid, rules in NAME_RULES.items():
        for pat, conf in rules:
            if pat in blob:
                hit = _result(iid, conf, f"name_lex:{pat[:24]}")
                if best is None or hit.confidence > best.confidence:
                    best = hit
    sec = sector.lower().strip()
    if best is None and sec in SECTOR_DEFAULTS:
        return _result(SECTOR_DEFAULTS[sec], 0.52, f"sector_default:{sec}")
    return best


def suffix_industry(symbol: str) -> str | None:
    sym = symbol.strip().upper()
    for suffix, iid in sorted(SYMBOL_SUFFIX.items(), key=lambda x: -len(x[0])):
        if sym.endswith(suffix):
            return iid
    return None

